import type { LevelContent } from "@/lib/types";

export const a1: LevelContent = {
  level: "A1",

  grammar: [
    {
      id: "a1-nouns-gender",
      title: "Nouns: Gender & Number",
      explanation:
        "Every French noun is masculine or feminine. You must learn the gender with the noun: le/un for masculine, la/une for feminine. Plural adds -s (usually). Article also changes: les/des for plurals.",
      examples: [
        { fr: "le livre / les livres", en: "the book / the books" },
        { fr: "la chaise / les chaises", en: "the chair / the chairs" },
        { fr: "un garçon, une fille", en: "a boy, a girl" },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Unit 1: Nouns and Gender",
      exercises: [
        {
          id: "a1-nouns-gender-1",
          type: "multiple_choice",
          prompt: "Choose the correct masculine article: ___ garçon",
          options: ["la", "le", "les", "un"],
          answer: 1,
          skill: "grammar",
          explain: "‘garçon’ (boy) is masculine, so we use ‘le’.",
        },
        {
          id: "a1-nouns-gender-2",
          type: "multiple_choice",
          prompt: "Choose the correct feminine article: ___ table",
          options: ["le", "un", "la", "les"],
          answer: 2,
          skill: "grammar",
          explain: "‘table’ (table) is feminine, so we use ‘la’.",
        },
        {
          id: "a1-nouns-gender-3",
          type: "fill_in_blank",
          prompt: "Write the definite article for: ___ école (feminine) — use the elided form before a vowel.",
          answer: "l'",
          answerVariants: ["l'"],
          skill: "grammar",
          explain: "Before a vowel sound, le/la become l‘.",
        },
      ],
    },
    {
      id: "a1-articles",
      title: "Articles: Definite, Indefinite & Partitive",
      explanation:
        "le/la/l'/les = the. un/une/des = a, some. du/de la/de l'/des = partitive (some, used for uncountable things like food and water). Partitive becomes de after negation.",
      examples: [
        { fr: "Je mange le pain.", en: "I eat the bread." },
        { fr: "Je mange du pain.", en: "I eat some bread." },
        { fr: "Je ne mange pas de pain.", en: "I don't eat any bread." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Unit 2: Articles",
      exercises: [
        {
          id: "a1-articles-1",
          type: "multiple_choice",
          prompt: "Complete: Je bois ___ eau. (I drink some water.)",
          options: ["le", "de la", "du", "les"],
          answer: 1,
          skill: "grammar",
          explain: "‘eau’ is feminine and uncountable here → partitive ‘de la’.",
        },
        {
          id: "a1-articles-2",
          type: "translation",
          prompt: "Translate to French: I eat some bread.",
          answer: "Je mange du pain",
          answerVariants: ["je mange du pain"],
          skill: "grammar",
        },
        {
          id: "a1-articles-3",
          type: "fill_in_blank",
          prompt: "Negation: Je ne mange pas ___ pain.",
          answer: "de",
          skill: "grammar",
          explain: "After negation, partitive du/de la/des → de.",
        },
      ],
    },
    {
      id: "a1-etre-avoir",
      title: "Être & Avoir (Present)",
      explanation:
        "être (to be): je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont. avoir (to have): j'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont. They are the two most important verbs in French.",
      examples: [
        { fr: "Je suis étudiant.", en: "I am a student." },
        { fr: "J'ai un chien.", en: "I have a dog." },
        { fr: "Nous sommes contents.", en: "We are happy." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Être and Avoir",
      exercises: [
        {
          id: "a1-etre-avoir-1",
          type: "multiple_choice",
          prompt: "Complete: Nous ___ français.",
          options: ["sommes", "êtes", "avons", "sont"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "a1-etre-avoir-2",
          type: "fill_in_blank",
          prompt: "Complete with avoir: Tu ___ dix-huit ans.",
          answer: "as",
          skill: "grammar",
          explain: "avoir, tu → as.",
        },
        {
          id: "a1-etre-avoir-3",
          type: "translation",
          prompt: "Translate to French: She is happy.",
          answer: "Elle est contente",
          answerVariants: ["elle est contente", "elle est heureuse"],
          skill: "grammar",
        },
      ],
    },
    {
      id: "a1-er-verbs",
      title: "Regular -er Verbs (Present)",
      explanation:
        "Most French verbs end in -er (parler, manger, aimer). Remove -er and add: -e, -es, -e, -ons, -ez, -ent. Note the endings for je/tu/il are silent — the pronunciation is the same.",
      examples: [
        { fr: "Je parle français.", en: "I speak French." },
        { fr: "Ils habitent à Paris.", en: "They live in Paris." },
        { fr: "Nous aimons le café.", en: "We like coffee." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Regular -er Verbs",
      exercises: [
        {
          id: "a1-er-verbs-1",
          type: "fill_in_blank",
          prompt: "Conjugate parler (je): Je ___ avec Marie.",
          answer: "parle",
          skill: "grammar",
        },
        {
          id: "a1-er-verbs-2",
          type: "multiple_choice",
          prompt: "Complete: Ils ___ beaucoup.",
          options: ["travaille", "travaillons", "travaillent", "travailles"],
          answer: 2,
          skill: "grammar",
        },
        {
          id: "a1-er-verbs-3",
          type: "ordering",
          prompt: "Put the words in order: (je / parle / français / ne / pas)",
          parts: ["Je", "ne", "parle", "pas", "français"],
          answer: [0, 1, 2, 3, 4],
          skill: "grammar",
        },
      ],
    },
    {
      id: "a1-ir-re-verbs",
      title: "Regular -ir and -re Verbs",
      explanation:
        "-ir verbs (finir, choisir): -is, -is, -it, -issons, -issez, -issent. -re verbs (vendre, attendre): -s, -s, -, -ons, -ez, -ent. These drop and add endings to the stem.",
      examples: [
        { fr: "Je finis mes devoirs.", en: "I finish my homework." },
        { fr: "Nous vendons notre maison.", en: "We sell our house." },
        { fr: "Elle attend le bus.", en: "She waits for the bus." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, -ir and -re Verbs",
      exercises: [
        {
          id: "a1-ir-re-verbs-1",
          type: "multiple_choice",
          prompt: "Complete: Je ___ mes devoirs.",
          options: ["finis", "finit", "finissions", "finissez"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "a1-ir-re-verbs-2",
          type: "fill_in_blank",
          prompt: "Conjugate attendre (nous): Nous ___ le train.",
          answer: "attendons",
          skill: "grammar",
        },
      ],
    },
    {
      id: "a1-negation",
      title: "Negation: ne…pas",
      explanation:
        "To make a sentence negative, put ne before the verb and pas after it: Je ne parle pas. In everyday speech, ne is often dropped: Je parle pas. With compound verbs, pas goes after the conjugated verb.",
      examples: [
        { fr: "Je ne mange pas de viande.", en: "I don't eat meat." },
        { fr: "Il ne travaille pas ici.", en: "He doesn't work here." },
        { fr: "Nous n'aimons pas le froid.", en: "We don't like the cold." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Negation",
      exercises: [
        {
          id: "a1-negation-1",
          type: "multiple_choice",
          prompt: "Choose the correct negative: Je ___ aime ___ le chocolat.",
          options: ["ne / pas", "pas / ne", "ne / plus", "n' / rien"],
          answer: 0,
          skill: "grammar",
          explain: "ne before the verb, pas after it.",
        },
        {
          id: "a1-negation-2",
          type: "fill_in_blank",
          prompt: "Turn negative: Il parle anglais. → Il ___ parle pas anglais.",
          answer: "ne",
          skill: "grammar",
        },
      ],
    },
    {
      id: "a1-questions",
      title: "Asking Questions",
      explanation:
        "Three ways to ask: 1) Intonation (rising voice): Tu aimes le café ? 2) Est-ce que: Est-ce que tu aimes le café ? 3) Inversion: Aimes-tu le café ? Question words: qui (who), que (what), où (where), quand (when), pourquoi (why), comment (how), combien (how much/many).",
      examples: [
        { fr: "Où habitez-vous ?", en: "Where do you live?" },
        { fr: "Est-ce que tu parles français ?", en: "Do you speak French?" },
        { fr: "Combien ça coûte ?", en: "How much does it cost?" },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Interrogative forms",
      exercises: [
        {
          id: "a1-questions-1",
          type: "multiple_choice",
          prompt: "Which question word fits: « ___ est-ce que tu habites ? » — Paris.",
          options: ["Qui", "Où", "Quand", "Comment"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "a1-questions-2",
          type: "translation",
          prompt: "Translate to French: Do you speak French?",
          answer: "Parle-tu français ?",
          answerVariants: [
            "Est-ce que tu parles français",
            "est-ce que tu parles francais",
          ],
          skill: "grammar",
        },
      ],
    },
    {
      id: "a1-adjectives",
      title: "Adjectives: Agreement & Placement",
      explanation:
        "Adjectives agree with the noun: un petit garçon / une petite fille. Most go after the noun (un livre intéressant), but common ones go before (beau, bon, grand, petit, jeune, nouveau).",
      examples: [
        { fr: "un grand hôtel", en: "a big hotel" },
        { fr: "une maison blanche", en: "a white house" },
        { fr: "des amis sympas", en: "friendly friends" },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Adjectives",
      exercises: [
        {
          id: "a1-adjectives-1",
          type: "multiple_choice",
          prompt: "Correct feminine form: une fille ___",
          options: ["grand", "grande", "grands", "grandes"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "a1-adjectives-2",
          type: "fill_in_blank",
          prompt: "Complete with the masculine singular adjective: un ___ hôtel (white)",
          answer: "blanc",
          skill: "grammar",
        },
      ],
    },
    {
      id: "a1-possed-dem",
      title: "Possessive & Demonstrative Adjectives",
      explanation:
        "Possessives: mon/ma/mes (my), ton/ta/tes (your), son/sa/ses (his/her), notre/nos (our), votre/vos (your), leur/leurs (their). Demonstratives: ce/cet/ces (this/that/these). cet is used before a vowel.",
      examples: [
        { fr: "mon père, ma mère, mes parents", en: "my father, my mother, my parents" },
        { fr: "ce livre / cette maison / ces enfants", en: "this book / this house / these children" },
        { fr: "cet homme", en: "this man (vowel sound after cet)" },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Possessive and demonstrative adjectives",
      exercises: [
        {
          id: "a1-poss-dem-1",
          type: "multiple_choice",
          prompt: "Complete: C'est ___ livre. (this)",
          options: ["cette", "ce", "ces", "cet"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "a1-poss-dem-2",
          type: "fill_in_blank",
          prompt: "Complete with possessive: C'est ___ mère. (my)",
          answer: "ma",
          skill: "grammar",
          explain: "mère is feminine singular → ma.",
        },
      ],
    },
    {
      id: "a1-prepositions-time",
      title: "Prepositions & Telling Time",
      explanation:
        "Place: à (at/to), dans (in), sur (on), sous (under), devant (in front of), derrière (behind). Say the time with Il est: Il est trois heures (3:00), Il est trois heures et demie (3:30), Il est quatre heures moins le quart (3:45).",
      examples: [
        { fr: "Le livre est sur la table.", en: "The book is on the table." },
        { fr: "Il est deux heures.", en: "It's two o'clock." },
        { fr: "J'habite dans un appartement.", en: "I live in an apartment." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Prepositions and time",
      exercises: [
        {
          id: "a1-prep-time-1",
          type: "multiple_choice",
          prompt: "The cat is ___ the chair (under): Le chat est ___ la chaise.",
          options: ["sur", "sous", "dans", "devant"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "a1-prep-time-2",
          type: "fill_in_blank",
          prompt: "What time is 3:30? Il est trois heures et ___.",
          answer: "demie",
          answerVariants: ["demi"],
          skill: "grammar",
        },
      ],
    },
    {
      id: "a1-numbers",
      title: "Numbers & The Date",
      explanation:
        "0-20: zéro, un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix, onze, douze, treize, quatorze, quinze, seize, dix-sept, dix-huit, dix-neuf, vingt. 20=vingt, 30=trente, 40=quarante, 50=cinquante, 60=soixante. 21 = vingt et un (but 22 = vingt-deux). Dates: Nous sommes le 5 mai (2026).",
      examples: [
        { fr: "vingt et un livres", en: "twenty-one books" },
        { fr: "Aujourd'hui, nous sommes le 15 mars.", en: "Today is March 15." },
        { fr: "Il coûte cinquante euros.", en: "It costs fifty euros." },
      ],
      bookChapters: "Complete French All-in-One — Essentials, Numbers and dates",
      exercises: [
        {
          id: "a1-numbers-1",
          type: "multiple_choice",
          prompt: "What is 70 in French?",
          options: ["soixante-dix", "septante", "soixante", "dix-sept"],
          answer: 0,
          skill: "grammar",
          explain: "70 is literally 'sixty-ten' in French.",
        },
        {
          id: "a1-numbers-2",
          type: "fill_in_blank",
          prompt: "Write 22 in French (two words, lower case):",
          answer: "vingt-deux",
          answerVariants: ["vingt deux"],
          skill: "grammar",
        },
      ],
    },
  ],

  vocabulary: [
    {
      theme: "Greetings & Introductions",
      items: [
        { fr: "Bonjour", en: "Hello / Good morning", ipa: "/bɔ̃ʒuʁ/", example: "Bonjour, comment ça va ?", exampleEn: "Hello, how are you?" },
        { fr: "Salut", en: "Hi (informal)", ipa: "/saly/", example: "Salut Marie !", exampleEn: "Hi Marie!" },
        { fr: "Au revoir", en: "Goodbye", ipa: "/o ʁəvwaʁ/", example: "Au revoir, à demain !", exampleEn: "Goodbye, see you tomorrow!" },
        { fr: "Bonsoir", en: "Good evening", ipa: "/bɔ̃swaʁ/", example: "Bonsoir et bienvenue.", exampleEn: "Good evening and welcome." },
        { fr: "Merci", en: "Thank you", ipa: "/mɛʁsi/", example: "Merci beaucoup !", exampleEn: "Thank you very much!" },
        { fr: "S'il vous plaît", en: "Please (formal)", ipa: "/sil vu plɛ/", example: "Un café, s'il vous plaît.", exampleEn: "A coffee, please." },
        { fr: "Oui", en: "Yes", example: "Oui, d'accord.", exampleEn: "Yes, okay." },
        { fr: "Non", en: "No", example: "Non, merci.", exampleEn: "No, thank you." },
        { fr: "Comment ça va ?", en: "How are you?", example: "Comment ça va aujourd'hui ?", exampleEn: "How are you today?" },
        { fr: "Ça va bien", en: "I'm doing well", example: "Ça va bien, merci.", exampleEn: "I'm doing well, thanks." },
        { fr: "Je m'appelle…", en: "My name is…", example: "Je m'appelle Claire.", exampleEn: "My name is Claire." },
        { fr: "Enchanté(e)", en: "Nice to meet you", example: "Enchantée, Madame.", exampleEn: "Nice to meet you, Ma'am." },
      ],
    },
    {
      theme: "Family & People",
      items: [
        { fr: "la famille", en: "the family", example: "J'aime ma famille.", exampleEn: "I love my family." },
        { fr: "le père", en: "the father", example: "Mon père est médecin.", exampleEn: "My father is a doctor." },
        { fr: "la mère", en: "the mother", example: "Ma mère est professeur.", exampleEn: "My mother is a teacher." },
        { fr: "le frère", en: "the brother", example: "J'ai un frère.", exampleEn: "I have one brother." },
        { fr: "la sœur", en: "the sister", example: "Ma sœur a quinze ans.", exampleEn: "My sister is fifteen." },
        { fr: "le fils", en: "the son", example: "Leur fils est grand.", exampleEn: "Their son is tall." },
        { fr: "la fille", en: "the daughter / girl", example: "Leur fille s'appelle Zoé.", exampleEn: "Their daughter is named Zoé." },
        { fr: "l'homme", en: "the man", example: "L'homme lit le journal.", exampleEn: "The man reads the newspaper." },
        { fr: "la femme", en: "the woman / wife", example: "Cette femme est sympathique.", exampleEn: "This woman is nice." },
        { fr: "l'ami / l'amie", en: "the friend (m/f)", example: "C'est mon ami Paul.", exampleEn: "This is my friend Paul." },
        { fr: "les parents", en: "the parents", example: "Mes parents habitent ici.", exampleEn: "My parents live here." },
        { fr: "l'enfant", en: "the child", example: "L'enfant dort.", exampleEn: "The child is sleeping." },
      ],
    },
    {
      theme: "Numbers, Colors & Dates",
      items: [
        { fr: "un, deux, trois", en: "one, two, three", example: "Un, deux, trois, quatre.", exampleEn: "One, two, three, four." },
        { fr: "dix, vingt, cent", en: "ten, twenty, hundred", example: "Il a cent euros.", exampleEn: "He has a hundred euros." },
        { fr: "rouge", en: "red", example: "La voiture est rouge.", exampleEn: "The car is red." },
        { fr: "bleu", en: "blue", example: "Le ciel est bleu.", exampleEn: "The sky is blue." },
        { fr: "vert", en: "green", example: "Les feuilles sont vertes.", exampleEn: "The leaves are green." },
        { fr: "jaune", en: "yellow", example: "Le soleil est jaune.", exampleEn: "The sun is yellow." },
        { fr: "noir", en: "black", example: "J'ai un chat noir.", exampleEn: "I have a black cat." },
        { fr: "blanc", en: "white", example: "Une robe blanche.", exampleEn: "A white dress." },
        { fr: "aujourd'hui", en: "today", example: "Aujourd'hui, il fait beau.", exampleEn: "Today the weather is nice." },
        { fr: "demain", en: "tomorrow", example: "À demain !", exampleEn: "See you tomorrow!" },
        { fr: "lundi, mardi, mercredi", en: "Monday, Tuesday, Wednesday", example: "Je travaille lundi.", exampleEn: "I work on Monday." },
        { fr: "janvier, février", en: "January, February", example: "Janvier est froid.", exampleEn: "January is cold." },
      ],
    },
    {
      theme: "Food & Drink",
      items: [
        { fr: "le pain", en: "the bread", example: "J'achète du pain.", exampleEn: "I buy some bread." },
        { fr: "l'eau", en: "the water", example: "Je bois de l'eau.", exampleEn: "I drink water." },
        { fr: "le café", en: "the coffee", example: "Un café, s'il vous plaît.", exampleEn: "A coffee, please." },
        { fr: "le thé", en: "the tea", example: "Elle prend du thé.", exampleEn: "She has some tea." },
        { fr: "le lait", en: "the milk", example: "Le lait est blanc.", exampleEn: "Milk is white." },
        { fr: "le fromage", en: "the cheese", example: "La France est célèbre pour le fromage.", exampleEn: "France is famous for cheese." },
        { fr: "la pomme", en: "the apple", example: "Je mange une pomme.", exampleEn: "I eat an apple." },
        { fr: "le poulet", en: "the chicken", example: "Nous mangeons du poulet.", exampleEn: "We eat chicken." },
        { fr: "le poisson", en: "the fish", example: "Le poisson est frais.", exampleEn: "The fish is fresh." },
        { fr: "les légumes", en: "the vegetables", example: "J'aime les légumes.", exampleEn: "I like vegetables." },
        { fr: "le sucre", en: "the sugar", example: "Un café avec du sucre.", exampleEn: "A coffee with sugar." },
        { fr: "le petit-déjeuner", en: "the breakfast", example: "Le petit-déjeuner est à huit heures.", exampleEn: "Breakfast is at eight." },
      ],
    },
    {
      theme: "Daily Routine",
      items: [
        { fr: "se lever", en: "to get up", example: "Je me lève à sept heures.", exampleEn: "I get up at seven." },
        { fr: "se laver", en: "to wash (oneself)", example: "Je me lave le visage.", exampleEn: "I wash my face." },
        { fr: "manger", en: "to eat", example: "Je mange à midi.", exampleEn: "I eat at noon." },
        { fr: "boire", en: "to drink", example: "Je bois de l'eau.", exampleEn: "I drink water." },
        { fr: "travailler", en: "to work", example: "Je travaille tous les jours.", exampleEn: "I work every day." },
        { fr: "étudier", en: "to study", example: "J'étudie le français.", exampleEn: "I study French." },
        { fr: "dormir", en: "to sleep", example: "Je dors huit heures.", exampleEn: "I sleep eight hours." },
        { fr: "s'habiller", en: "to get dressed", example: "Je m'habille vite.", exampleEn: "I get dressed quickly." },
        { fr: "sortir", en: "to go out", example: "Nous sortons le soir.", exampleEn: "We go out in the evening." },
        { fr: "rentrer", en: "to come home", example: "Je rentre à dix-huit heures.", exampleEn: "I come home at six pm." },
        { fr: "regarder la télévision", en: "to watch television", example: "Je regarde la télévision le soir.", exampleEn: "I watch TV in the evening." },
        { fr: "prendre", en: "to take", example: "Je prends le bus.", exampleEn: "I take the bus." },
      ],
    },
    {
      theme: "Weather & Seasons",
      items: [
        { fr: "il fait beau", en: "the weather is nice", example: "Aujourd'hui, il fait beau.", exampleEn: "Today the weather is nice." },
        { fr: "il fait chaud", en: "it is hot", example: "En été, il fait chaud.", exampleEn: "In summer it's hot." },
        { fr: "il fait froid", en: "it is cold", example: "En hiver, il fait froid.", exampleEn: "In winter it's cold." },
        { fr: "il pleut", en: "it is raining", example: "Il pleut beaucoup à Paris.", exampleEn: "It rains a lot in Paris." },
        { fr: "il neige", en: "it is snowing", example: "Il neige en décembre.", exampleEn: "It snows in December." },
        { fr: "le soleil", en: "the sun", example: "Le soleil brille.", exampleEn: "The sun is shining." },
        { fr: "la pluie", en: "the rain", example: "Je n'aime pas la pluie.", exampleEn: "I don't like the rain." },
        { fr: "le printemps", en: "spring", example: "Au printemps, les fleurs poussent.", exampleEn: "In spring, flowers grow." },
        { fr: "l'été", en: "summer", example: "L'été, je vais à la plage.", exampleEn: "In summer I go to the beach." },
        { fr: "l'automne", en: "autumn/fall", example: "En automne, les feuilles tombent.", exampleEn: "In autumn, leaves fall." },
        { fr: "l'hiver", en: "winter", example: "L'hiver est long ici.", exampleEn: "Winter is long here." },
        { fr: "la neige", en: "the snow", example: "La neige est blanche.", exampleEn: "Snow is white." },
      ],
    },
    {
      theme: "Clothing",
      items: [
        { fr: "les vêtements", en: "the clothes", example: "J'achète des vêtements.", exampleEn: "I buy clothes." },
        { fr: "la chemise", en: "the shirt", example: "La chemise est blanche.", exampleEn: "The shirt is white." },
        { fr: "le pantalon", en: "the trousers/pants", example: "Ce pantalon est noir.", exampleEn: "These pants are black." },
        { fr: "la robe", en: "the dress", example: "Elle porte une robe rouge.", exampleEn: "She wears a red dress." },
        { fr: "la jupe", en: "the skirt", example: "Une jupe bleue.", exampleEn: "A blue skirt." },
        { fr: "les chaussures", en: "the shoes", example: "Mes chaussures sont confortables.", exampleEn: "My shoes are comfortable." },
        { fr: "le manteau", en: "the coat", example: "Il fait froid, prends ton manteau.", exampleEn: "It's cold, take your coat." },
        { fr: "le chapeau", en: "the hat", example: "Un chapeau élégant.", exampleEn: "An elegant hat." },
        { fr: "porter", en: "to wear", example: "Je porte un jean.", exampleEn: "I'm wearing jeans." },
        { fr: "acheter", en: "to buy", example: "J'achète une veste.", exampleEn: "I buy a jacket." },
        { fr: "le pull", en: "the sweater", example: "Ce pull est en laine.", exampleEn: "This sweater is wool." },
        { fr: "les chaussettes", en: "the socks", example: "J'ai perdu une chaussette.", exampleEn: "I lost a sock." },
      ],
    },
    {
      theme: "Home & City",
      items: [
        { fr: "la maison", en: "the house", example: "J'habite dans une maison.", exampleEn: "I live in a house." },
        { fr: "l'appartement", en: "the apartment", example: "Notre appartement est petit.", exampleEn: "Our apartment is small." },
        { fr: "la chambre", en: "the bedroom", example: "Ma chambre est au premier étage.", exampleEn: "My bedroom is upstairs." },
        { fr: "la cuisine", en: "the kitchen", example: "La cuisine est moderne.", exampleEn: "The kitchen is modern." },
        { fr: "la salle de bains", en: "the bathroom", example: "La salle de bains est propre.", exampleEn: "The bathroom is clean." },
        { fr: "la table", en: "the table", example: "Le dîner est sur la table.", exampleEn: "Dinner is on the table." },
        { fr: "la porte", en: "the door", example: "Ferme la porte, s'il te plaît.", exampleEn: "Close the door, please." },
        { fr: "la fenêtre", en: "the window", example: "Ouvre la fenêtre !", exampleEn: "Open the window!" },
        { fr: "la rue", en: "the street", example: "La rue est calme.", exampleEn: "The street is quiet." },
        { fr: "la ville", en: "the city", example: "Paris est une grande ville.", exampleEn: "Paris is a big city." },
        { fr: "le magasin", en: "the shop", example: "Le magasin ferme à 19h.", exampleEn: "The shop closes at 7 pm." },
        { fr: "le parc", en: "the park", example: "Nous allons au parc.", exampleEn: "We go to the park." },
      ],
    },
    {
      theme: "Jobs & Professions",
      items: [
        { fr: "le travail", en: "the work", example: "J'aime mon travail.", exampleEn: "I like my work." },
        { fr: "le médecin", en: "the doctor", example: "Le médecin arrive.", exampleEn: "The doctor is coming." },
        { fr: "le professeur", en: "the teacher", example: "Le professeur explique.", exampleEn: "The teacher explains." },
        { fr: "l'ingénieur", en: "the engineer", example: "Il est ingénieur.", exampleEn: "He is an engineer." },
        { fr: "l'étudiant", en: "the student", example: "Je suis étudiant.", exampleEn: "I am a student." },
        { fr: "le vendeur", en: "the salesman", example: "Le vendeur est poli.", exampleEn: "The salesman is polite." },
        { fr: "le cuisinier", en: "the cook", example: "Le cuisinier prépare le repas.", exampleEn: "The cook prepares the meal." },
        { fr: "le peintre", en: "the painter", example: "Le peintre travaille ici.", exampleEn: "The painter works here." },
        { fr: "la secrétaire", en: "the secretary", example: "La secrétaire répond au téléphone.", exampleEn: "The secretary answers the phone." },
        { fr: "l'agriculteur", en: "the farmer", example: "L'agriculteur cultive le blé.", exampleEn: "The farmer grows wheat." },
        { fr: "gagner", en: "to earn", example: "Il gagne bien sa vie.", exampleEn: "He earns a good living." },
        { fr: "chercher", en: "to look for", example: "Je cherche un emploi.", exampleEn: "I'm looking for a job." },
      ],
    },
  ],

  phrases: [
    { fr: "Excusez-moi", en: "Excuse me", example: "Excusez-moi, où est la gare ?", exampleEn: "Excuse me, where is the station?" },
    { fr: "Je ne comprends pas", en: "I don't understand", example: "Je ne comprends pas, parlez plus lentement.", exampleEn: "I don't understand, speak more slowly." },
    { fr: "Pouvez-vous répéter ?", en: "Can you repeat?", example: "Pouvez-vous répéter, s'il vous plaît ?", exampleEn: "Can you repeat, please?" },
    { fr: "Où sont les toilettes ?", en: "Where is the bathroom?", example: "Où sont les toilettes ?", exampleEn: "Where are the toilets?" },
    { fr: "Quelle heure est-il ?", en: "What time is it?", example: "Quelle heure est-il ?", exampleEn: "What time is it?" },
    { fr: "Combien ça coûte ?", en: "How much does it cost?", example: "Combien ça coûte ?", exampleEn: "How much does this cost?" },
    { fr: "Je voudrais…", en: "I would like…", example: "Je voudrais un café.", exampleEn: "I would like a coffee." },
    { fr: "J'ai faim", en: "I'm hungry", example: "J'ai faim, allons manger.", exampleEn: "I'm hungry, let's go eat." },
    { fr: "J'ai soif", en: "I'm thirsty", example: "J'ai soif, je bois de l'eau.", exampleEn: "I'm thirsty, I'll drink water." },
    { fr: "À tout à l'heure", en: "See you soon", example: "À tout à l'heure !", exampleEn: "See you in a bit!" },
    { fr: "Pas de problème", en: "No problem", example: "Pas de problème, bien sûr.", exampleEn: "No problem, of course." },
    { fr: "Je suis désolé(e)", en: "I'm sorry", example: "Je suis désolé, je suis en retard.", exampleEn: "I'm sorry, I'm late." },
  ],

  pronunciation: {
    phonemes: [
      { symbol: "ɑ̃", name: "Open nasal vowel (an/en)", examples: ["enfant", "maman", "champ"], note: "The sound in 'an' and 'en': mouth open, air goes through the nose." },
      { symbol: "ɔ̃", name: "Closed nasal vowel (on)", examples: ["bon", "maison", "pont"], note: "Round your lips more than for 'ɑ̃'." },
      { symbol: "ɛ̃", name: "Front nasal vowel (in/ain)", examples: ["pain", "main", "vin"], note: "Like 'an' but with the tongue more forward." },
      { symbol: "ø / œ", name: "Round e (eu)", examples: ["deux", "peur", "neuf"], note: "Lips rounded like for 'u', but say 'e'." },
      { symbol: "y", name: "French u", examples: ["tu", "du", "jus"], note: "Round your lips for 'oo' but say 'ee' — there is no English equivalent." },
      { symbol: "u", name: "ou", examples: ["vous", "tout", "route"], note: "Like English 'oo' in 'food'." },
      { symbol: "ʁ", name: "Voiced uvular r", examples: ["rouge", "paris", "beurre"], note: "The French r is produced at the back of the throat." },
      { symbol: "ʃ / ʒ", name: "Ch / J", examples: ["chat", "jupe", "chérie"], note: "ch=/ʃ/, j=/ʒ/ (like the 's' in 'measure')." },
    ],
    minimalPairs: [
      { a: "dessus", b: "dessous" },
      { a: "du", b: "dou" },
      { a: "tu", b: "tout" },
      { a: "pu", b: "pou" },
      { a: "bon", b: "banc" },
      { a: "vin", b: "vent" },
      { a: "pain", b: "pente" },
      { a: "rue", b: "roue" },
      { a: "chat", b: "chaque" },
      { a: "jeu", b: "jus" },
    ],
    rules: [
      "When two consonants are followed by a vowel (e.g., paris), the final consonant is silent unless it is c, r, f, or l.",
      "Nasal vowels are NOT followed by a pronounced n or m in the same syllable.",
      "Final -e is usually silent (elle, table, porte).",
      "h at the start of a word is silent.",
    ],
  },

  listening: [
    {
      id: "a1-listen-1",
      title: "A Simple Introduction",
      text: "Bonjour ! Je m'appelle Sophie. J'ai vingt-cinq ans. J'habite à Lyon avec ma famille. Je suis professeur et j'aime beaucoup mon travail. Le week-end, j'aime aller au parc avec mes amis.",
      questions: [
        {
          id: "a1-listen-1-q1",
          type: "multiple_choice",
          prompt: "Quel est le prénom de la femme ?",
          options: ["Camille", "Sophie", "Marie", "Zoé"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "a1-listen-1-q2",
          type: "multiple_choice",
          prompt: "Où habite-t-elle ?",
          options: ["À Paris", "À Lyon", "À Marseille", "À Nice"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "a1-listen-1-q3",
          type: "multiple_choice",
          prompt: "Quel est son métier ?",
          options: ["Professeur", "Médecin", "Ingénieur", "Secrétaire"],
          answer: 0,
          skill: "listening",
        },
      ],
    },
    {
      id: "a1-listen-2",
      title: "Buying a Coffee",
      text: "Bonjour, je voudrais un café, s'il vous plaît. — Avec du lait ? — Non, sans lait, merci. — C'est deux euros cinquante. — Voilà trois euros. — Et voilà votre monnaie. — Merci, au revoir !",
      questions: [
        {
          id: "a1-listen-2-q1",
          type: "multiple_choice",
          prompt: "Que veut le client ?",
          options: ["Un thé", "Un café sans lait", "Un chocolat", "Un jus d'orange"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "a1-listen-2-q2",
          type: "multiple_choice",
          prompt: "Combien coûte le café ?",
          options: ["Un euro", "Deux euros cinquante", "Trois euros", "Deux euros"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
    {
      id: "a1-listen-3",
      title: "A Message on the Machine",
      text: "Salut, c'est Marc. Je suis chez le médecin. Je rentre à dix-huit heures. On se voit ce soir au parc ? Réponds-moi quand tu peux. À tout à l'heure !",
      questions: [
        {
          id: "a1-listen-3-q1",
          type: "multiple_choice",
          prompt: "Où est Marc ?",
          options: ["Au travail", "Chez le médecin", "Au parc", "À la maison"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "a1-listen-3-q2",
          type: "multiple_choice",
          prompt: "À quelle heure rentre-t-il ?",
          options: ["À huit heures", "À six heures du soir", "À midi", "À sept heures"],
          answer: 1,
          skill: "listening",
          explain: "18h00 = six heures du soir.",
        },
      ],
    },
  ],

  reading: [
    {
      id: "a1-read-1",
      title: "Un e-mail de Julie",
      text: "Salut Lucas, Comment ça va ? Moi, ça va très bien. Aujourd'hui, il fait beau à Nice. Je vais à la plage avec mon frère. Ce soir, nous mangeons dans un restaurant italien. Je t'appelle demain. Gros bisous, Julie",
      questions: [
        {
          id: "a1-read-1-q1",
          type: "multiple_choice",
          prompt: "Où est Julie ?",
          options: ["À Paris", "À Lyon", "À Nice", "À Marseille"],
          answer: 2,
          skill: "reading",
        },
        {
          id: "a1-read-1-q2",
          type: "multiple_choice",
          prompt: "Quel temps fait-il ?",
          options: ["Il pleut", "Il fait beau", "Il neige", "Il fait froid"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a1-read-1-q3",
          type: "multiple_choice",
          prompt: "Où mangent-ils ce soir ?",
          options: ["À la maison", "Dans un restaurant italien", "Au parc", "À la plage"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
    {
      id: "a1-read-2",
      title: "L'annonce",
      text: "À vendre : joli appartement à Lyon, deux chambres, grande cuisine, salon clair. Proche du métro et des magasins. Prix : 180 000 euros. Téléphone : 04 78 12 34 56.",
      questions: [
        {
          id: "a1-read-2-q1",
          type: "multiple_choice",
          prompt: "Que vend la personne ?",
          options: ["Une maison", "Un appartement", "Une voiture", "Un magasin"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a1-read-2-q2",
          type: "multiple_choice",
          prompt: "Combien de chambres y a-t-il ?",
          options: ["Une", "Deux", "Trois", "Quatre"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a1-read-2-q3",
          type: "multiple_choice",
          prompt: "Comment est l'appartement ?",
          options: ["Loin du centre", "Proche du métro", "Froid", "Petit"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  writingPrompts: [
    {
      id: "a1-write-1",
      title: "Présente-toi",
      task: "Écrivez un message de 30 à 50 mots pour vous présenter : votre nom, votre âge, votre ville, votre profession et votre famille.",
      minWords: 30,
    },
    {
      id: "a1-write-2",
      title: "Une carte postale",
      task: "Vous êtes en vacances. Écrivez une carte postale à un ami (30 à 50 mots) : où vous êtes, le temps, ce que vous faites, un projet pour demain.",
      minWords: 30,
    },
  ],

  speakingPrompts: [
    {
      id: "a1-speaking-1",
      title: "Votre routine",
      scenario: "Décrivez votre journée type. Parlez de l'heure à laquelle vous vous levez, ce que vous mangez, et ce que vous faites le soir.",
      hint: "Utilisez : Je me lève à…, Je mange…, Le soir, je…",
    },
    {
      id: "a1-speaking-2",
      title: "Au restaurant",
      scenario: "Faites semblant de commander au restaurant. Dites bonjour, demandez le menu, commandez un plat et une boisson, remerciez et payez.",
      hint: "Utilisez : Bonjour, Je voudrais…, Merci, Combien ça coûte ?",
    },
  ],

  stories: [
    {
      id: "a1-story-1",
      title: "Le premier jour",
      level: "A1",
      dialogue: [
        { speaker: "Lucas", text: "Bonjour ! Je m'appelle Lucas, et toi ?" },
        { speaker: "Léa", text: "Salut Lucas, moi c'est Léa. Tu es nouveau ici ?" },
        { speaker: "Lucas", text: "Oui, j'arrive de la Belgique. Je suis étudiant." },
        { speaker: "Léa", text: "Génial ! Tu étudies quoi ?" },
        { speaker: "Lucas", text: "J'étudie le droit. Et toi, tu travailles ?" },
        { speaker: "Léa", text: "Oui, je suis infirmière à l'hôpital." },
        { speaker: "Lucas", text: "Tu veux boire un café ? Il y a un bon café près de l'école." },
        { speaker: "Léa", text: "Avec plaisir ! Aujourd'hui, il fait beau, on s'installe en terrasse." },
      ],
      questions: [
        {
          id: "a1-story-1-q1",
          type: "multiple_choice",
          prompt: "D'où vient Lucas ?",
          options: ["De France", "De Belgique", "Du Canada", "De Suisse"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a1-story-1-q2",
          type: "multiple_choice",
          prompt: "Quel est le métier de Léa ?",
          options: ["Professeur", "Étudiante", "Infirmière", "Secrétaire"],
          answer: 2,
          skill: "reading",
        },
        {
          id: "a1-story-1-q3",
          type: "multiple_choice",
          prompt: "Où va le café ?",
          options: ["Au parc", "Près de l'école", "À la maison", "À l'hôpital"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  scenarios: [
    {
      id: "a1-scenario-hotel",
      title: "À l'hôtel",
      setting: "Vous arrivez dans un hôtel à Paris. Le réceptionniste vous accueille.",
      dialogue: [
        { speaker: "Réceptionniste", text: "Bonjour, monsieur. Vous avez une réservation ?" },
        { speaker: "Client", text: "Bonjour, oui. Je m'appelle Paul Martin." },
        { speaker: "Réceptionniste", text: "Oui, une chambre pour deux nuits. Voici votre clé. C'est la chambre 204." },
        { speaker: "Client", text: "Merci. À quelle heure est le petit-déjeuner ?" },
        { speaker: "Réceptionniste", text: "Le petit-déjeuner est servi de sept à dix heures." },
        { speaker: "Client", text: "Parfait, merci beaucoup !" },
      ],
    },
  ],

  culturalNotes: [
    {
      title: "Tu ou Vous ?",
      body: "In France, use « vous » with strangers, elders, and in professional settings. Use « tu » with friends, family, and children. Switching to « tu » is often an invitation to friendship.",
    },
    {
      title: "La bise",
      body: "In France, friends greet each other with the « bise » (kisses on both cheeks). The number varies by region: two in Paris, four in parts of Provence. Men usually shake hands.",
    },
    {
      title: "Le Québec",
      body: "Québec French uses « tu » almost universally, even with strangers. « Bonjour » is also the official greeting in shops — by law in Québec, store staff must greet customers with « Bonjour ». Small differences: « autobus » not « bus », « courriel » for email.",
    },
  ],

  test: {
    passingScore: 150,
    maxScore: 300,
    listening: [
      {
        id: "a1-test-l1",
        type: "multiple_choice",
        prompt: "Vous entendez : « Bonjour, je voudrais une chambre pour deux nuits, s'il vous plaît. » — Quel document concerne cette phrase ?",
        audio: "Bonjour, je voudrais une chambre pour deux nuits, s'il vous plaît.",
        options: ["Un restaurant", "Un hôtel", "Un magasin", "Une école"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a1-test-l2",
        type: "multiple_choice",
        prompt: "Vous entendez : « Le train pour Lyon part à trois heures moins le quart. » — À quelle heure part le train ?",
        audio: "Le train pour Lyon part à trois heures moins le quart.",
        options: ["3h15", "2h45", "3h45", "2h15"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a1-test-l3",
        type: "multiple_choice",
        prompt: "Vous entendez : « Ma mère est médecin et mon père travaille dans un magasin. » — Qu'est-ce qu'est la mère ?",
        audio: "Ma mère est médecin et mon père travaille dans un magasin.",
        options: ["Secrétaire", "Professeure", "Médecin", "Vendeuse"],
        answer: 2,
        skill: "listening",
      },
      {
        id: "a1-test-l4",
        type: "multiple_choice",
        prompt: "Vous entendez : « Dépêche-toi, il est déjà huit heures et demie ! » — Quelle heure est-il ?",
        audio: "Dépêche-toi, il est déjà huit heures et demie !",
        options: ["8h30", "8h15", "9h30", "8h45"],
        answer: 0,
        skill: "listening",
      },
      {
        id: "a1-test-l5",
        type: "multiple_choice",
        prompt: "Vous entendez : « Je n'aime pas le froid, je préfère l'été. » — Que préfère la personne ?",
        audio: "Je n'aime pas le froid, je préfère l'été.",
        options: ["L'hiver", "L'été", "L'automne", "Le printemps"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a1-test-l6",
        type: "multiple_choice",
        prompt: "Vous entendez : « Le supermarché est à côté de la gare. » — Où est le supermarché ?",
        audio: "Le supermarché est à côté de la gare.",
        options: ["Devant la gare", "À côté de la gare", "Derrière la gare", "Dans la gare"],
        answer: 1,
        skill: "listening",
      },
    ],
    reading: [
      {
        id: "a1-test-r1",
        type: "multiple_choice",
        prompt: "« Vente de vêtements : robes, pantalons et jupes. Magasin Ouvert, rue de la Paix. » — Que vend ce magasin ?",
        options: ["Des meubles", "Des vêtements", "Des livres", "Des fruits"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "a1-test-r2",
        type: "multiple_choice",
        prompt: "« Je m'appelle Nina. J'habite à Nantes avec ma famille : mon père, ma mère et mon petit frère. Nous avons un chien qui s'appelle Oscar. » — Combien de personnes y a-t-il dans la famille ?",
        options: ["Trois", "Quatre", "Cinq", "Deux"],
        answer: 1,
        skill: "reading",
        explain: "Nina + son père + sa mère + son petit frère = quatre personnes.",
      },
      {
        id: "a1-test-r3",
        type: "multiple_choice",
        prompt: "« Le musée est ouvert de 10h à 18h. Entrée : 8 euros. Gratuit pour les enfants de moins de 12 ans. » — Que paye un enfant de 8 ans ?",
        options: ["8 euros", "4 euros", "Rien", "10 euros"],
        answer: 2,
        skill: "reading",
      },
      {
        id: "a1-test-r4",
        type: "multiple_choice",
        prompt: "« Tous les jours, je me lève à six heures, je prends un petit-déjeuner, puis je vais au travail en bus. Le soir, je cuisine et je regarde la télévision. » — Comment va-t-il au travail ?",
        options: ["En voiture", "En bus", "À pied", "En train"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "a1-test-r5",
        type: "multiple_choice",
        prompt: "« C'est un joli village avec une église, une petite école et deux restaurants. Les gens sont accueillants. » — Qu'est-ce qu'il y a dans ce village ?",
        options: ["Une gare", "Une église", "Un hôtel", "Un musée"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "a1-test-r6",
        type: "multiple_choice",
        prompt: "« Faire du sport est bon pour la santé. Je fais du vélo trois fois par semaine avec mon ami. » — Combien de fois par semaine fait-il du vélo ?",
        options: ["Une fois", "Deux fois", "Trois fois", "Tous les jours"],
        answer: 2,
        skill: "reading",
      },
    ],
    writing: [
      {
        id: "a1-test-w1",
        title: "Formulaire",
        prompt: "Vous remplissez un formulaire d'hôtel. Écrivez : votre nom, votre prénom, votre nationalité, votre adresse et votre numéro de téléphone.",
        minWords: 15,
      },
      {
        id: "a1-test-w2",
        title: "Message court",
        prompt: "Écrivez un message de 30 à 40 mots à un ami pour l'inviter au cinéma : jour, heure, film et lieu de rendez-vous.",
        minWords: 30,
      },
    ],
    speaking: [
      {
        id: "a1-test-s1",
        title: "Présentation",
        prompt: "Présentez-vous pendant 1 à 2 minutes : nom, âge, ville, famille, profession, hobbies.",
        hint: "Je m'appelle…, J'ai… ans, J'habite à…, J'aime…",
      },
      {
        id: "a1-test-s2",
        title: "Dialogue",
        prompt: "Vous êtes au marché et vous voulez acheter des fruits. Posez des questions sur les prix et le goût, puis achetez.",
        hint: "Combien ça coûte ? / C'est trop cher ! / Je voudrais…",
      },
    ],
    pronunciation: [
      { id: "a1-test-p1", type: "pronunciation", prompt: "Prononcez ce mot clairement :", word: "bonjour", ipa: "/bɔ̃ʒuʁ/", skill: "pronunciation" },
      { id: "a1-test-p2", type: "pronunciation", prompt: "Prononcez ce mot clairement :", word: "famille", ipa: "/famij/", skill: "pronunciation" },
      { id: "a1-test-p3", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Je ne comprends pas", ipa: "/ʒə nə kɔ̃pʁɑ̃ pa/", skill: "pronunciation" },
      { id: "a1-test-p4", type: "pronunciation", prompt: "Prononcez ce numéro :", word: "vingt-deux", ipa: "/vɛ̃ dø/", skill: "pronunciation" },
    ],
  },
};