import type { LevelContent } from "@/lib/types";

export const a2: LevelContent = {
  level: "A2",

  grammar: [
    {
      id: "a2-passe-compose",
      title: "Passé Composé (with avoir & être)",
      explanation:
        "The past compound tense. Form: subject + avoir/être (present) + past participle. With avoir: J'ai mangé. With être (movement & reflexive verbs, 17 verbs: aller, venir, arriver, partir, naître, mourir, monter, descendre, sortir, entrer, rester, tomber, retourner, passer — and all pronominal): Je suis allé(e). The participle agrees with the subject with être and with a preceding direct object with avoir.",
      examples: [
        { fr: "J'ai fini mes devoirs.", en: "I finished my homework." },
        { fr: "Elle est arrivée à 8 heures.", en: "She arrived at 8 o'clock." },
        { fr: "Nous nous sommes levés tôt.", en: "We got up early." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Passé composé",
      exercises: [
        {
          id: "a2-pc-1",
          type: "fill_in_blank",
          prompt: "Conjugate manger (passé composé, je): J'___ une pomme. (two words)",
          answer: "ai mangé",
          answerVariants: ["je ai mange"],
          skill: "grammar",
          explain: "avoir + mangé (stem manger → mangé).",
        },
        {
          id: "a2-pc-2",
          type: "multiple_choice",
          prompt: "Which verb takes être in the passé composé?",
          options: ["manger", "arriver", "aimer", "finir"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "a2-pc-3",
          type: "fill_in_blank",
          prompt: "Complete (elle, être-verb aller): Elle est ___ à la gare. (past participle)",
          answer: "allée",
          answerVariants: ["alle"],
          skill: "grammar",
          explain: "aller is an être verb; with elle, add -e.",
        },
      ],
    },
    {
      id: "a2-imperatif",
      title: "The Imperative",
      explanation:
        "Giving orders/advice. Uses tu, nous, vous forms of the present tense minus the subject. -er verbs lose the -s in the tu form: Parle ! (not parles). Add y / en placements. Negative: Ne + verb + pas.",
      examples: [
        { fr: "Parle plus lentement !", en: "Speak more slowly!" },
        { fr: "Allons au cinéma !", en: "Let's go to the movies!" },
        { fr: "Ne fermez pas la porte !", en: "Don't close the door!" },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Imperative",
      exercises: [
        {
          id: "a2-imperatif-1",
          type: "fill_in_blank",
          prompt: "Give the order (tu form of parler): ___ plus lentement !",
          answer: "Parle",
          skill: "grammar",
          explain: "-er verbs drop the -s in the tu imperative.",
        },
        {
          id: "a2-imperatif-2",
          type: "multiple_choice",
          prompt: "Choose the correct imperative: ___ (nous) au restaurant !",
          options: ["Mangeons", "Mange", "Mangez", "Manger"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
    {
      id: "a2-object-pronouns",
      title: "Object Pronouns",
      explanation:
        "me, te, le, la, lui, nous, vous, les, leur go BEFORE the verb: Je le vois (I see him/it). lui/leur = to him/her/them. With imperative affirmative they move after: Donne-le-moi.",
      examples: [
        { fr: "Je le regarde.", en: "I watch him/it." },
        { fr: "Je lui parle.", en: "I speak to him/her." },
        { fr: "Il m'appelle.", en: "He calls me." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Object pronouns",
      exercises: [
        {
          id: "a2-obj-1",
          type: "multiple_choice",
          prompt: "Replace 'Jean' by a pronoun: Je vois Jean → Je ___ vois.",
          options: ["le", "la", "lui", "les"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "a2-obj-2",
          type: "translation",
          prompt: "Translate to French: I speak to her.",
          answer: "Je lui parle",
          answerVariants: ["je lui parle"],
          skill: "grammar",
        },
      ],
    },
    {
      id: "a2-comparatives",
      title: "Comparative & Superlative",
      explanation:
        "Comparative: plus…que (more than), moins…que (less than), aussi…que (as…as). Superlative: le/la/les plus + adjective, or le plus de + noun. meilleur (better) is the irregular of bon.",
      examples: [
        { fr: "Il est plus grand que moi.", en: "He is taller than I am." },
        { fr: "C'est le meilleur restaurant.", en: "It's the best restaurant." },
        { fr: "Elle parle aussi bien que lui.", en: "She speaks as well as him." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Comparisons",
      exercises: [
        {
          id: "a2-cmp-1",
          type: "multiple_choice",
          prompt: "Complete: Paris est ___ grand ___ Lyon.",
          options: ["plus / que", "aussi / plus", "moins / aussi", "plus / de"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "a2-cmp-2",
          type: "fill_in_blank",
          prompt: "Irregular superlative of bon: C'est le ___ repas. (best)",
          answer: "meilleur",
          skill: "grammar",
        },
      ],
    },
    {
      id: "a2-futur-proche",
      title: "Futur Proche (aller + infinitive)",
      explanation:
        "Immediate future: present of aller + infinitive. Je vais manger = I'm going to eat. Very common in spoken French, including for distant future plans.",
      examples: [
        { fr: "Je vais partir demain.", en: "I'm going to leave tomorrow." },
        { fr: "Nous allons visiter Paris.", en: "We're going to visit Paris." },
        { fr: "Tu vas adorer ce film !", en: "You're going to love this film!" },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Futur proche",
      exercises: [
        {
          id: "a2-fp-1",
          type: "fill_in_blank",
          prompt: "Complete: Nous ___ manger au restaurant. (aller, nous)",
          answer: "allons",
          skill: "grammar",
        },
        {
          id: "a2-fp-2",
          type: "translation",
          prompt: "Translate to French: I'm going to visit Paris.",
          answer: "Je vais visiter Paris",
          answerVariants: ["je vais visiter paris"],
          skill: "grammar",
        },
      ],
    },
    {
      id: "a2-imparfait",
      title: "The Imparfait",
      explanation:
        "Used for background, description, habits, and long actions in the past. Form: nous form minus -ons + endings (-ais, -ais, -ait, -ions, -iez, -aient). Être is irregular: j'étais…",
      examples: [
        { fr: "Quand j'étais petit, je jouais au football.", en: "When I was little, I played football." },
        { fr: "Il faisait beau.", en: "The weather was nice." },
        { fr: "Nous habitions à Bruxelles.", en: "We lived in Brussels." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Imparfait",
      exercises: [
        {
          id: "a2-imparfait-1",
          type: "fill_in_blank",
          prompt: "Conjugate jouer (imparfait, je): Je ___ au foot quand j'étais petit.",
          answer: "jouais",
          skill: "grammar",
        },
        {
          id: "a2-imparfait-2",
          type: "multiple_choice",
          prompt: "Which tense fits: Il ___ beau quand nous sommes sortis.",
          options: ["faisait", "a fait", "fera", "fait"],
          answer: 0,
          skill: "grammar",
          explain: "Setting/description in the past → imparfait.",
        },
      ],
    },
    {
      id: "a2-reflexives",
      title: "Reflexive Verbs",
      explanation:
        "Pronominal verbs with se: se lever, se laver, s'appeler. Pronoun agrees with subject: je me, tu te, il/elle se, nous nous, vous vous, ils/elles se. In passsé composé they take être: Elle s'est levée.",
      examples: [
        { fr: "Je me lève à sept heures.", en: "I get up at seven." },
        { fr: "Elle s'est couchée tard.", en: "She went to bed late." },
        { fr: "Ils se sont rencontrés à Paris.", en: "They met in Paris." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Pronominal verbs",
      exercises: [
        {
          id: "a2-refl-1",
          type: "multiple_choice",
          prompt: "Complete: Tu ___ appelles comment ?",
          options: ["te", "se", "me", "vous"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "a2-refl-2",
          type: "fill_in_blank",
          prompt: "Passé composé of se lever (elle): Elle s'est ___ tôt.",
          answer: "levée",
          skill: "grammar",
        },
      ],
    },
    {
      id: "a2-relative-pronouns",
      title: "Relative Pronouns: qui, que, où",
      explanation:
        "qui = that/which (subject, or follows a preposition for people). que = that/which (object). où = where. C'est le film que j'aime. La dame qui parle. Le pays où je vis.",
      examples: [
        { fr: "La fille qui chante est ma sœur.", en: "The girl who sings is my sister." },
        { fr: "Le livre que je lis est intéressant.", en: "The book that I'm reading is interesting." },
        { fr: "Voici la ville où je suis né.", en: "Here is the town where I was born." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Relative pronouns",
      exercises: [
        {
          id: "a2-rel-1",
          type: "multiple_choice",
          prompt: "Complete: Le film ___ je regarde est long.",
          options: ["qui", "que", "où", "dont"],
          answer: 1,
          skill: "grammar",
          explain: "The film which I watch — direct object → que.",
        },
        {
          id: "a2-rel-2",
          type: "multiple_choice",
          prompt: "Complete: L'homme ___ parle est le directeur.",
          options: ["qui", "que", "où", "dont"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
  ],

  vocabulary: [
    {
      theme: "Travel & Transport",
      items: [
        { fr: "le voyage", en: "the trip", example: "Mon voyage était fantastique.", exampleEn: "My trip was fantastic." },
        { fr: "la gare", en: "the station", example: "J'arrive à la gare à midi.", exampleEn: "I arrive at the station at noon." },
        { fr: "l'aéroport", en: "the airport", example: "L'aéroport est loin du centre.", exampleEn: "The airport is far from the center." },
        { fr: "le billet", en: "the ticket", example: "Le billet coûte trente euros.", exampleEn: "The ticket costs thirty euros." },
        { fr: "le train", en: "the train", example: "Le train part à neuf heures.", exampleEn: "The train leaves at nine." },
        { fr: "l'avion", en: "the plane", example: "L'avion arrive à temps.", exampleEn: "The plane arrives on time." },
        { fr: "la voiture", en: "the car", example: "Il conduit sa voiture.", exampleEn: "He drives his car." },
        { fr: "le métro", en: "the subway", example: "Le métro est rapide.", exampleEn: "The subway is fast." },
      ],
    },
    {
      theme: "Shopping",
      items: [
        { fr: "le magasin", en: "the shop", example: "Ce magasin est moderne.", exampleEn: "This shop is modern." },
        { fr: "la vente", en: "the sale", example: "Il y a une grande vente aujourd'hui.", exampleEn: "There's a big sale today." },
        { fr: "le prix", en: "the price", example: "Le prix est raisonnable.", exampleEn: "The price is reasonable." },
        { fr: "payer", en: "to pay", example: "Je paie avec ma carte.", exampleEn: "I pay with my card." },
        { fr: "coûter", en: "to cost", example: "Ça coûte trop cher.", exampleEn: "That's too expensive." },
        { fr: "l'argent", en: "the money", example: "Je n'ai pas beaucoup d'argent.", exampleEn: "I don't have much money." },
        { fr: "le client", en: "the customer", example: "Le client attend.", exampleEn: "The customer is waiting." },
        { fr: "rendre", en: "to return/give back", example: "Je rends ce pantalon.", exampleEn: "I return these pants." },
      ],
    },
    {
      theme: "Health & Body",
      items: [
        { fr: "la santé", en: "the health", example: "La santé est importante.", exampleEn: "Health is important." },
        { fr: "la tête", en: "the head", example: "J'ai mal à la tête.", exampleEn: "I have a headache." },
        { fr: "le ventre", en: "the stomach", example: "J'ai mal au ventre.", exampleEn: "I have a stomachache." },
        { fr: "le docteur", en: "the doctor", example: "Je dois voir le docteur.", exampleEn: "I must see the doctor." },
        { fr: "la pharmacie", en: "the pharmacy", example: "Où est la pharmacie ?", exampleEn: "Where is the pharmacy?" },
        { fr: "le médicament", en: "the medicine", example: "Prenez ce médicament.", exampleEn: "Take this medicine." },
        { fr: "la douleur", en: "the pain", example: "J'ai une douleur au dos.", exampleEn: "I have a pain in my back." },
        { fr: "se reposer", en: "to rest", example: "Je dois me reposer.", exampleEn: "I need to rest." },
      ],
    },
    {
      theme: "City & Directions",
      items: [
        { fr: "tout droit", en: "straight ahead", example: "Allez tout droit.", exampleEn: "Go straight ahead." },
        { fr: "à gauche", en: "to the left", example: "Tournez à gauche.", exampleEn: "Turn left." },
        { fr: "à droite", en: "to the right", example: "La banque est à droite.", exampleEn: "The bank is on the right." },
        { fr: "tout près", en: "very near", example: "La boulangerie est tout près.", exampleEn: "The bakery is very near." },
        { fr: "loin", en: "far", example: "Le château est loin d'ici.", exampleEn: "The castle is far from here." },
        { fr: "le coin", en: "the corner", example: "Au coin de la rue.", exampleEn: "At the street corner." },
        { fr: "le centre-ville", en: "the city center", example: "Nous allons au centre-ville.", exampleEn: "We're going downtown." },
        { fr: "se perdre", en: "to get lost", example: "Je me suis perdu !", exampleEn: "I got lost!" },
      ],
    },
    {
      theme: "Restaurant",
      items: [
        { fr: "le serveur / la serveuse", en: "the waiter / waitress", example: "Le serveur apporte le menu.", exampleEn: "The waiter brings the menu." },
        { fr: "le menu", en: "the menu", example: "Le menu du jour, s'il vous plaît.", exampleEn: "Today's menu, please." },
        { fr: "la note", en: "the bill", example: "L'addition, s'il vous plaît !", exampleEn: "The bill, please!" },
        { fr: "l'entrée", en: "the starter", example: "Comme entrée, une salade.", exampleEn: "As a starter, a salad." },
        { fr: "le plat principal", en: "the main course", example: "Le plat principal est le poulet.", exampleEn: "The main course is chicken." },
        { fr: "le dessert", en: "the dessert", example: "Je veux un dessert au chocolat.", exampleEn: "I want a chocolate dessert." },
        { fr: "délicieux", en: "delicious", example: "Ce plat est délicieux !", exampleEn: "This dish is delicious!" },
        { fr: "réserver", en: "to reserve", example: "J'ai réservé une table pour deux.", exampleEn: "I reserved a table for two." },
      ],
    },
    {
      theme: "Emotions",
      items: [
        { fr: "content(e)", en: "happy", example: "Je suis content de te voir.", exampleEn: "I'm happy to see you." },
        { fr: "triste", en: "sad", example: "Il est triste aujourd'hui.", exampleEn: "He is sad today." },
        { fr: "énervé(e)", en: "angry/annoyed", example: "Elle est énervée par le bruit.", exampleEn: "She is annoyed by the noise." },
        { fr: "fatigué(e)", en: "tired", example: "Je suis fatigué après le travail.", exampleEn: "I'm tired after work." },
        { fr: "stressé(e)", en: "stressed", example: "Il est stressé avant l'examen.", exampleEn: "He's stressed before the exam." },
        { fr: "avoir peur", en: "to be scared", example: "J'ai peur des chiens.", exampleEn: "I'm scared of dogs." },
        { fr: "avoir envie de", en: "to feel like", example: "J'ai envie de dormir.", exampleEn: "I feel like sleeping." },
        { fr: "ça m'est égal", en: "it's all the same to me", example: "Ça m'est égal, choisis toi.", exampleEn: "I don't mind, you choose." },
      ],
    },
    {
      theme: "Accommodation",
      items: [
        { fr: "l'hôtel", en: "the hotel", example: "L'hôtel est confortable.", exampleEn: "The hotel is comfortable." },
        { fr: "la chambre", en: "the room", example: "Ma chambre a une belle vue.", exampleEn: "My room has a nice view." },
        { fr: "la réservation", en: "the reservation", example: "J'ai fait une réservation.", exampleEn: "I made a reservation." },
        { fr: "la clé", en: "the key", example: "Voici la clé de votre chambre.", exampleEn: "Here is the key to your room." },
        { fr: "l'étage", en: "the floor", example: "Votre chambre est au deuxième étage.", exampleEn: "Your room is on the second floor." },
        { fr: "petit-déjeuner compris", en: "breakfast included", example: "Le petit-déjeuner est compris.", exampleEn: "Breakfast is included." },
        { fr: "l'ascenseur", en: "the elevator", example: "L'ascenseur est en panne.", exampleEn: "The elevator is out of order." },
        { fr: "le linge", en: "the linen", example: "Le linge propre est dans l'armoire.", exampleEn: "Clean linen is in the wardrobe." },
      ],
    },
    {
      theme: "Hobbies & Leisure",
      items: [
        { fr: "le passe-temps", en: "the hobby", example: "Son passe-temps est la photo.", exampleEn: "His hobby is photography." },
        { fr: "le sport", en: "the sport", example: "Le sport, c'est important.", exampleEn: "Sport is important." },
        { fr: "le cinéma", en: "the cinema", example: "Allons au cinéma ce soir.", exampleEn: "Let's go to the movies tonight." },
        { fr: "la lecture", en: "reading", example: "La lecture est relaxante.", exampleEn: "Reading is relaxing." },
        { fr: "la musique", en: "music", example: "J'écoute de la musique.", exampleEn: "I listen to music." },
        { fr: "le jardin", en: "the garden", example: "Il travaille dans son jardin.", exampleEn: "He works in his garden." },
        { fr: "la plage", en: "the beach", example: "La plage est remplie.", exampleEn: "The beach is crowded." },
        { fr: "se balader", en: "to stroll", example: "Je me balade dans les rues.", exampleEn: "I stroll through the streets." },
      ],
    },
  ],

  phrases: [
    { fr: "Je peux vous aider ?", en: "Can I help you?", example: "Bonjour, je peux vous aider ?", exampleEn: "Hello, can I help you?" },
    { fr: "Je cherche…", en: "I'm looking for…", example: "Je cherche la poste.", exampleEn: "I'm looking for the post office." },
    { fr: "Comment aller à… ?", en: "How do I get to…?", example: "Comment aller à la gare ?", exampleEn: "How do I get to the station?" },
    { fr: "Je suis perdu(e)", en: "I'm lost", example: "Pardon, je suis perdu.", exampleEn: "Sorry, I'm lost." },
    { fr: "À quelle heure ?", en: "At what time?", example: "À quelle heure part le bus ?", exampleEn: "What time does the bus leave?" },
    { fr: "Pas encore", en: "Not yet", example: "Tu as fini ? Non, pas encore.", exampleEn: "Are you done? No, not yet." },
    { fr: "Ça y est !", en: "There it is / It's done!", example: "Ça y est, j'ai mon billet !", exampleEn: "It's done, I have my ticket!" },
    { fr: "Quelquefois", en: "sometimes", example: "Quelquefois, je travaille le dimanche.", exampleEn: "Sometimes I work on Sunday." },
    { fr: "Je me suis trompé(e)", en: "I made a mistake", example: "Pardon, je me suis trompé de bus.", exampleEn: "Sorry, I took the wrong bus." },
    { fr: "Bon courage !", en: "Good luck / Hang in there!", example: "Bon courage pour l'examen !", exampleEn: "Good luck on the exam!" },
  ],

  pronunciation: {
    phonemes: [
      { symbol: "e / ɛ", name: "É vs È", examples: ["école (e)", "père (ɛ)"], note: "é is closed (mouth less open), è is open." },
      { symbol: "wa", name: "OI", examples: ["moi", "toi", "voir"], note: "Always pronounced 'wa': poisson /pwasɔ̃/." },
      { symbol: "œ̃", name: "Nasal un", examples: ["un", "brun", "lundi"], note: "Rare in Paris speech (often merges with ɛ̃), keep it in careful speech." },
      { symbol: "j", name: "Y/ill sound", examples: ["fille", "travail", "payer"], note: "Like English 'y' in 'yes'; -ille = /ij/." },
      { symbol: "ɡ", name: "Hard g", examples: ["gâteau", "gomme", "guerre"], note: "gu + vowel keeps the hard /ɡ/ sound." },
      { symbol: "z", name: "Voiced s", examples: ["maison", "rose", "zéro"], note: "An s between two vowels says /z/." },
    ],
    minimalPairs: [
      { a: "école", b: "écolier" },
      { a: "père", b: "péris" },
      { a: "moi", b: "moua" },
      { a: "fille", b: "fi" },
      { a: "brun", b: "brin" },
      { a: "un", b: "in" },
      { a: "maison", b: "masson" },
      { a: "poisson", b: "poison" },
      { a: "gâteau", b: "cadeau" },
      { a: "il", b: "ils" },
    ],
    rules: [
      "s between two vowels is voiced (/z/): maison, raison, visage.",
      "-oi- is always pronounced /wa/.",
      "-ille / -eille at the end is /ij/ (fille, vieille).",
      "Final consonants are generally silent: petit, grand, trois (but c, r, f, l are pronounced).",
    ],
  },

  listening: [
    {
      id: "a2-listen-1",
      title: "Direction à la gare",
      text: "Excusez-moi, où est la gare ? — Allez tout droit, puis tournez à droite après la banque. La gare est en face du supermarché. — C'est loin ? — Non, dix minutes à pied environ.",
      questions: [
        {
          id: "a2-listen-1-q1",
          type: "multiple_choice",
          prompt: "Qu'est-ce que la personne cherche ?",
          options: ["La banque", "La gare", "Le supermarché", "L'hôtel"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "a2-listen-1-q2",
          type: "multiple_choice",
          prompt: "Où est la gare ?",
          options: ["À gauche de la banque", "En face du supermarché", "Derrière la poste", "Suivant la banque"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "a2-listen-1-q3",
          type: "multiple_choice",
          prompt: "Combien de temps faut-il à pied ?",
          options: ["Cinq minutes", "Dix minutes", "Quinze minutes", "Vingt minutes"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
    {
      id: "a2-listen-2",
      title: "Chez le médecin",
      text: "Bonjour docteur, je suis malade. — Depuis quand avez-vous mal ? — Depuis hier soir. J'ai mal à la gorge et je tousse. — Prenez ce médicament deux fois par jour et reposez-vous. Revenez dans trois jours si ça ne va pas mieux.",
      questions: [
        {
          id: "a2-listen-2-q1",
          type: "multiple_choice",
          prompt: "Quel est le problème du patient ?",
          options: ["Mal à la tête", "Mal à la gorge", "Mal au dos", "Mal au ventre"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "a2-listen-2-q2",
          type: "multiple_choice",
          prompt: "À quelle fréquence doit-il prendre le médicament ?",
          options: ["Une fois par jour", "Deux fois par jour", "Trois fois par jour", "Une fois par semaine"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
  ],

  reading: [
    {
      id: "a2-read-1",
      title: "Un courriel de Luc",
      text: "Chère Sophie, Nous sommes enfin arrivés à Montréal ! Le voyage était long mais agréable. Nous avons loué un petit appartement dans le Vieux-Port. Il fait un peu froid mais on s'habitue. Demain, nous allons visiter le marché Jean-Talon et goûter la poutine. On se voit le mois prochain ? Bisous, Luc",
      questions: [
        {
          id: "a2-read-1-q1",
          type: "multiple_choice",
          prompt: "Où sont Luc et sa famille ?",
          options: ["À Québec", "À Montréal", "À Paris", "À Bruxelles"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a2-read-1-q2",
          type: "multiple_choice",
          prompt: "Que vont-ils faire demain ?",
          options: ["Visiter un musée", "Aller au marché", "Louer un appartement", "Prendre l'avion"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a2-read-1-q3",
          type: "multiple_choice",
          prompt: "Quels temps font-ils ?",
          options: ["Il fait chaud", "Il fait un peu froid", "Il pleut", "Il neige"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
    {
      id: "a2-read-2",
      title: "Le petit restaurant",
      text: "Le « Bistro du Port » est un petit restaurant familial. Le serveur est très gentil et les plats sont faits maison. Le menu du jour coûte 12 euros : soupe ou salade, plat principal, dessert. Le restaurant est ouvert du mardi au dimanche, de 12h à 14h et de 19h à 22h. Le lundi, il est fermé. Il est conseillé de réserver le week-end.",
      questions: [
        {
          id: "a2-read-2-q1",
          type: "multiple_choice",
          prompt: "Combien coûte le menu du jour ?",
          options: ["10 euros", "12 euros", "15 euros", "20 euros"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a2-read-2-q2",
          type: "multiple_choice",
          prompt: "Quel jour le restaurant est-il fermé ?",
          options: ["Mardi", "Dimanche", "Lundi", "Samedi"],
          answer: 2,
          skill: "reading",
        },
        {
          id: "a2-read-2-q3",
          type: "multiple_choice",
          prompt: "Pourquoi faut-il réserver le week-end ?",
          options: ["C'est conseillé", "C'est obligatoire", "Le restaurant est fermé", "Le service est lent"],
          answer: 0,
          skill: "reading",
        },
      ],
    },
  ],

  writingPrompts: [
    {
      id: "a2-write-1",
      title: "Vos dernières vacances",
      task: "Écrivez un message de 60 à 80 mots sur vos dernières vacances : où vous êtes allé(e), avec qui, le temps, et ce que vous avez fait.",
      minWords: 60,
    },
    {
      id: "a2-write-2",
      title: "Décrire une photo",
      task: "Écrivez 50 à 70 mots pour décrire une photo de votre famille : qui est présent, où ils sont, ce qu'ils portent et ce qu'ils font.",
      minWords: 50,
    },
  ],

  speakingPrompts: [
    {
      id: "a2-speaking-1",
      title: "Raconter un souvenir",
      scenario: "Racontez un souvenir de voyage ou d'enfance : où c'était, quand, qui était là, ce qui s'est passé.",
      hint: "Utilisez le passé composé et l'imparfait : C'était…, Nous avons…, J'ai…",
    },
    {
      id: "a2-speaking-2",
      title: "Au magasin",
      scenario: "Vous êtes dans un magasin de vêtements. Demandez la taille, essayez un vêtement, posez des questions sur le prix et le remboursement, puis achetez.",
      hint: "Pouvez-vous m'aider ? / Quelle taille ? / Je peux l'essayer ?",
    },
  ],

  stories: [
    {
      id: "a2-story-1",
      title: "La valise perdue",
      level: "A2",
      dialogue: [
        { speaker: "Passager", text: "Excusez-moi, ma valise n'est pas arrivée." },
        { speaker: "Agent", text: "De quel vol venez-vous ?" },
        { speaker: "Passager", text: "Le vol AF 320, en provenance de Montréal." },
        { speaker: "Agent", text: "Un moment, s'il vous plaît… Votre valise est encore à Montréal." },
        { speaker: "Passager", text: "Qu'est-ce que je fais ?" },
        { speaker: "Agent", text: "Ne vous inquiétez pas. Nous allons vous l'apporter demain matin à votre hôtel." },
        { speaker: "Passager", text: "Et mes vêtements ? Je n'ai rien pour me changer !" },
        { speaker: "Agent", text: "Nous vous donnons une trousse avec une brosse à dents et un tee-shirt." },
        { speaker: "Passager", text: "D'accord, merci. À quelle heure demain ?" },
        { speaker: "Agent", text: "Vers dix heures du matin. Je suis désolé pour la gêne." },
      ],
      questions: [
        {
          id: "a2-story-1-q1",
          type: "multiple_choice",
          prompt: "D'où vient le vol ?",
          options: ["De Québec", "De Montréal", "De Paris", "De Lyon"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a2-story-1-q2",
          type: "multiple_choice",
          prompt: "Quand la valise va-t-elle arriver ?",
          options: ["Ce soir", "Demain matin", "Dans trois jours", "La semaine prochaine"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "a2-story-1-q3",
          type: "multiple_choice",
          prompt: "Que donne l'agent au passager ?",
          options: ["Une carte", "Une trousse", "Un livre", "Un billet"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  scenarios: [
    {
      id: "a2-scenario-resto",
      title: "Commander au restaurant",
      setting: "Vous êtes au restaurant avec un ami. Le serveur prend la commande.",
      dialogue: [
        { speaker: "Serveur", text: "Bonsoir, voici le menu. Qu'est-ce que je vous sers à boire ?" },
        { speaker: "Client", text: "Une carafe d'eau, s'il vous plaît." },
        { speaker: "Serveur", text: "Très bien. Et comme entrée ?" },
        { speaker: "Client", text: "Je vais prendre la salade de chèvre, s'il vous plaît." },
        { speaker: "Serveur", text: "Excellent choix. Et comme plat principal ?" },
        { speaker: "Client", text: "Le poisson du jour, avec des légumes." },
        { speaker: "Serveur", text: "Parfait. Le poisson est délicieux aujourd'hui." },
        { speaker: "Client", text: "L'addition, s'il vous plaît, et je peux payer par carte ?" },
        { speaker: "Serveur", text: "Bien sûr, je vous apporte le terminal." },
      ],
    },
  ],

  culturalNotes: [
    {
      title: "La boulangerie",
      body: "Bakeries are a daily stop in France. The « baguette » is bought fresh daily. A polite « Bonjour Madame / Monsieur » is essential before ordering. In the evenings, fresh bread is often sold out.",
    },
    {
      title: "La poutine au Québec",
      body: "Québec's famous dish: fries topped with cheese curds and gravy. A symbol of Québécois identity, it is served in cafés and fast food joints across the province.",
    },
    {
      title: "Les horaires de repas",
      body: "In France, lunch is typically 12h-14h and dinner 19h-21h. Restaurants close between lunch and dinner — tourists often arrive 'too late' for lunch at 14h30 and find the kitchen closed.",
    },
  ],

  test: {
    passingScore: 200,
    maxScore: 350,
    listening: [
      {
        id: "a2-test-l1",
        type: "multiple_choice",
        prompt: "Vous entendez : « Pour aller à la poste, prenez la deuxième rue à gauche, puis la poste est à droite. » — Quelle direction prenez-vous ?",
        audio: "Pour aller à la poste, prenez la deuxième rue à gauche, puis la poste est à droite.",
        options: ["À droite puis à gauche", "À gauche puis à droite", "Tout droit", "En arrière"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a2-test-l2",
        type: "multiple_choice",
        prompt: "Vous entendez : « Le film commence à vingt heures trente. Nous avons rendez-vous à vingt heures devant le cinéma. » — À quelle heure commence le film ?",
        audio: "Le film commence à vingt heures trente. Nous avons rendez-vous à vingt heures devant le cinéma.",
        options: ["20h", "20h30", "21h", "21h30"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a2-test-l3",
        type: "multiple_choice",
        prompt: "Vous entendez : « J'ai perdu mon portable dans le train. Je suis très énervé ! » — Que ressent la personne ?",
        audio: "J'ai perdu mon portable dans le train. Je suis très énervé !",
        options: ["Elle est contente", "Elle est énervée", "Elle est fatiguée", "Elle a peur"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a2-test-l4",
        type: "multiple_choice",
        prompt: "Vous entendez : « Malheureusement, votre chambre n'est pas encore prête. Revenez dans trente minutes. » — Quand la chambre sera-t-elle prête ?",
        audio: "Malheureusement, votre chambre n'est pas encore prête. Revenez dans trente minutes.",
        options: ["Tout de suite", "Dans 30 minutes", "Demain", "Dans une heure et demie"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a2-test-l5",
        type: "multiple_choice",
        prompt: "Vous entendez : « Je suis arrivé hier. J'ai déjà visité le musée et le jardin. Demain, je vais prendre le bateau. » — Que va-t-il faire demain ?",
        audio: "Je suis arrivé hier. J'ai déjà visité le musée et le jardin. Demain, je vais prendre le bateau.",
        options: ["Visiter le musée", "Prendre le bateau", "Visiter le jardin", "Partir"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "a2-test-l6",
        type: "multiple_choice",
        prompt: "Vous entendez : « Il n'y a plus de pâtes. Nous allons manger du riz à la place. » — Que vont-ils manger ?",
        audio: "Il n'y a plus de pâtes. Nous allons manger du riz à la place.",
        options: ["Des pâtes", "Du riz", "De la soupe", "Du pain"],
        answer: 1,
        skill: "listening",
      },
    ],
    reading: [
      {
        id: "a2-test-r1",
        type: "multiple_choice",
        prompt: "« L'appartement de deux chambres se trouve au troisième étage. Il n'y a pas d'ascenseur. » — Qu'est-ce qu'il n'y a pas ?",
        options: ["D'étage", "De chambre", "D'ascenseur", "De fenêtre"],
        answer: 2,
        skill: "reading",
      },
      {
        id: "a2-test-r2",
        type: "multiple_choice",
        prompt: "« Apres le travail, je fais toujours du sport. Je fais de la natation le lundi et le mercredi, et du tennis le samedi. » — Combien de fois par semaine fait-il du sport ?",
        options: ["Une fois", "Deux fois", "Trois fois", "Quatre fois"],
        answer: 2,
        skill: "reading",
      },
      {
        id: "a2-test-r3",
        type: "multiple_choice",
        prompt: "« Cette randonnée est difficile mais magnifique. Le village au sommet offre une vue incroyable sur la vallée. » — Pourquoi faire cette randonnée ?",
        options: ["Elle est facile", "La vue est magnifique", "Le village est vide", "Elle est courte"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "a2-test-r4",
        type: "multiple_choice",
        prompt: "« Nous sommes allés au marché ce matin. Nous avons acheté des fruits, du fromage et deux baguettes. Après, nous avons pris un café en terrasse. » — Qu'ont-ils fait après le marché ?",
        options: ["Ils ont cuisiné", "Ils ont pris un café", "Ils sont rentrés", "Ils ont dîné"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "a2-test-r5",
        type: "multiple_choice",
        prompt: "« Si vous avez mal à la tête, prenez un comprimé d'aspirine et buvez beaucoup d'eau. Ne conduisez pas après avoir pris le médicament. » — Pourquoi ne pas conduire ?",
        options: ["Parce qu'il pleut", "À cause du médicament", "Parce qu'il est tard", "À cause de la neige"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "a2-test-r6",
        type: "multiple_choice",
        prompt: "« Le train arrive en gare avec vingt minutes de retard à cause d'un problème sur la voie. » — Quel est le problème ?",
        options: ["La grève", "Un retard", "Un accident", "Une panne de bus"],
        answer: 1,
        skill: "reading",
      },
    ],
    writing: [
      {
        id: "a2-test-w1",
        title: "Message personnel",
        prompt: "Votre ami français vous demande comment se passe votre voyage. Répondez-lui par e-mail (60 à 80 mots) : où vous êtes, ce que vous avez déjà fait, vos impressions.",
        minWords: 60,
      },
      {
        id: "a2-test-w2",
        title: "Description",
        prompt: "Décrivez votre quartier en 50 à 70 mots : les commerces, les transports, les habitants, et ce que vous aimez.",
        minWords: 50,
      },
    ],
    speaking: [
      {
        id: "a2-test-s1",
        title: "Votre quotidien",
        prompt: "Parlez de votre semaine type pendant 2 minutes : travail/études, sports, loisirs, et activité du week-end.",
        hint: "Pendant la semaine, je… / Le week-end, je… / J'aime…",
      },
      {
        id: "a2-test-s2",
        title: "Transaction",
        prompt: "Vous rapportez un vêtement au magasin. Expliquez le problème et demandez un échange ou un remboursement.",
        hint: "Je voudrais rendre… / Je peux avoir un remboursement ?",
      },
    ],
    pronunciation: [
      { id: "a2-test-p1", type: "pronunciation", prompt: "Prononcez ce mot :", word: "restaurant", ipa: "/ʁɛstɔʁɑ̃/", skill: "pronunciation" },
      { id: "a2-test-p2", type: "pronunciation", prompt: "Prononcez ce mot :", word: "s'il vous plaît", ipa: "/sil vu plɛ/", skill: "pronunciation" },
      { id: "a2-test-p3", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Je me suis perdus", ipa: "/ʒə mə sɥi pɛʁdy/", skill: "pronunciation" },
      { id: "a2-test-p4", type: "pronunciation", prompt: "Prononcez ce numéro :", word: "quatre-vingt", ipa: "/katʁ vɛ̃/", skill: "pronunciation" },
    ],
  },
};