import type { LevelContent } from "@/lib/types";

export const b1: LevelContent = {
  level: "B1",

  grammar: [
    {
      id: "b1-conditionnel",
      title: "Le Conditionnel Présent",
      explanation:
        "Used for polite requests, wishes, hypotheses (si + imparfait → conditionnel), and reported news. Form: future stem + imparfait endings (ais, ais, ait, ions, iez, aient). Je voudrais, il faudrait, on pourrait.",
      examples: [
        { fr: "Je voudrais un café, s'il vous plaît.", en: "I would like a coffee, please." },
        { fr: "Si j'avais le temps, je voyagerais.", en: "If I had time, I would travel." },
        { fr: "Il serait intéressant de voir ce film.", en: "It would be interesting to see this movie." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Conditional",
      exercises: [
        {
          id: "b1-cond-1",
          type: "fill_in_blank",
          prompt: "Conjugate aimer (conditionnel, je): J'___ un café. (I would like a coffee)",
          answer: "aimerais",
          answerVariants: ["aimerait"],
          skill: "grammar",
        },
        {
          id: "b1-cond-2",
          type: "multiple_choice",
          prompt: "Choose the polite request: ___ vous m'aider ?",
          options: ["Pouvez", "Pourriez", "Pourrais", "Pouvois"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b1-cond-3",
          type: "fill_in_blank",
          prompt: "Complete with the conditional: Si j'étais riche, je ___ (acheter) un château.",
          answer: "achèterais",
          answerVariants: ["acheterais", "achèterai"],
          skill: "grammar",
          explain: "si + imparfait → conditionnel présent.",
        },
      ],
    },
    {
      id: "b1-plus-que-parfait",
      title: "Le Plus-que-parfait",
      explanation:
        "Pluperfect: describes an action that happened BEFORE another past action. Form: imparfait of avoir/être + past participle. Elle avait mangé avant de sortir. In English: had + past participle.",
      examples: [
        { fr: "Quand je suis arrivé, il était déjà parti.", en: "When I arrived, he had already left." },
        { fr: "Elle avait oublié ses clés.", en: "She had forgotten her keys." },
        { fr: "Nous avions déjà vu ce film.", en: "We had already seen this film." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Pluperfect",
      exercises: [
        {
          id: "b1-pqf-1",
          type: "fill_in_blank",
          prompt: "Complete: Quand je suis arrivé, il ___ parti. (être, il)",
          answer: "était",
          skill: "grammar",
        },
        {
          id: "b1-pqf-2",
          type: "multiple_choice",
          prompt: "Which tense expresses an action before another past action?",
          options: ["Le présent", "Le plus-que-parfait", "Le futur simple", "L'imparfait"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "b1-futur-simple",
      title: "Le Futur Simple",
      explanation:
        "Simple future for predictions and plans. Form: infinitive + -ai, -as, -a, -ons, -ez, -ont. Irregular stems: être→ser-, avoir→aur-, aller→ir-, faire→fer-, voir→ver-, pouvoir→pourr-, vouloir→voudr-, savoir→saur-.",
      examples: [
        { fr: "Demain, il fera beau.", en: "Tomorrow the weather will be nice." },
        { fr: "Nous irons en France l'année prochaine.", en: "We will go to France next year." },
        { fr: "Je ne pourrai pas venir.", en: "I won't be able to come." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Future",
      exercises: [
        {
          id: "b1-fut-1",
          type: "fill_in_blank",
          prompt: "Conjugate être (futur, il): Il ___ tard demain.",
          answer: "sera",
          skill: "grammar",
        },
        {
          id: "b1-fut-2",
          type: "multiple_choice",
          prompt: "Irregular future of aller: Vous ___ au concert ?",
          options: ["aller", "irez", "allez", "irai"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "b1-subjonctif",
      title: "Le Subjonctif (introduction)",
      explanation:
        "Used after expressions of emotion, doubt, necessity, wish: il faut que, pour que, bien que, je veux que, il est important que. Ends in -e, -es, -e, -ions, -iez, -ent (from ils stem). Irregulars: être→sois/soit, avoir→aie/ait, aller→aille, faire→fasse, savoir→sache.",
      examples: [
        { fr: "Il faut que tu viennes.", en: "You must come (it's necessary that you come)." },
        { fr: "Je veux qu'il soit content.", en: "I want him to be happy." },
        { fr: "Bien qu'il fasse froid, il sort.", en: "Although it's cold, he goes out." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Subjunctive",
      exercises: [
        {
          id: "b1-subj-1",
          type: "multiple_choice",
          prompt: "Complete: Il faut que nous ___ (faire) nos devoirs.",
          options: ["faisons", "fasse", "fassions", "font"],
          answer: 2,
          skill: "grammar",
        },
        {
          id: "b1-subj-2",
          type: "multiple_choice",
          prompt: "Choose the sentence with the subjunctive REQUIRED:",
          options: ["Je pense qu'il est parti.", "Je veux qu'il parte.", "Je sais qu'il part.", "Il dit qu'il partira."],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b1-subj-3",
          type: "fill_in_blank",
          prompt: "Conjugate être (subjonctif, tu): Il est important que tu ___ là.",
          answer: "sois",
          skill: "grammar",
        },
      ],
    },
    {
      id: "b1-pronoms-relatifs",
      title: "Pronoms Relatifs Composés: auquel, dont",
      explanation:
        "dont = whose / of which: Le livre dont je parle (the book I'm talking about). duquel/de laquelle/desquels follow prepositions: la chaise sur laquelle il s'assoit. auquel = à + lequel: Le projet auquel je travaille.",
      examples: [
        { fr: "Le film dont tu m'as parlé était excellent.", en: "The film you told me about was excellent." },
        { fr: "La ville dans laquelle j'habite est petite.", en: "The city in which I live is small." },
        { fr: "Le projet auquel nous participons est ambitieux.", en: "The project we're taking part in is ambitious." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Relative pronouns",
      exercises: [
        {
          id: "b1-pron-1",
          type: "multiple_choice",
          prompt: "Complete: La maison ___ je rêve est très chère.",
          options: ["que", "dont", "qui", "où"],
          answer: 1,
          skill: "grammar",
          explain: "rêver de → 'the house I dream of' uses dont.",
        },
        {
          id: "b1-pron-2",
          type: "multiple_choice",
          prompt: "Complete: Le livre ___ tu penses est sur la table.",
          options: ["auquel", "à quel", "que", "dont"],
          answer: 0,
          skill: "grammar",
          explain: "penser à → auquel.",
        },
      ],
    },
    {
      id: "b1-voice-moyenne",
      title: "Le Passif",
      explanation:
        "Passive voice: être + past participle, agent introduced by par (action) or de (feeling). La maison a été vendue par le propriétaire. Less common in French than in English; often replaced by on.",
      examples: [
        { fr: "La maison a été vendue.", en: "The house has been sold." },
        { fr: "Le gâteau est fait par mon père.", en: "The cake is made by my father." },
        { fr: "Il est aimé de tous.", en: "He is loved by everyone." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Passive voice",
      exercises: [
        {
          id: "b1-passif-1",
          type: "multiple_choice",
          prompt: "Complete: Le château ___ construit en 1800.",
          options: ["a", "a été", "est" , "être"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b1-passif-2",
          type: "fill_in_blank",
          prompt: "Rewrite passively: On a vendu le vélo. → Le vélo a été ___.",
          answer: "vendu",
          skill: "grammar",
        },
      ],
    },
    {
      id: "b1-discours-indirect",
      title: "Le Discours Indirect",
      explanation:
        "Reported speech: Il dit « Je suis fatigué » → Il dit qu'il est fatigué. Tense shifts: present→imparfait, futur→conditionnel, passé composé→plus-que-parfait in the past (Il a dit qu'il était fatigué). Questions: il demande si…, il demande où/qui/ce que…",
      examples: [
        { fr: "Elle dit qu'elle viendra.", en: "She says she will come." },
        { fr: "Il a dit qu'il avait faim.", en: "He said he was hungry." },
        { fr: "Demande-lui ce qu'il veut.", en: "Ask him what he wants." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Reported speech",
      exercises: [
        {
          id: "b1-indirect-1",
          type: "multiple_choice",
          prompt: "Report: Il dit « Je suis malade » → Il dit que ___.",
          options: ["je suis malade", "il est malade", "il était malade", "tu es malade"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b1-indirect-2",
          type: "multiple_choice",
          prompt: "Report: « Où habites-tu ? » demande-t-il. → Il demande ___.",
          options: ["où j'habite", "où habites-tu", "que j'habite", "si j'habite"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
    {
      id: "b1-gerondif",
      title: "Le Gérondif",
      explanation:
        "en + present participle = 'while doing something' or a manner. En mangeant, en travaillant. Present participle stem + -ant. En lisant ce livre, j'ai appris beaucoup. Contraction of while/when + verb.",
      examples: [
        { fr: "Il écoute de la musique en travaillant.", en: "He listens to music while working." },
        { fr: "En marchant, j'ai rencontré Paul.", en: "Walking, I met Paul." },
        { fr: "Elle est partie en souriant.", en: "She left smiling." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Gérondif",
      exercises: [
        {
          id: "b1-gerondif-1",
          type: "multiple_choice",
          prompt: "Complete: Je me suis blessé en ___ (jouer).",
          options: ["jouant", "jouer", "joué", "jouais"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "b1-gerondif-2",
          type: "fill_in_blank",
          prompt: "Complete: On apprend beaucoup en ___ (voyager).",
          answer: "voyageant",
          skill: "grammar",
          explain: "voyager → voyageant.",
        },
      ],
    },
    {
      id: "b1-negation-nee",
      title: "Négations Complexes",
      explanation:
        "ne…plus (no more), ne…rien (nothing), ne…personne (no one), ne…jamais (never), ne…que (only), ne…aucun (none). In compound tenses both parts surround the auxiliary: Je n'ai rien vu. Personne can follow the verb: Je ne connais personne.",
      examples: [
        { fr: "Je ne bois plus de café.", en: "I no longer drink coffee." },
        { fr: "Je n'ai rien compris.", en: "I understood nothing." },
        { fr: "Il ne sort jamais le soir.", en: "He never goes out in the evening." },
        { fr: "Il ne reste que dix minutes.", en: "Only ten minutes remain." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Negation",
      exercises: [
        {
          id: "b1-neg-1",
          type: "multiple_choice",
          prompt: "Complete: Il ne fume ___. (no longer)",
          options: ["jamais", "plus", "rien", "personne"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b1-neg-2",
          type: "fill_in_blank",
          prompt: "Complete: Je n'ai ___ vu. (nothing)",
          answer: "rien",
          skill: "grammar",
        },
        {
          id: "b1-neg-3",
          type: "translation",
          prompt: "Translate to French: I never eat meat.",
          answer: "Je ne mange jamais de viande",
          answerVariants: ["je ne mange jamais de viande"],
          skill: "grammar",
        },
      ],
    },
    {
      id: "b1-irregular-plural",
      title: "Plurals & Accords Spéciaux",
      explanation:
        "Nouns ending in -al → -aux (cheval → chevaux), -ou → -oux (bijou → bijoux), -eau/-eu → -x (château → châteaux), -s/-x/-z → unchanged in plural. Compound words: des après-midi (invariable), des garde-mangers.",
      examples: [
        { fr: "Les chevaux galopent.", en: "The horses gallop." },
        { fr: "Les châteaux sont anciens.", en: "The castles are old." },
        { fr: "Je vois des hommes.", en: "I see men." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Plurals",
      exercises: [
        {
          id: "b1-plur-1",
          type: "multiple_choice",
          prompt: "Plural of 'journal'?",
          options: ["journals", "journaux", "journals", "jounaux"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b1-plur-2",
          type: "fill_in_blank",
          prompt: "Plural of 'château':",
          answer: "châteaux",
          answerVariants: ["chateaux"],
          skill: "grammar",
        },
      ],
    },
  ],

  vocabulary: [
    {
      theme: "Work & Career",
      items: [
        { fr: "l'entreprise", en: "the company", example: "Elle travaille dans une grande entreprise.", exampleEn: "She works in a large company." },
        { fr: "le/la collègue", en: "the colleague", example: "Mes collègues sont sympas.", exampleEn: "My colleagues are nice." },
        { fr: "le rendez-vous", en: "the appointment", example: "J'ai un rendez-vous à 14h.", exampleEn: "I have an appointment at 2pm." },
        { fr: "embaucher", en: "to hire", example: "L'entreprise embauche des ingénieurs.", exampleEn: "The company is hiring engineers." },
        { fr: "le salaire", en: "the salary", example: "Le salaire est attractif.", exampleEn: "The salary is attractive." },
        { fr: "la formation", en: "the training", example: "La formation dure deux semaines.", exampleEn: "The training lasts two weeks." },
        { fr: "chercher du travail", en: "to look for work", example: "Il cherche du travail depuis un mois.", exampleEn: "He's been looking for work for a month." },
        { fr: "la réunion", en: "the meeting", example: "La réunion commence à dix heures.", exampleEn: "The meeting starts at ten." },
        { fr: "un emploi", en: "a job", example: "Cet emploi est intéressant.", exampleEn: "This job is interesting." },
        { fr: "le poste", en: "the position", example: "Elle a postulé pour ce poste.", exampleEn: "She applied for this position." },
      ],
    },
    {
      theme: "News & Media",
      items: [
        { fr: "l'actualité", en: "the news", example: "Je regarde l'actualité le soir.", exampleEn: "I watch the news in the evening." },
        { fr: "le journal", en: "the newspaper", example: "Il lit le journal au café.", exampleEn: "He reads the newspaper at the café." },
        { fr: "la télévision", en: "the television", example: "La télévision est allumée.", exampleEn: "The TV is on." },
        { fr: "le reportage", en: "the report", example: "Le reportage était émouvant.", exampleEn: "The report was moving." },
        { fr: "l'article", en: "the article", example: "L'article est bien écrit.", exampleEn: "The article is well written." },
        { fr: "le journaliste", en: "the journalist", example: "Le journaliste pose des questions.", exampleEn: "The journalist asks questions." },
        { fr: "l'info", en: "the information/headline", example: "J'ai vu ça aux infos.", exampleEn: "I saw that on the news." },
        { fr: "à la une", en: "front page", example: "Cette histoire est à la une.", exampleEn: "This story is on the front page." },
      ],
    },
    {
      theme: "Environment",
      items: [
        { fr: "l'environnement", en: "the environment", example: "Protégeons l'environnement.", exampleEn: "Let's protect the environment." },
        { fr: "le réchauffement climatique", en: "climate warming", example: "Le réchauffement préoccupe les scientifiques.", exampleEn: "Climate warming worries scientists." },
        { fr: "la pollution", en: "the pollution", example: "La pollution de l'air est grave.", exampleEn: "Air pollution is serious." },
        { fr: "le recyclage", en: "recycling", example: "Le tri et le recyclage sont importants.", exampleEn: "Sorting and recycling are important." },
        { fr: "les énergies renouvelables", en: "renewable energies", example: "On investit dans les énergies renouvelables.", exampleEn: "We invest in renewable energies." },
        { fr: "le climat", en: "the climate", example: "Le climat change rapidement.", exampleEn: "The climate is changing quickly." },
        { fr: "la forêt", en: "the forest", example: "La forêt brûle chaque été.", exampleEn: "The forest burns every summer." },
        { fr: "le déchet", en: "the waste", example: "On réduit les déchets.", exampleEn: "We reduce waste." },
      ],
    },
    {
      theme: "Technology",
      items: [
        { fr: "l'ordinateur", en: "the computer", example: "Mon ordinateur est lent.", exampleEn: "My computer is slow." },
        { fr: "le portable", en: "the mobile phone", example: "J'ai oublié mon portable à la maison.", exampleEn: "I forgot my phone at home." },
        { fr: "télécharger", en: "to download", example: "Je télécharge cette application.", exampleEn: "I download this app." },
        { fr: "la connexion", en: "the connection", example: "La connexion Internet est coupée.", exampleEn: "The internet connection is down." },
        { fr: "l'écran", en: "the screen", example: "L'écran est trop petit.", exampleEn: "The screen is too small." },
        { fr: "le mot de passe", en: "the password", example: "J'ai oublié mon mot de passe.", exampleEn: "I forgot my password." },
        { fr: "le clavier", en: "the keyboard", example: "Le clavier est en anglais.", exampleEn: "The keyboard is in English." },
        { fr: "les réseaux sociaux", en: "social media", example: "Il passe ses soirées sur les réseaux.", exampleEn: "He spends his evenings on social media." },
      ],
    },
    {
      theme: "Politics & Society",
      items: [
        { fr: "la loi", en: "the law", example: "Une nouvelle loi a été votée.", exampleEn: "A new law was passed." },
        { fr: "le gouvernement", en: "the government", example: "Le gouvernement annonce des mesures.", exampleEn: "The government announces measures." },
        { fr: "l'élection", en: "the election", example: "L'élection aura lieu en juin.", exampleEn: "The election will take place in June." },
        { fr: "le citoyen", en: "the citizen", example: "Les citoyens votent.", exampleEn: "Citizens vote." },
        { fr: "le droit", en: "the right/law", example: "Chaque citoyen a des droits.", exampleEn: "Every citizen has rights." },
        { fr: "la manifestation", en: "the demonstration", example: "Il y a une manifestation dans le centre.", exampleEn: "There's a demonstration downtown." },
        { fr: "le parti", en: "the party", example: "Ce parti a gagné les élections.", exampleEn: "This party won the election." },
        { fr: "la décision", en: "the decision", example: "La décision est difficile.", exampleEn: "The decision is difficult." },
      ],
    },
    {
      theme: "Arts & Culture",
      items: [
        { fr: "l'œuvre", en: "the work (of art)", example: "Cette œuvre est célèbre.", exampleEn: "This work is famous." },
        { fr: "l'exposition", en: "the exhibition", example: "L'exposition a lieu au musée.", exampleEn: "The exhibition takes place at the museum." },
        { fr: "le peintre", en: "the painter", example: "Ce peintre est connu dans le monde.", exampleEn: "This painter is known worldwide." },
        { fr: "la sculpture", en: "the sculpture", example: "La sculpture se trouve dans le parc.", exampleEn: "The sculpture is in the park." },
        { fr: "le théâtre", en: "the theatre", example: "On va au théâtre demain.", exampleEn: "We're going to the theatre tomorrow." },
        { fr: "le siècle", en: "the century", example: "Ce château date du dix-septième siècle.", exampleEn: "This castle dates from the seventeenth century." },
        { fr: "l'artiste", en: "the artist", example: "L'artiste est très talentueux.", exampleEn: "The artist is very talented." },
        { fr: "le public", en: "the audience", example: "Le public a applaudi longtemps.", exampleEn: "The audience applauded for a long time." },
      ],
    },
    {
      theme: "Education",
      items: [
        { fr: "l'école primaire", en: "primary school", example: "Les enfants vont à l'école primaire.", exampleEn: "Children go to primary school." },
        { fr: "le lycée", en: "high school", example: "Elle est en première au lycée.", exampleEn: "She's in her second-to-last year of high school." },
        { fr: "l'université", en: "the university", example: "L'université propose des cours de français.", exampleEn: "The university offers French courses." },
        { fr: "le diplôme", en: "the diploma", example: "Il a obtenu son diplôme la semaine dernière.", exampleEn: "He got his diploma last week." },
        { fr: "l'examen", en: "the exam", example: "L'examen de français est difficile.", exampleEn: "The French exam is difficult." },
        { fr: "la matière", en: "the subject", example: "Quelle est ta matière préférée ?", exampleEn: "What is your favorite subject?" },
        { fr: "le résultat", en: "the result", example: "Les résultats sont publiés demain.", exampleEn: "The results are published tomorrow." },
        { fr: "réussir", en: "to succeed", example: "Tu vas réussir ton examen !", exampleEn: "You are going to pass your exam!" },
      ],
    },
    {
      theme: "Relationships",
      items: [
        { fr: "le couple", en: "the couple", example: "Le couple se marie en été.", exampleEn: "The couple gets married in summer." },
        { fr: "les fiançailles", en: "the engagement", example: "Les fiançailles ont eu lieu en mai.", exampleEn: "The engagement took place in May." },
        { fr: "se disputer", en: "to argue", example: "Ils se disputent souvent.", exampleEn: "They often argue." },
        { fr: "se réconcilier", en: "to make up", example: "Ils se sont réconciliés.", exampleEn: "They made up." },
        { fr: "le voisin", en: "the neighbor", example: "Nos voisins sont très gentils.", exampleEn: "Our neighbors are very nice." },
        { fr: "la confiance", en: "the trust", example: "Il y a une grande confiance entre eux.", exampleEn: "There is great trust between them." },
        { fr: "s'engager", en: "to commit", example: "Il s'est engagé à aider.", exampleEn: "He committed to helping." },
        { fr: "partager", en: "to share", example: "Nous partageons les mêmes valeurs.", exampleEn: "We share the same values." },
      ],
    },
    {
      theme: "Health & Emergency",
      items: [
        { fr: "l'urgence", en: "the emergency", example: "Appelez l'hôpital en cas d'urgence.", exampleEn: "Call the hospital in case of emergency." },
        { fr: "les urgences", en: "emergency room", example: "Il est allé aux urgences.", exampleEn: "He went to the emergency room." },
        { fr: "l'ambulance", en: "the ambulance", example: "L'ambulance est arrivée en cinq minutes.", exampleEn: "The ambulance arrived in five minutes." },
        { fr: "se blesser", en: "to hurt oneself", example: "Il s'est blessé au genou.", exampleEn: "He hurt his knee." },
        { fr: "le pansement", en: "the bandage", example: "Elle met un pansement sur la coupure.", exampleEn: "She puts a bandage on the cut." },
        { fr: "la fracture", en: "the fracture", example: "C'est une fracture du bras.", exampleEn: "It's a fracture of the arm." },
        { fr: "l'ordonnance", en: "the prescription", example: "Le docteur écrit une ordonnance.", exampleEn: "The doctor writes a prescription." },
        { fr: "l'assurance", en: "the insurance", example: "L'assurance rembourse les frais.", exampleEn: "Insurance reimburses the costs." },
      ],
    },
  ],

  phrases: [
    { fr: "Ça ne mange pas de pain", en: "It costs nothing / it can't hurt", example: "Essaie, ça ne mange pas de pain !", exampleEn: "Try it, it can't hurt!" },
    { fr: "C'est pas grave", en: "It's not serious / no big deal", example: "Tu as oublié ? C'est pas grave.", exampleEn: "You forgot? No big deal." },
    { fr: "Il faut que je…", en: "I have to / I must…", example: "Il faut que je parte tôt.", exampleEn: "I have to leave early." },
    { fr: "Tant mieux / Tant pis", en: "All the better / too bad", example: "Il fait beau ? Tant mieux !", exampleEn: "Nice weather? All the better!" },
    { fr: "À mon avis", en: "In my opinion", example: "À mon avis, il a raison.", exampleEn: "In my opinion, he's right." },
    { fr: "Ça vaut le coup", en: "It's worth it", example: "Ce musée vaut le coup.", exampleEn: "This museum is worth it." },
    { fr: "Ça dépend", en: "It depends", example: "Tu viens à pied ? Ça dépend.", exampleEn: "You're coming on foot? It depends." },
    { fr: "J'en ai marre", en: "I'm fed up", example: "J'en ai marre de la pluie.", exampleEn: "I'm fed up with the rain." },
    { fr: "Il se peut que", en: "It may be that", example: "Il se peut qu'il pleuve.", exampleEn: "It may rain." },
    { fr: "N'importe comment", en: "Any way / no matter how", example: "N'importe comment, on arrive.", exampleEn: "Either way, we'll get there." },
  ],

  pronunciation: {
    phonemes: [
      { symbol: "œ̃/ɛ̃", name: "Nasal vowels (un, in)", examples: ["brun", "brin", "un", "vin"], note: "Listen for the difference between un (still in francophone Africa/Quebec) and in (Paris merges them)." },
      { symbol: "y", name: "The /y/ vowel (u)", examples: ["tu", "vu", "rue", "mule"], note: "Round your lips and say 'ee' — the most distinctive French sound for English speakers." },
      { symbol: "ø/œ", name: "eu sounds", examples: ["peu (ø)", "peur (œ)", "heure", "feu"], note: "ø is closed (like in 'peu'), œ is open (like in 'peur')." },
      { symbol: "ʁ", name: "The French r", examples: ["Paris", "rouge", "grand", "merci"], note: "Produced at the back of the throat; English speakers often tap it like the Spanish r." },
      { symbol: "ɛ̃/ɔ̃/ɑ̃", name: "The three main nasals", examples: ["pain (ɛ̃)", "pont (ɔ̃)", "blanc (ɑ̃)"], note: "Maintain nasal vibration without closing the mouth fully (with an (é) written)." },
      { symbol: "l mouillé", name: "ill after consonant (front)", examples: ["famille", "fille", "feuille"], note: "In front of a vowel they say /j/ sound." },
    ],
    minimalPairs: [
      { a: "tu", b: "tout" },
      { a: "dessus", b: "dessous" },
      { a: "peu", b: "peur" },
      { a: "pain", b: "paon" },
      { a: "brin", b: "brun" },
      { a: "posé", b: "pois" },
      { a: "fille", b: "fiche" },
      { a: "rue", b: "roue" },
      { a: "mil", b: "mille" },
      { a: "mangé", b: "manger" },
    ],
    rules: [
      "The 'eu' becomes /ø/ at the end of a word (peu) and /œ/ elsewhere (peur).",
      "The nasal vowels must not be followed by a pronounced nasal consonant: bon bonbon (n is silent).",
      "The /y/ of 'u' requires tightly rounded lips — 'tu' must not sound like 'too'.",
      "The final e (mute) makes the preceding consonant pronounced in liaisons: les amis (/lez‿ami/).",
      "The French r is never rolled; a light uvular friction at the back of the mouth.",
    ],
  },

  listening: [
    {
      id: "b1-listen-1",
      title: "Une conversation au travail",
      text: "Marc : Salut Julie, tu as regardé les nouvelles ce matin ? — Julie : Non, j'étais en réunion. Qu'est-ce qui se passe ? — Marc : L'entreprise a annoncé qu'elle allait embaucher cinquante nouvelles personnes à Lyon. — Julie : C'est une bonne nouvelle ! Mon cousin cherche un poste de développeur. — Marc : Qu'il envoie son CV rapidement, alors !",
      questions: [
        {
          id: "b1-listen-1-q1",
          type: "multiple_choice",
          prompt: "Pourquoi Julie n'a pas vu les nouvelles ?",
          options: ["Elle dormait", "Elle était en réunion", "Elle était malade", "Elle était en congé"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b1-listen-1-q2",
          type: "multiple_choice",
          prompt: "Qu'est-ce que l'entreprise a annoncé ?",
          options: ["Des licenciements", "Une fermeture", "Des embauches", "Un déménagement"],
          answer: 2,
          skill: "listening",
        },
        {
          id: "b1-listen-1-q3",
          type: "multiple_choice",
          prompt: "Qu'est-ce que le cousin de Julie cherche ?",
          options: ["Un logement", "Un emploi", "Un stage", "Une formation"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
    {
      id: "b1-listen-2",
      title: "Météo et plan",
      text: "Avec le beau temps prévu ce week-end, on organise une sortie à la campagne. On partira samedi matin à neuf heures et on reviendra dimanche soir. Si la météo change, on ira au musée d'histoire naturelle à la place. Chacun apporte un plat à partager pour le pique-nique du samedi midi.",
      questions: [
        {
          id: "b1-listen-2-q1",
          type: "multiple_choice",
          prompt: "Quel est le plan si le temps reste beau ?",
          options: ["Un pique-nique en ville", "Une sortie à la campagne", "Une visite au musée", "Un voyage en train"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b1-listen-2-q2",
          type: "multiple_choice",
          prompt: "Quand partent-ils ?",
          options: ["Vendredi soir", "Samedi matin", "Samedi soir", "Dimanche matin"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b1-listen-2-q3",
          type: "multiple_choice",
          prompt: "Que faut-il apporter ?",
          options: ["Un cadeau", "Un plat à partager", "Un parapluie", "Un sac de couchage"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
  ],

  reading: [
    {
      id: "b1-read-1",
      title: "Un changement de carrière",
      text: "Après dix ans comme comptable, Léa a décidé de changer de vie. Elle a suivi une formation de pâtissière pendant un an et vient d'ouvrir sa propre boutique au centre-ville. Le début a été difficile : les banques refusaient son prêt et le loyer était élevé. Mais grâce au bouche-à-oreille, sa clientèle grandit chaque semaine. « J'ai enfin un travail qui a du sens pour moi », raconte-t-elle, les mains enfarinées.",
      questions: [
        {
          id: "b1-read-1-q1",
          type: "multiple_choice",
          prompt: "Quel était le métier de Léa avant ?",
          options: ["Pâtissière", "Comptable", "Boulangère", "Banquière"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b1-read-1-q2",
          type: "multiple_choice",
          prompt: "Quelle difficulté a-t-elle rencontrée ?",
          options: ["Le manque de clients", "Une maladie", "Le refus des banques", "Une fermeture"],
          answer: 2,
          skill: "reading",
        },
        {
          id: "b1-read-1-q3",
          type: "multiple_choice",
          prompt: "Comment sa clientèle augmente-t-elle ?",
          options: ["Grâce à la publicité", "Grâce au bouche-à-oreille", "Grâce aux réseaux sociaux", "Grâce à un grand magasin"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b1-read-1-q4",
          type: "multiple_choice",
          prompt: "Comment se sent Léa à la fin du texte ?",
          options: ["Fatiguée", "Décue", "Épanouie", "Stressée"],
          answer: 2,
          skill: "reading",
        },
      ],
    },
    {
      id: "b1-read-2",
      title: "Le télétravail",
      text: "Depuis les années 2020, le télétravail a transformé la vie des salariés. Les entreprises économisent sur les bureaux, les employés gagnent du temps de transport. Mais tout le monde ne s'y retrouve pas : certains souffrent de la solitude et de la difficulté à séparer vie privée et vie professionnelle. C'est pourquoi beaucoup d'entreprises choisissent désormais une formule hybride : deux ou trois jours au bureau, le reste de la semaine à la maison.",
      questions: [
        {
          id: "b1-read-2-q1",
          type: "multiple_choice",
          prompt: "Quel est l'avantage du télétravail pour les employés ?",
          options: ["Plus d'argent", "Moins de temps de transport", "Plus de bureau", "Plus de réunions"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b1-read-2-q2",
          type: "multiple_choice",
          prompt: "Quel est l'inconvénient mentionné ?",
          options: ["Le bruit", "La solitude", "Le coût", "L'ordinateur"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b1-read-2-q3",
          type: "multiple_choice",
          prompt: "Que choisissent beaucoup d'entreprises ?",
          options: ["Un retour total au bureau", "Une formule hybride", "Plus de vacances", "Le travail le week-end"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  writingPrompts: [
    {
      id: "b1-write-1",
      title: "Opinion argumentée",
      task: "Rédigez un texte de 100 à 130 mots pour ou contre le télétravail. Donnez au moins trois arguments et une introduction.",
      minWords: 100,
    },
    {
      id: "b1-write-2",
      title: "Lettre formelle",
      task: "Écrivez une lettre de candidature (80 à 120 mots) pour un poste de votre choix : qui vous êtes, expériences, motivation, disponibilité.",
      minWords: 80,
    },
  ],

  speakingPrompts: [
    {
      id: "b1-speaking-1",
      title: "Raconter un film",
      scenario: "Racontez un film que vous avez vu récemment : l'histoire, les personnages, ce que vous en pensez, et si vous recommandez.",
      hint: "Il s'agit de… / L'histoire se passe en… / Je pense que… / Je recommande…",
    },
    {
      id: "b1-speaking-2",
      title: "Débattre un sujet",
      scenario: "Donnez votre opinion sur le sujet : « Faut-il utiliser moins la voiture en ville ? » Justifiez avec au moins deux arguments et répondez à une objection.",
      hint: "À mon avis / D'une part… d'autre part / Certains disent que… mais…",
    },
  ],

  stories: [
    {
      id: "b1-story-1",
      title: "Le colis mystérieux",
      level: "B1",
      dialogue: [
        { speaker: "Narrateur", text: "Ce matin, Paul a trouvé un grand colis devant sa porte. Il n'avait pas commandé de paquet." },
        { speaker: "Paul", text: "C'est étrange. Je n'attends aucun colis." },
        { speaker: "Marie", text: "Regarde l'adresse. C'est peut-être une erreur." },
        { speaker: "Paul", text: "L'adresse est correcte, mais l'expéditeur est inconnu." },
        { speaker: "Marie", text: "Ouvre-le ! Je suis trop curieuse." },
        { speaker: "Paul", text: "Et si c'était un piège ?" },
        { speaker: "Marie", text: "Allez, personne n'envoie de bombes par la poste." },
        { speaker: "Narrateur", text: "Paul a ouvert le colis. Il contenait des livres anciens et un message : « Merci pour le coffre ! »" },
        { speaker: "Paul", text: "Mais… je n'ai jamais eu de coffre !" },
        { speaker: "Marie", text: "Attends… le coffre que tu as vendu la semaine dernière ?" },
      ],
      questions: [
        {
          id: "b1-story-1-q1",
          type: "multiple_choice",
          prompt: "Qu'est-ce que Paul a trouvé ?",
          options: ["Une lettre", "Un colis", "Un coffre", "Une surprise"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b1-story-1-q2",
          type: "multiple_choice",
          prompt: "Que contient le colis ?",
          options: ["Des vêtements", "Des livres anciens", "De l'argent", "Des photos"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b1-story-1-q3",
          type: "multiple_choice",
          prompt: "Qu'est-ce que Paul a vendu la semaine dernière ?",
          options: ["Une voiture", "Un coffre", "Une maison", "Un tableau"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  scenarios: [
    {
      id: "b1-scenario-entretien",
      title: "Un entretien d'embauche",
      setting: "Vous passez un entretien pour un poste de commercial dans une entreprise francophone.",
      dialogue: [
        { speaker: "Recruteur", text: "Bonjour, merci d'être venu. Pouvez-vous vous présenter ?" },
        { speaker: "Candidat", text: "Bonjour, je m'appelle [Prénom], j'ai cinq ans d'expérience dans la vente." },
        { speaker: "Recruteur", text: "Pourquoi voulez-vous travailler chez nous ?" },
        { speaker: "Candidat", text: "Votre entreprise m'intéresse parce qu'elle innove beaucoup et qu'elle est présente à l'international." },
        { speaker: "Recruteur", text: "Quelles sont vos qualités principales ?" },
        { speaker: "Candidat", text: "Je suis persévérant et je sais écouter les clients." },
        { speaker: "Recruteur", text: "Pourriez-vous me parler d'une réussite récente ?" },
        { speaker: "Candidat", text: "L'année dernière, j'ai augmenté mes ventes de trente pour cent." },
        { speaker: "Recruteur", text: "Très bien. Quand seriez-vous disponible ?" },
        { speaker: "Candidat", text: "Je peux commencer dès le mois prochain." },
      ],
    },
  ],

  culturalNotes: [
    {
      title: "Le cumul des mentions « vous » et la politesse",
      body: "At wA2+ you still must keep the French distinction between « tu » and « vous ». In the workplace colleagues often say tu, but in shops, with elders, and with strangers, vous remains the norm. Using tu with a stranger is perceived as rude.",
    },
    {
      title: "La grève comme tradition",
      body: "Strikes and demonstrations are a recurring part of French working life, protected by law. Travelers should learn phrases like « la grève » (strike) and always check transport « perturbation » announcements.",
    },
    {
      title: "Le bouche-à-oreille",
      body: "Word of mouth (bouche-à-oreille) drives a huge share of business in francophone countries. Restaurants, bakeries and shops often thrive on reputation rather than advertising.",
    },
  ],

  test: {
    passingScore: 240,
    maxScore: 400,
    listening: [
      {
        id: "b1-test-l1",
        type: "multiple_choice",
        prompt: "Vous entendez : « Le départ de la randonnée est prévu à sept heures mais le petit-déjeuner est servi à partir de six heures trente. » — À quelle heure pouvez-vous déjeuner ?",
        audio: "Le départ de la randonnée est prévu à sept heures mais le petit-déjeuner est servi à partir de six heures trente.",
        options: ["À 6h30", "À 7h", "À 7h30", "À 6h"],
        answer: 0,
        skill: "listening",
      },
      {
        id: "b1-test-l2",
        type: "multiple_choice",
        prompt: "Vous entendez : « Bien que le temps soit mauvais, le vol partira comme prévu. » — Que va-t-il se passer ?",
        audio: "Bien que le temps soit mauvais, le vol partira comme prévu.",
        options: ["Le vol est annulé", "Le vol partira normalement", "Le vol est reporté", "Le vol reste à l'aéroport"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "b1-test-l3",
        type: "multiple_choice",
        prompt: "Vous entendez : « Si j'avais su, je ne serais pas venu ! » — Que signifie cette phrase ?",
        audio: "Si j'avais su, je ne serais pas venu !",
        options: ["Il est content d'être venu", "Il regrette d'être venu", "Il veut revenir", "Il a changé d'avis"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "b1-test-l4",
        type: "multiple_choice",
        prompt: "Vous entendez : « L'entreprise cherche une personne qui parle couramment anglais et qui ait passé un an à l'étranger. » — Quel est le profil recherché ?",
        audio: "L'entreprise cherche une personne qui parle couramment anglais et qui ait passé un an à l'étranger.",
        options: ["Qui parle deux langues", "Qui parle anglais et a voyagé un an", "Qui a un diplôme", "Qui travaille à l'étranger"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "b1-test-l5",
        type: "multiple_choice",
        prompt: "Vous entendez : « Il nous faudrait partir avant neuf heures pour éviter les embouteillages sur le périphérique. » — Pourquoi partir avant neuf heures ?",
        audio: "Il nous faudrait partir avant neuf heures pour éviter les embouteillages sur le périphérique.",
        options: ["Pour éviter les embouteillages", "Pour prendre le train", "Pour arriver en retard", "Pour trouver un parking"],
        answer: 0,
        skill: "listening",
      },
      {
        id: "b1-test-l6",
        type: "multiple_choice",
        prompt: "Vous entendez : « Sans la permission de ses parents, il ne pourra pas participer au voyage scolaire. » — Que faut-il pour participer ?",
        audio: "Sans la permission de ses parents, il ne pourra pas participer au voyage scolaire.",
        options: ["De l'argent", "Une permission", "Un billet", "Une carte"],
        answer: 1,
        skill: "listening",
      },
    ],
    reading: [
      {
        id: "b1-test-r1",
        type: "multiple_choice",
        prompt: "« Malgré la pluie, le festival a attiré un public record. Les organisateurs prévoient dès maintenant des chariots supplémentaires pour l'année prochaine. » — Comment était le festival ?",
        options: ["Raté", "Très fréquenté", "Annulé", "Déplacé"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b1-test-r2",
        type: "multiple_choice",
        prompt: "« Vous pouvez acheter votre abonnement en ligne ou à l'accueil. L'abonnement en ligne est moins cher de dix euros par mois. » — Quel est l'avantage de l'abonnement en ligne ?",
        options: ["Il est plus rapide", "Il coûte moins cher", "Il est payant", "Il est réservé"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b1-test-r3",
        type: "multiple_choice",
        prompt: "« Si la situation continue, les habitants devront chercher une autre source d'eau potable. Le réservoir actuel est presque vide. » — Quel est le problème ?",
        options: ["L'augmentation des prix", "Le manque d'eau", "La pollution", "Les voisins"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b1-test-r4",
        type: "multiple_choice",
        prompt: "« La boutique ferme exceptionnellement à dix-sept heures au lieu de dix-neuf heures à cause d'un inventaire. » — Quand ferme la boutique ?",
        options: ["À 17h", "À 19h", "À 12h", "À 20h"],
        answer: 0,
        skill: "reading",
      },
      {
        id: "b1-test-r5",
        type: "multiple_choice",
        prompt: "« Ce n'est pas la première fois qu'on propose cette réforme. L'année dernière, elle a été refusée, mais aujourd'hui les syndicats semblent plus ouverts. » — Quelle est la situation des syndicats ?",
        options: ["Ils refusent", "Ils sont plus ouverts", "Ils proposent la réforme", "Ils font une grève"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b1-test-r6",
        type: "multiple_choice",
        prompt: "« Les clients disposent de quinze jours après l'achat pour retourner un produit avec son ticket de caisse. » — Combien de temps pour retourner un produit ?",
        options: ["Cinq jours", "Deux semaines", "Un mois", "Un an"],
        answer: 1,
        skill: "reading",
      },
    ],
    writing: [
      {
        id: "b1-test-w1",
        title: "Lettre de réclamation",
        prompt: "Vous avez acheté un vêtement qui est arrivé abîmé. Écrivez un e-mail au service client (100 à 130 mots) pour expliquer le problème et demander un remplacement.",
        minWords: 100,
      },
      {
        id: "b1-test-w2",
        title: "Opinion",
        prompt: "Rédigez 100 à 130 mots sur la question : « Vaut-il mieux vivre en ville ou à la campagne ? » Donnez des arguments pour et contre, puis votre avis.",
        minWords: 100,
      },
    ],
    speaking: [
      {
        id: "b1-test-s1",
        title: "Présenter un projet",
        prompt: "Présentez pendant 2-3 minutes un projet important pour vous (voyage, travail, achat) : le contexte, ce que vous avez fait, les difficultés et les résultats.",
        hint: "Je voulais… / J'ai dû… / Finalement…",
      },
      {
        id: "b1-test-s2",
        title: "Défendre une opinion",
        prompt: "Donnez votre opinion et défendez-la : « Le télétravail devrait être obligatoire une partie de la semaine. » Préparez 2 arguments et une réponse à une objection.",
        hint: "D'abord, je pense que… / Ensuite, on peut dire que…",
      },
    ],
    pronunciation: [
      { id: "b1-test-p1", type: "pronunciation", prompt: "Prononcez ce mot :", word: "surtout", ipa: "/syʁtu/", skill: "pronunciation" },
      { id: "b1-test-p2", type: "pronunciation", prompt: "Prononcez ce mot :", word: "grande", ipa: "/gʁɑ̃d/", skill: "pronunciation" },
      { id: "b1-test-p3", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "J'en ai marre de la pluie", ipa: "/ʒɑ̃ nɛ maʁ də la plɥi/", skill: "pronunciation" },
      { id: "b1-test-p4", type: "pronunciation", prompt: "Prononcez ce mot :", word: "l'université", ipa: "/ly.nivɛʁ.si.te/", skill: "pronunciation" },
    ],
  },
};