import type { LevelContent } from "@/lib/types";

export const b2: LevelContent = {
  level: "B2",

  grammar: [
    {
      id: "b2-passe-subjonctif",
      title: "Le Subjonctif Passé",
      explanation:
        "Subjunctive in the past: avoir/être (subjunctive present) + past participle. Il faut que tu sois venu. Used when the verb in the main clause is in the past or indicates a past action relative to the main verb. Il est possible qu'il soit parti.",
      examples: [
        { fr: "Je regrette qu'il soit parti.", en: "I regret that he has left." },
        { fr: "Il est peu probable qu'ils aient réussi.", en: "It's unlikely they succeeded." },
        { fr: "Bien qu'elle ait travaillé dur, elle n'a pas été embauchée.", en: "Although she worked hard, she wasn't hired." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Subjunctive",
      exercises: [
        {
          id: "b2-subj-passe-1",
          type: "multiple_choice",
          prompt: "Complete: Je suis content qu'ils ___ arrivés. (arriver, être-verb)",
          options: ["sont", "soient", "seraient", "auront"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b2-subj-passe-2",
          type: "fill_in_blank",
          prompt: "Complete: Il est possible qu'elle ___ oublié. (oublier, avoir)",
          answer: "ait",
          skill: "grammar",
          explain: "impossible que + subj passé → ait + participe.",
        },
      ],
    },
    {
      id: "b2-voix-pronominale",
      title: "Le Passif avec Être (renforcer)",
      explanation:
        "Reinforcing passive: agent by par (definite action) or de (natural causes/abstract). Note that the passive is much less used in French than English. Certain verb types (intransitive, or those expressing measure) cannot passivate.",
      examples: [
        { fr: "Le mur est peint par les ouvriers.", en: "The wall is painted by the workers." },
        { fr: "La ville a été détruite par le séisme.", en: "The city was destroyed by the earthquake." },
        { fr: "Elle est aimée de tous.", en: "She is loved by everyone." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Passive & on expression",
      exercises: [
        {
          id: "b2-passif-1",
          type: "multiple_choice",
          prompt: "Rewrite actively: Le gâteau a été mangé par les enfants. → Les enfants ___ le gâteau.",
          options: ["ont mangé", "ont été mangés", "mangent", "sont mangés"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "b2-passif-2",
          type: "fill_in_blank",
          prompt: "Complete: Ce film ___ beaucoup aimé. (est, est-ce que ce film)",
          answer: "est",
          skill: "grammar",
        },
      ],
    },
    {
      id: "b2-futur-ante",

      title: "Le Futur Antérieur",
      explanation:
        "Future perfect: describes an action that will be completed before another action in the future. Formed with avoir/être (future simple) + past participle. Quand tu auras fini, tu pourras sortir.",
      examples: [
        { fr: "Dès que j'aurai fini, je t'appellerai.", en: "As soon as I have finished, I'll call you." },
        { fr: "Il aura terminé son rapport demain.", en: "He will have finished his report tomorrow." },
        { fr: "Après qu'elle aura tout expliqué, on décidera.", en: "After she has explained everything, we'll decide." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Future perfect",
      exercises: [
        {
          id: "b2-fut-ante-1",
          type: "fill_in_blank",
          prompt: "Complete: Quand tu ___ fini, appelle-moi. (avoir, tu)",
          answer: "auras",
          skill: "grammar",
        },
        {
          id: "b2-fut-ante-2",
          type: "multiple_choice",
          prompt: "Complete: Dès que nous ___ arrivés, nous vous préviendrons.",
          options: ["sommes", "serons", "soient", "avions"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "b2-conditionnel-passe",
      title: "Le Conditionnel Passé",
      explanation:
        "Conditional perfect: would have done. Form: avoir/être (conditional present) + past participle. Used with si + plus-que-parfait: Si tu m'avais parlé, j'aurais aidé. Also expresses unconfirmed reports and regrets. Je serais venu si j'avais su.",
      examples: [
        { fr: "J'aurais aimé te voir.", en: "I would have liked to see you." },
        { fr: "Si tu étais venu, tu aurais adoré.", en: "If you had come, you would have loved it." },
        { fr: "Elle serait partie plus tôt, mais elle a été retenue.", en: "She would have left earlier, but she was held up." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Conditional perfect",
      exercises: [
        {
          id: "b2-cond-passe-1",
          type: "multiple_choice",
          prompt: "Complete: Si j'avais su, je ___ (venir).",
          options: ["serais venu", "serai venu", "viens", "venais"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "b2-cond-passe-2",
          type: "fill_in_blank",
          prompt: "Complete: J'aurais ___ (faire) mes devoirs, mais j'étais fatigué.",
          answer: "fait",
          skill: "grammar",
        },
      ],
    },
    {
      id: "b2-propositions-relatives",
      title: "Les Propositions Relatives Complexes",
      explanation:
        "Relative clauses with prepositions + que/qui: auquel, duquel, dont, où, mais also à qui, pour qui, avec quoi. Note that in French you can't end a sentence with a preposition before que (that would be wrong): « voilà la fille à qui j'ai parlé », not « la fille que j'ai parlé à ».",
      examples: [
        { fr: "C'est la femme avec qui je voyage.", en: "She is the woman I travel with." },
        { fr: "Le sujet sur lequel nous discutons.", en: "The topic we're discussing (on which)." },
        { fr: "C'est un ami à qui je me confie.", en: "He's a friend I confide in." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Relative clauses",
      exercises: [
        {
          id: "b2-rel-1",
          type: "multiple_choice",
          prompt: "Complete: C'est l'homme ___ j'ai rencontré sa femme.",
          options: ["que", "dont", "avec lequel", "qui"],
          answer: 1,
          skill: "grammar",
          explain: "dont introduces 'whose wife'.",
        },
        {
          id: "b2-rel-2",
          type: "multiple_choice",
          prompt: "Complete: Voilà la personne ___ dépends.",
          options: ["que", "dont", "de qui", "auquel"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "b2-structures-concessives",
      title: "Concession: bien que, malgré, en dépit de",
      explanation:
        "bien que / quoique + subjunctive: Bien qu'il soit... malgré / en dépit de + noun: Malgré la pluie. Néanmoins, pourtant (nonetheless). Note that bien que is tricky: in French it is quite frequent but is followed by the subjunctive.",
      examples: [
        { fr: "Bien qu'il soit fatigué, il continue.", en: "Although he's tired, he continues." },
        { fr: "Malgré les difficultés, elle a réussi.", en: "Despite the difficulties, she succeeded." },
        { fr: "Il est riche ; pourtant, il n'est pas heureux.", en: "He's rich; yet he isn't happy." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Concession",
      exercises: [
        {
          id: "b2-concess-1",
          type: "multiple_choice",
          prompt: "Complete: ___ il pleuve, nous sortons.",
          options: ["Bien que", "Grâce à", "À cause de", "Parce que"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "b2-concess-2",
          type: "fill_in_blank",
          prompt: "Complete (either): ___ la fatigue, elle a terminé le marathon. (Despite)",
          answer: "malgre",
          answerVariants: ["malgre"],
          skill: "grammar",
          explain: "Malgré + noun = despite.",
        },
      ],
    },
    {
      id: "b2-formes-nominaux",
      title: "Le Nominalisation",
      explanation:
        "Turning verbs into nouns is very common in formal French: choisir → le choix, partir → le départ, arriver → l'arrivée, décider → la décision. Essential for writing essays and reports. Il a pris la décision de partir plutôt que il a décidé de partir.",
      examples: [
        { fr: "La construction du nouveau bâtiment a commencé.", en: "The construction of the new building has begun." },
        { fr: "L'achat de cette maison était une bonne idée.", en: "Buying this house was a good idea." },
        { fr: "Après l'annonce des résultats, il y a eu des félicitations.", en: "After the announcement of the results, there were congratulations." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Nominalisation",
      exercises: [
        {
          id: "b2-nom-1",
          type: "multiple_choice",
          prompt: "Which noun comes from 'partir'?",
          options: ["la part", "le départ", "le partage", "le parti"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b2-nom-2",
          type: "fill_in_blank",
          prompt: "Translate: the arrival → l'___",
          answer: "arrivée",
          skill: "grammar",
        },
      ],
    },
    {
      id: "b2-discours-rapporte-passe",
      title: "Discours Rapporté au Passé",
      explanation:
        "When introducing a report with a past verb (il a dit que), shift tenses: present → imparfait, passé composé → plus-que-parfait, futur → conditionnel, futur antérieur → conditionnel passé. Questions: il m'a demandé si / où / ce que… il m'a dit de + infinitive.",
      examples: [
        { fr: "Il a dit qu'il était fatigué.", en: "He said he was tired." },
        { fr: "Elle a annoncé qu'elle partirait le lendemain.", en: "She announced she would leave the next day." },
        { fr: "Il m'a demandé ce que je voulais.", en: "He asked me what I wanted." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Reported speech",
      exercises: [
        {
          id: "b2-reported-1",
          type: "multiple_choice",
          prompt: "Report in the past: « Je viendrai demain » → Il a dit qu'il ___ le lendemain.",
          options: ["viendra", "viendrait", "venait", "avait venu"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b2-reported-2",
          type: "multiple_choice",
          prompt: "Report: « Avez-vous vu ce film ? » → Il m'a demandé si ___.",
          options: ["j'avais vu ce film", "vous aviez vu ce film", "j'ai vu ce film", "elle avait vu ce film"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
    {
      id: "b2-verbes-regime-prepositionnel",
      title: "Verbes + Prépositions",
      explanation:
        "Learning which preposition follows which verb is vital: décider de, réussir à, profiter de, s'habituer à, penser à, se souvenir de, avoir besoin de, renoncer à. Often these are mistranslated from English. Use them in context rather than translate word-for-word.",
      examples: [
        { fr: "Il réussit à communiquer en français.", en: "He manages to communicate in French." },
        { fr: "Je profite de ce temps pour me reposer.", en: "I take advantage of this time to rest." },
        { fr: "Elle s'habitue à la vie ici.", en: "She is getting used to life here." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Verb + preposition",
      exercises: [
        {
          id: "b2-verbprep-1",
          type: "multiple_choice",
          prompt: "Complete: J'ai du mal ___ me concentrer.",
          options: ["à", "de", "pour", "dans"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "b2-verbprep-2",
          type: "multiple_choice",
          prompt: "Complete: Il rêve ___ devenir acteur.",
          options: ["de", "à", "pour", "par"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
    {
      id: "b2-articuler-idées",
      title: "Articulateurs de Discours",
      explanation:
        "Connectives make writing coherent: d'une part… d'autre part, en outre, par conséquent, par ailleurs, cependant, de plus, de surcroît, en revanche, au contraire. Practice structuring your writing with them.",
      examples: [
        { fr: "D'une part, c'est pratique ; d'autre part, c'est cher.", en: "On the one hand, it's practical; on the other, it's expensive." },
        { fr: "Les tests sont réussis ; par conséquent, nous pouvons lancer le produit.", en: "The tests pass; consequently, we can launch the product." },
        { fr: "En revanche, le service était excellent.", en: "On the other hand, the service was excellent." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Connectives",
      exercises: [
        {
          id: "b2-connect-1",
          type: "multiple_choice",
          prompt: "Choose the contrast connector: ___ du prix, la qualité est bonne.",
          options: ["En outre", "En revanche", "D'ailleurs", "De plus"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "b2-connect-2",
          type: "multiple_choice",
          prompt: "Choose the cause/effect connector: Il était malade ; ___, il est resté chez lui.",
          options: ["d'abord", "par conséquent", "par ailleurs", "en revanche"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
  ],

  vocabulary: [
    {
      theme: "Interviews & Media",
      items: [
        { fr: "l'enquête", en: "the survey/investigation", example: "L'enquête montre que les gens lisent moins.", exampleEn: "The survey shows people read less." },
        { fr: "le débat", en: "the debate", example: "Le débat a été houleux.", exampleEn: "The debate was heated." },
        { fr: "l'éditorial", en: "the editorial", example: "L'éditorial résume la position du journal.", exampleEn: "The editorial summarizes the newspaper's position." },
        { fr: "le reportage", en: "the report", example: "Le reportage a été tourné en Ukraine.", exampleEn: "The report was filmed in Ukraine." },
        { fr: "la chaîne", en: "the channel", example: "Cette chaîne de télévision est publique.", exampleEn: "This TV channel is public." },
        { fr: "les médias", en: "the media", example: "Les médias ont beaucoup parlé de cette affaire.", exampleEn: "The media talked a lot about this case." },
        { fr: "le correspondant", en: "the correspondent", example: "Le correspondant à Bruxelles répond en direct.", exampleEn: "The Brussels correspondent answers live." },
        { fr: "l'audience", en: "the audience/ratings", example: "L'audience a battu des records.", exampleEn: "The ratings broke records." },
        { fr: "l'invité", en: "the guest", example: "L'invité du soir était un écrivain.", exampleEn: "The evening's guest was a writer." },
        { fr: "la censure", en: "the censorship", example: "La censure est interdite par la loi.", exampleEn: "Censorship is banned by law." },
      ],
    },
    {
      theme: "Company & Industry",
      items: [
        { fr: "le siège social", en: "the head office", example: "Le siège social se trouve à Paris.", exampleEn: "The head office is in Paris." },
        { fr: "la filiale", en: "the subsidiary", example: "L'entreprise ouvre une filiale au Canada.", exampleEn: "The company is opening a subsidiary in Canada." },
        { fr: "le bénéfice", en: "the profit", example: "Les bénéfices ont augmenté de 10%.", exampleEn: "Profits rose by 10%." },
        { fr: "le chiffre d'affaires", en: "the turnover", example: "Le chiffre d'affaires dépasse le milliard.", exampleEn: "Turnover exceeds one billion." },
        { fr: "la réorganisation", en: "the reorganization", example: "La réorganisation touche tous les services.", exampleEn: "The reorganization affects all departments." },
        { fr: "le concurrent", en: "the competitor", example: "Nos concurrents ont baissé leurs prix.", exampleEn: "Our competitors cut their prices." },
        { fr: "la sous-traitance", en: "the subcontracting", example: "La sous-traitance réduit les coûts.", exampleEn: "Subcontracting reduces costs." },
        { fr: "l'impôt", en: "the tax", example: "L'entreprise paie des impôts importants.", exampleEn: "The company pays significant taxes." },
        { fr: "la marque", en: "the brand", example: "La marque est reconnue à l'international.", exampleEn: "The brand is recognized internationally." },
        { fr: "le siège", en: "the headquarter", example: "Le siège a déménagé à Lyon.", exampleEn: "The headquarters moved to Lyon." },
      ],
    },
    {
      theme: "International & Diplomacy",
      items: [
        { fr: "le traité", en: "the treaty", example: "Le traité a été signé en juin.", exampleEn: "The treaty was signed in June." },
        { fr: "l'ambassadeur", en: "the ambassador", example: "L'ambassadeur a donné une conférence.", exampleEn: "The ambassador gave a lecture." },
        { fr: "la négociation", en: "the negotiation", example: "Les négociations ont échoué.", exampleEn: "The negotiations failed." },
        { fr: "la frontière", en: "the border", example: "La frontière est fermée ce week-end.", exampleEn: "The border is closed this weekend." },
        { fr: "le conflit", en: "the conflict", example: "Le conflit dure depuis deux ans.", exampleEn: "The conflict has lasted two years." },
        { fr: "l'accord", en: "the agreement", example: "Les deux pays ont trouvé un accord.", exampleEn: "The two countries reached an agreement." },
        { fr: "la diplomatie", en: "diplomacy", example: "La diplomatie est la voie préférée.", exampleEn: "Diplomacy is the preferred path." },
        { fr: "l'organisme", en: "the body/organization", example: "Cet organisme surveille les élections.", exampleEn: "This body monitors elections." },
      ],
    },
    {
      theme: "Literature & Writing",
      items: [
        { fr: "le roman", en: "the novel", example: "Ce roman a gagné un prix.", exampleEn: "This novel won a prize." },
        { fr: "la nouvelle", en: "the short story", example: "Il écrit des nouvelles depuis dix ans.", exampleEn: "He writes short stories." },
        { fr: "le poème", en: "the poem", example: "Le poème évoque la mer.", exampleEn: "The poem evokes the sea." },
        { fr: "l'auteur", en: "the author", example: "L'auteur vit au Québec.", exampleEn: "The author lives in Quebec." },
        { fr: "le critique", en: "the critic", example: "Le critique a adoré le livre.", exampleEn: "The critic loved the book." },
        { fr: "le lecteur", en: "the reader", example: "Le lecteur s'identifie au héros.", exampleEn: "The reader identifies with the hero." },
        { fr: "l'éditeur", en: "the publisher", example: "L'éditeur a publié trois mille exemplaires.", exampleEn: "The publisher printed three thousand copies." },
        { fr: "le thème", en: "the theme", example: "Le thème principal est la liberté.", exampleEn: "The main theme is freedom." },
        { fr: "le chapitre", en: "the chapter", example: "Le dernier chapitre est émouvant.", exampleEn: "The last chapter is moving." },
        { fr: "le manuscrit", en: "the manuscript", example: "Elle a envoyé son manuscrit à plusieurs maisons.", exampleEn: "She sent her manuscript to several houses." },
      ],
    },
    {
      theme: "Health & Lifestyle",
      items: [
        { fr: "la nutrition", en: "nutrition", example: "La nutrition est essentielle pour la santé.", exampleEn: "Nutrition is essential for health." },
        { fr: "le rythme de vie", en: "the pace of life", example: "Le rythme de vie en ville est intense.", exampleEn: "The pace of life in the city is intense." },
        { fr: "l'équilibre", en: "the balance", example: "Il cherche un équilibre entre travail et famille.", exampleEn: "He seeks a balance between work and family." },
        { fr: "l'hygiène", en: "hygiene", example: "L'hygiène alimentaire est primordiale.", exampleEn: "Food hygiene is paramount." },
        { fr: "se relaxer", en: "to relax", example: "Je me relaxe avec le yoga.", exampleEn: "I relax with yoga." },
        { fr: "l'épuisement", en: "the exhaustion", example: "L'épuisement au travail est un vrai problème.", exampleEn: "Work exhaustion is a real problem." },
        { fr: "dépenser", en: "to spend", example: "Il dépense trop en café.", exampleEn: "He spends too much on coffee." },
        { fr: "se nourrir", en: "to eat/nourish oneself", example: "On se nourrit de produits locaux.", exampleEn: "We eat local products." },
        { fr: "l'activité physique", en: "physical activity", example: "L'activité physique réduit le stress.", exampleEn: "Physical activity reduces stress." },
        { fr: "consommer", en: "to consume", example: "On consomme trop de sucre.", exampleEn: "We consume too much sugar." },
      ],
    },
    {
      theme: "Economy & Business",
      items: [
        { fr: "l'inflation", en: "inflation", example: "L'inflation accélère.", exampleEn: "Inflation is accelerating." },
        { fr: "les taux d'intérêt", en: "interest rates", example: "Les taux d'intérêt sont élevés.", exampleEn: "Interest rates are high." },
        { fr: "le marché", en: "the market", example: "Le marché immobilier stagne.", exampleEn: "The property market is flat." },
        { fr: "la devise", en: "the currency", example: "L'euro est la devise commune.", exampleEn: "The euro is the common currency." },
        { fr: "le coût de la vie", en: "the cost of living", example: "Le coût de la vie augmente.", exampleEn: "The cost of living is rising." },
        { fr: "la consommation", en: "consumption", example: "La consommation des ménages a baissé.", exampleEn: "Household consumption has fallen." },
        { fr: "les investissements", en: "investments", example: "Les investissements étrangers progressent.", exampleEn: "Foreign investments are growing." },
        { fr: "la bourse", en: "the stock market", example: "La bourse a perdu 2% aujourd'hui.", exampleEn: "The stock market lost 2% today." },
        { fr: "la croissance", en: "growth", example: "La croissance est faible cette année.", exampleEn: "Growth is weak this year." },
        { fr: "la récession", en: "recession", example: "Une récession est possible.", exampleEn: "A recession is possible." },
      ],
    },
    {
      theme: "Social Issues",
      items: [
        { fr: "l'inégalité", en: "inequality", example: "Les inégalités se creusent.", exampleEn: "Inequalities are widening." },
        { fr: "la pauvreté", en: "poverty", example: "La pauvreté touche les zones rurales.", exampleEn: "Poverty hits rural areas." },
        { fr: "le chômage", en: "unemployment", example: "Le chômage des jeunes est élevé.", exampleEn: "Youth unemployment is high." },
        { fr: "la discrimination", en: "discrimination", example: "La discrimination est interdite.", exampleEn: "Discrimination is forbidden." },
        { fr: "l'égalité", en: "equality", example: "L'égalité des chances est un idéal.", exampleEn: "Equal opportunity is an ideal." },
        { fr: "la protection sociale", en: "social protection", example: "La protection sociale couvre les risques.", exampleEn: "Social protection covers risks." },
        { fr: "les valeurs", en: "values", example: "La solidarité est une valeur chère.", exampleEn: "Solidarity is a cherished value." },
        { fr: "la migration", en: "migration", example: "La migration internationale augmente.", exampleEn: "International migration is increasing." },
      ],
    },
    {
      theme: "Semantic Fields & Idioms",
      items: [
        { fr: "avoir du pain sur la planche", en: "have a lot of work ahead", example: "On a du pain sur la planche pour le projet.", exampleEn: "We have a lot on our plate for the project." },
        { fr: "mettre les pieds dans le plat", en: "to bring up a sensitive topic bluntly", example: "Il a mis les pieds dans le plat en parlant de ça.", exampleEn: "He bluntly brought it up." },
        { fr: "donner le coup d'envoi", en: "to kick off", example: "Le maire a donné le coup d'envoi de la fête.", exampleEn: "The mayor kicked off the festival." },
        { fr: "perdre la face", en: "to lose face", example: "Il a perdu la face devant ses collègues.", exampleEn: "He lost face in front of his colleagues." },
        { fr: "faire la une", en: "to be front-page news", example: "Cette histoire fait la une des journaux.", exampleEn: "This story is front-page news." },
        { fr: "être dans le coup", en: "to be in the know / up to date", example: "Il est toujours dans le coup.", exampleEn: "He's always up to date." },
        { fr: "faire le point", en: "to take stock", example: "On fait le point sur la situation.", exampleEn: "We take stock of the situation." },
        { fr: "le mot de passe", en: "the password", example: "Il a oublié son mot de passe.", exampleEn: "He forgot his password." },
        { fr: "faire sens", en: "to make sense", example: "Ça fait sens, vu le contexte.", exampleEn: "That makes sense, given the context." },
        { fr: "être bête", en: "to be stupid/silly", example: "C'est bête, j'ai oublié mon parapluie.", exampleEn: "It's silly, I forgot my umbrella." },
      ],
    },
  ],

  phrases: [
    { fr: "Il va sans dire que", en: "It goes without saying that", example: "Il va sans dire que je serai enchanté de vous revoir.", exampleEn: "It goes without saying that I'll be delighted to see you again." },
    { fr: "Ne pas avoir le temps de…", en: "Not to have the time to…", example: "Je n'ai pas eu le temps de répondre.", exampleEn: "I didn't have time to reply." },
    { fr: "Il reste que…", en: "The fact remains that…", example: "Il reste que nous avons besoin d'argent.", exampleEn: "The fact remains that we need money." },
    { fr: "Qu'il en soit", en: "So be it", example: "Qu'il en soit ainsi !", exampleEn: "So be it!" },
    { fr: "Ce n'est pas de mon ressort", en: "It's not within my remit", example: "La question budgétaire n'est pas de mon ressort.", exampleEn: "Budget questions aren't within my remit." },
    { fr: "Il s'agit de", en: "It's a matter of", example: "Il s'agit d'être prudent.", exampleEn: "It's a matter of being careful." },
    { fr: "à chaque jour suffit sa peine", en: "each day brings its own challenge", example: "Ne t'inquiète pas, à chaque jour suffit sa peine.", exampleEn: "Don't worry, each day brings its own challenge." },
    { fr: "Ça me rester sur l'estomac", en: "It sticks in my throat", example: "Ses remarques me sont restées sur l'estomac.", exampleEn: "His remarks stuck in my throat." },
    { fr: "Le moins qu'on puisse dire", en: "The least one can say", example: "Le moins qu'on puisse dire, c'est qu'il n'est pas content.", exampleEn: "The least one can say is that he's not happy." },
    { fr: "Vu que", en: "Given that", example: "Vu que tu es occupé, je m'occupe du rapport.", exampleEn: "Given that you're busy, I'll handle the report." },
    { fr: "en plus de ça", en: "on top of that", example: "En plus de ça, il pleut.", exampleEn: "On top of that, it's raining." },
    { fr: "toutefois", en: "however", example: "Il est sympa. Toutefois, je ne lui ferais pas confiance.", exampleEn: "He's nice. However, I wouldn't trust him." },
  ],

  pronunciation: {
    phonemes: [
      { symbol: "e/ɛ", name: "é vs è in final positions", examples: ["parlé", "parler", "père", "palet"], note: "The distinction matters: 'j'ai parlé' vs 'je parlerai'." },
      { symbol: "œ̃ vs ɛ̃", name: "un/in", examples: ["un", "vin", "brun", "brin"], note: "Minimal pairs isolate the nasal contrast." },
      { symbol: "y/u", name: "u vs ou", examples: ["tu", "tout", "lu", "loup"], note: "The dreaded /y/ vs /u/ contrast: keep lips rounded tightly for /y/." },
      { symbol: "ɛ/ɑ̃", name: "en/an vs in", examples: ["chambre", "temps", "vain"], note: "Nasal vowels must be crisp; an/a in like 'in' sound." },
      { symbol: "I/œl", name: "il/ille", examples: ["mil", "mille", "fille", "ville"], note: "The 'ill' adds a /j/ (except in 'ville', 'mille' where it lengthens: they are [vil], [mil])." },
      { symbol: "S/Z", name: "s vs z", examples: ["poisson", "poison", "cause", "corse"], note: "Voiceless vs voiced fricative; the s between vowels becomes /z/." },
    ],
    minimalPairs: [
      { a: "parlé", b: "parler" },
      { a: "été", b: "étai" },
      { a: "un", b: "in" },
      { a: "brun", b: "brin" },
      { a: "tu", b: "tout" },
      { a: "dessus", b: "dessous" },
      { a: "fille", b: "fil" },
      { a: "ville", b: "vie" },
      { a: "poisson", b: "poison" },
      { a: "cause", b: "corse" },
      { a: "chambre", b: "chan" },
      { a: "temps", b: "tant" },
    ],
    rules: [
      "The final syllable of a word tends to be stressed; French has no long or short vowels but vowel quality matters.",
      "Liaison: pronounced consonants in certain phrases (les_hommes, cinq_heures) — the s/z sound changes.",
      "Elision: the 'e' 'muet' is dropped (je → j'), pronunciation of 'je suis' becomes 'chuis' in casual speech.",
      "The /y/ of 'u' requires constant lip-rounding, not needed for 'ou'.",
      "In French there's no 'v' in 'voiced' vs both z and s; watch the voicing of s between vowels.",
    ],
  },

  listening: [
    {
      id: "b2-listen-1",
      title: "Décision stratégique",
      text: "Le conseil d'administration a annoncé hier la création d'un comité spécial pour évaluer l'opportunité d'ouvrir un nouveau site de production au Sénégal. Le directeur général a souligné que cette décision ne serait pas prise à la légère : une étude de faisabilité sera menée pendant six mois, et les partenaires africains seront consultés avant toute signature. Certains administrateurs ont exprimé des réserves sur les coûts de transport et l'instabilité politique dans la région.",
      questions: [
        {
          id: "b2-listen-1-q1",
          type: "multiple_choice",
          prompt: "Qu'est-ce que le conseil d'administration a annoncé ?",
          options: ["La fermeture d'un site", "La création d'un comité", "L'embauche de dirigeants", "Une fusion"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b2-listen-1-q2",
          type: "multiple_choice",
          prompt: "Combien de temps durera l'étude de faisabilité ?",
          options: ["Deux mois", "Six mois", "Un an", "Deux ans"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b2-listen-1-q3",
          type: "multiple_choice",
          prompt: "Quelle réserve ont exprimée certains administrateurs ?",
          options: ["Les impôts trop élevés", "Les coûts de transport et l'instabilité", "Le manque de main-d'œuvre", "La distance avec l'Europe"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
    {
      id: "b2-listen-2",
      title: "Reportage économique",
      text: "La banque centrale a relevé ses taux d'intérêt de 0,5 point ce matin pour freiner l'inflation. Cette décision, attendue par les marchés, devrait avoir un impact modéré sur l'immobilier. Toutefois, les économistes restent partagés : certains estiment qu'une hausse trop rapide risque de ralentir la croissance, tandis que d'autres considèrent qu'elle est indispensable pour protéger le pouvoir d'achat. Les consommateurs, eux, redoutent une hausse des mensualités de leurs crédits immobiliers.",
      questions: [
        {
          id: "b2-listen-2-q1",
          type: "multiple_choice",
          prompt: "Quelle est la décision de la banque centrale ?",
          options: ["Baisser ses taux", "Relever ses taux", "Garder ses taux", "Créer une monnaie"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b2-listen-2-q2",
          type: "multiple_choice",
          prompt: "Quel est le but de cette décision ?",
          options: ["Augmenter la croissance", "Freiner l'inflation", "Soutenir l'immobilier", "Financer les entreprises"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b2-listen-2-q3",
          type: "multiple_choice",
          prompt: "Que redoutent les consommateurs ?",
          options: ["La baisse des salaires", "La hausse de leurs mensualités", "La fermeture des banques", "Une taxe sur les livrets"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "b2-listen-2-q4",
          type: "multiple_choice",
          prompt: "Quel est le constat des économistes ?",
          options: ["Ils sont tous d'accord", "Ils sont partagés", "Ils refusent de commenter", "Ils se trompent"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
  ],

  reading: [
    {
      id: "b2-read-1",
      title: "L'économie de la créativité",
      text: "Les industries culturelles et créatives ne sont plus un simple secteur d'agrément. Elles représentent aujourd'hui près de 5% du PIB français et emploient plus de 700 000 personnes. La transformation numérique a bouleversé ces chaînes de production : les musées numérisent leurs collections, les éditeurs vendent des versions audio augmentées, et les festivals s'exportent à l'étranger grâce au streaming. Pour les territoires, ces industries jouent un rôle d'attractivité majeur : une ville qui investit dans sa vie culturelle attire de nouveaux habitants et des entreprises innovantes. Pour autant, la précarité reste le lot de nombreux artistes, dont les revenus fluctuent fortement d'une année sur l'autre.",
      questions: [
        {
          id: "b2-read-1-q1",
          type: "multiple_choice",
          prompt: "Quelle part du PIB français représentent les industries culturelles ?",
          options: ["2%", "5%", "10%", "15%"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-read-1-q2",
          type: "multiple_choice",
          prompt: "Quel est le rôle de ces industries pour les territoires ?",
          options: ["Un rôle fiscal", "Un rôle d'attractivité", "Un rôle politique", "Un rôle militaire"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-read-1-q3",
          type: "multiple_choice",
          prompt: "Quel problème touche de nombreux artistes ?",
          options: ["La fermeture des salles", "La précarité des revenus", "Le manque de publics", "La censure"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-read-1-q4",
          type: "multiple_choice",
          prompt: "Comment la technologie a-t-elle changé le secteur ?",
          options: ["Elle l'a ralenti", "Elle a bouleversé les chaînes de production", "Elle a supprimé les musées", "Elle a interdit le streaming"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-read-1-q5",
          type: "multiple_choice",
          prompt: "Quel verbe résume le mieux la situation du secteur ?",
          options: ["Stagnant", "En expansion", "En déclin", "Invisible"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
    {
      id: "b2-read-2",
      title: "Le livre numérique en débat",
      text: "La lecture sur écran séduit une partie croissante des lecteurs, séduits par le prix et l'accessibilité. Pourtant, une étude récente montre que la compréhension en profondeur d'un texte long reste meilleure sur papier : le format imprimé offre des repères spatiaux qui aident la mémoire. Les bibliothèques publiques, elles, se sont adaptées et multiplient les ressources en ligne, indices d'un service public qui modernise ses pratiques sans renier sa mission. Le débat, à vrai dire, n'est pas tant entre deux supports qu'entre deux manières d'aborder la culture : la consommation rapide, d'un côté, et la lenteur, de l'autre.",
      questions: [
        {
          id: "b2-read-2-q1",
          type: "multiple_choice",
          prompt: "Pourquoi les lecteurs choisissent-ils le numérique ?",
          options: ["Le confort", "Le prix et l'accessibilité", "La qualité", "L'écologie"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-read-2-q2",
          type: "multiple_choice",
          prompt: "Quel avantage le papier garde-t-il selon l'étude ?",
          options: ["Il est plus léger", "La compréhension en profondeur", "Il est plus rapide", "Il est plus moderne"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-read-2-q3",
          type: "multiple_choice",
          prompt: "Comment les bibliothèques s'adaptent-elles ?",
          options: ["Elles ferment", "Elles proposent des ressources en ligne", "Elles interdisent le numérique", "Elles augmentent leurs tarifs"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-read-2-q4",
          type: "multiple_choice",
          prompt: "Quel est le vrai débat selon l'auteur ?",
          options: ["Papier contre numérique", "Consommation rapide contre lenteur", "Bibliothèques contre librairies", "Prix contre qualité"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  writingPrompts: [
    {
      id: "b2-write-1",
      title: "Lettre de motivation",
      task: "Écrivez une lettre de motivation de 150 à 200 mots pour un poste ou une formation à l'étranger. Structurez : accroche, expérience, compétences, motivation.",
      minWords: 150,
    },
    {
      id: "b2-write-2",
      title: "Article d'opinion",
      task: "Rédigez un court article d'opinion (150 à 200 mots) : « Faut-il imposer le télétravail ? ». Utilisez des connecteurs logiques et une conclusion.",
      minWords: 150,
    },
  ],

  speakingPrompts: [
    {
      id: "b2-speaking-1",
      title: "Analyse d'un sujet",
      scenario: "Exposez et défendez votre position (3 minutes) : « Faut-il investir plus dans la culture ou la santé ? » Présentez les enjeux, les arguments pour et contre, puis votre avis pondéré.",
      hint: "Enjeu :… / La question est de savoir si… / L'une des priorités serait…",
    },
    {
      id: "b2-speaking-2",
      title: "Négociation",
      scenario: "Vous négociez avec un collègue francophone pour obtenir un week-end de repos après un projet intense. Proposez des solutions concrètes et acceptez un compromis.",
      hint: "Je comprends votre point de vue, mais… / Une solution pourrait être… / Êtes-vous d'accord pour…?",
    },
  ],

  stories: [
    {
      id: "b2-story-1",
      title: "Le dossier disparu",
      level: "B2",
      dialogue: [
        { speaker: "Narrateur", text: "Aline, contrôleuse de gestion, découvre que le dossier de recettes du mois de mars a disparu de son logiciel." },
        { speaker: "Aline", text: "C'est impossible. Le rapport existait encore hier soir." },
        { speaker: "Marc", text: "As-tu fait une sauvegarde ?" },
        { speaker: "Aline", text: "Normalement, une copie automatique se fait chaque nuit. Mais depuis la mise à jour, rien !" },
        { speaker: "Marc", text: "Il faut contacter l'informaticien. Et surtout, prévenir la direction avant l'audit." },
        { speaker: "Aline", text: "La direction ne va pas apprécier. L'audit commence lundi." },
        { speaker: "Marc", text: "Si tu l'annonces toi-même, ça prouvera ta rigueur. Le cacher serait pire." },
        { speaker: "Aline", text: "Tu as raison. Je vais préparer un point écrit clair et factuel." },
        { speaker: "Marc", text: "Et si le fichier ne se retrouve pas, on peut recalculer les données à partir des factures clients." },
        { speaker: "Aline", text: "C'est beaucoup de travail, mais c'est la seule solution fiable." },
      ],
      questions: [
        {
          id: "b2-story-1-q1",
          type: "multiple_choice",
          prompt: "Quel est le problème d'Aline ?",
          options: ["Elle a perdu son poste", "Un dossier a disparu", "Elle est malade", "Elle a une nouvelle équipe"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "b2-story-1-q2",
          type: "multiple_choice",
          prompt: "Pourquoi la situation est-elle urgente ?",
          options: ["L'audit commence lundi", "La direction arrive demain", "Le logiciel ferme", "Les clients réclament"],
          answer: 0,
          skill: "reading",
        },
        {
          id: "b2-story-1-q3",
          type: "multiple_choice",
          prompt: "Quelle solution propose Marc à la fin ?",
          options: ["Attendre la copie", "Recalculer à partir des factures", "Changer de logiciel", "Signaler la fraude"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  scenarios: [
    {
      id: "b2-scenario-renogice",
      title: "Renégocier un contrat",
      setting: "En tant que responsable achats, vous devez renégocier un contrat de fourniture avec un fournisseur francophone.",
      dialogue: [
        { speaker: "Fournisseur", text: "Je vous remercie de me recevoir. Que pensez-vous de notre proposition ?" },
        { speaker: "Acheteur", text: "La qualité est au rendez-vous, mais le prix dépasse notre budget de 15%." },
        { speaker: "Fournisseur", text: "Nos coûts ont augmenté ; le tarif reflète la matière première." },
        { speaker: "Acheteur", text: "Je comprends, mais nous avons des offres concurrentes moins chères. Que pouvez-vous nous proposer ?" },
        { speaker: "Fournisseur", text: "Je pourrais vous accorder une remise de 5% en échange d'un volume plus important." },
        { speaker: "Acheteur", text: "Et si nous signions un contrat de deux ans, serait-ce suffisant pour 10% ?" },
        { speaker: "Fournisseur", text: "10% est difficile, mais je peux discuter de 8% avec une commande minimale trimestrielle." },
        { speaker: "Acheteur", text: "C'est une possibilité. Laissez-moi une semaine pour consolider, je reviens vers vous." },
      ],
    },
  ],

  culturalNotes: [
    {
      title: "Le journalisme et l'édito",
      body: "In France, an éditorial (or « édito ») explicitly states the newspaper's position, without hiding the opinion behind neutrality. Editorials are often signed and appear on page 3 of daily papers, distinguishing fact (dépêche) from comment (analyse).",
    },
    {
      title: "L'« exception culturelle »",
      body: "France defends its cultural industries with state support, strict media rules and funding for film, music, books. This « exception culturelle » shapes French media: public channels, radio quotas on French-language music, and protections for cinema distribution.",
    },
    {
      title: "La langue des affaires",
      body: "Business French is distinct: « un fournisseur », « une remise », « un acte de vente », « la TVA ». Negotiations are formal and often written. The vous-form is standard and titles matter — a wrong turn can close the deal.",
    },
  ],

  test: {
    passingScore: 258,
    maxScore: 400,
    listening: [
      {
        id: "b2-test-l1",
        type: "multiple_choice",
        prompt: "Vous entendez : « Bien que le résultat de l'enquête ne soit pas encore officiel, les fuites indiquent une baisse significative du chômage. » — Quelle est la situation ?",
        audio: "Bien que le résultat de l'enquête ne soit pas encore officiel, les fuites indiquent une baisse significative du chômage.",
        options: ["Le chômage baisse", "Le chômage augmente", "Le chômage est stable", "On ne sait pas"],
        answer: 0,
        skill: "listening",
      },
      {
        id: "b2-test-l2",
        type: "multiple_choice",
        prompt: "Vous entendez : « Les négociations ont été suspendues jusqu'à jeudi, après que les deux parties ont rejeté la médiation. » — Pourquoi les négociations sont-elles suspendues ?",
        audio: "Les négociations ont été suspendues jusqu'à jeudi, après que les deux parties ont rejeté la médiation.",
        options: ["Parce qu'il y a un accord", "Parce que la médiation a été rejetée", "Parce que jeudi est un jour férié", "Parce que le président est absent"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "b2-test-l3",
        type: "multiple_choice",
        prompt: "Vous entendez : « Il aurait préféré qu'on lui dise la vérité plutôt que d'apprendre la nouvelle par la presse. » — Que révèle cette phrase ?",
        audio: "Il aurait préféré qu'on lui dise la vérité plutôt que d'apprendre la nouvelle par la presse.",
        options: ["Il est content de la presse", "Il est contrarié d'apprendre la nouvelle par les médias", "Il attend la suite", "Il veut écrire à la presse"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "b2-test-l4",
        type: "multiple_choice",
        prompt: "Vous entendez : « Dès que la direction aura validé le budget, nous pourrons lancer la campagne de recrutement. » — Qu'est-ce qui est nécessaire pour lancer la campagne ?",
        audio: "Dès que la direction aura validé le budget, nous pourrons lancer la campagne de recrutement.",
        options: ["Un recrutement", "La validation du budget", "Une campagne", "Un rapport"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "b2-test-l5",
        type: "multiple_choice",
        prompt: "Vous entendez : « L'entreprise n'aurait pas dû investir dans ce secteur sans études préalables. » — Quelle critique enferme cette phrase ?",
        audio: "L'entreprise n'aurait pas dû investir dans ce secteur sans études préalables.",
        options: ["Elles ont investi trop tôt dans le secteur", "Elles ont investi sans études", "Elles ont été trop prudentes", "Elles ont refusé les études"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "b2-test-l6",
        type: "multiple_choice",
        prompt: "Vous entendez : « En dépit des promesses électorales, aucune mesure n'a été prise pour protéger les zones côtières. » — Qu'est-ce qui a manqué ?",
        audio: "En dépit des promesses électorales, aucune mesure n'a été prise pour protéger les zones côtières.",
        options: ["Des mesures", "Des promesses", "Des élections", "Des zones côtières"],
        answer: 0,
        skill: "listening",
      },
    ],
    reading: [
      {
        id: "b2-test-r1",
        type: "multiple_choice",
        prompt: "« Le Festival de Liège accueille cette année vingt délégations étrangères, contre douze l'an dernier, signe de son rayonnement croissant. » — Que montre cet écart ?",
        options: ["Une baisse", "Une croissance du rayonnement", "Une stabilité", "Une fermeture"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b2-test-r2",
        type: "multiple_choice",
        prompt: "« L'hôpital a mis en place une consultation sans rendez-vous pour désengorger les urgences. » — Quel est l'objectif ?",
        options: ["Réduire le personnel", "Désengorger les urgences", "Augmenter les tarifs", "Fermer un service"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b2-test-r3",
        type: "multiple_choice",
        prompt: "« Beaucoup d'étudiants renoncent à leur inscription faute de logement abordable, alors que les résidences universitaires sont pleines. » — Qu'est-ce qui explique les renoncements ?",
        options: ["Les frais d'inscription", "Le manque de logements abordables", "La qualité des cours", "Le nombre d'étudiants"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b2-test-r4",
        type: "multiple_choice",
        prompt: "« Le projet de loi vise à simplifier les démarches administratives des entreprises, une demande récurrente des patrons. » — Quel est l'objectif du projet ?",
        options: ["Complexifier les démarches", "Simplifier les démarches", "Augmenter les impôts", "Détendre les entreprises"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b2-test-r5",
        type: "multiple_choice",
        prompt: "« Bien que le musée ait augmenté son billet d'entrée, sa fréquentation ne cesse de croître. » — Quel lien existe entre prix et fréquentation ?",
        options: ["Le prix fait baisser la fréquentation", "La fréquentation augmente malgré le prix", "Le prix est stable", "La fréquentation stagne"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "b2-test-r6",
        type: "multiple_choice",
        prompt: "« L'adjoint au maire a déclaré que le succès du marché bio dépendait avant tout du bouche-à-oreille et de la qualité des produits locaux. » — Selon lui, d'où vient principalement le succès ?",
        options: ["De la publicité", "Du bouche-à-oreille et de la qualité", "Des subventions", "Du nombre de stands"],
        answer: 1,
        skill: "reading",
      },
    ],
    writing: [
      {
        id: "b2-test-w1",
        title: "Analyse argumentée",
        prompt: "Rédigez un texte argumenté de 170 à 220 mots : « La croissance économique doit-elle primer sur la protection de l'environnement ? » Structurez et utilisez des connecteurs.",
        minWords: 170,
      },
      {
        id: "b2-test-w2",
        title: "Rapport",
        prompt: "Écrivez un petit rapport de 150 à 200 mots à votre direction ayant pour sujet : le recours croissant au télétravail dans votre équipe. Présentez les constats, les avantages et les risques, et proposez une recommandation.",
        minWords: 150,
      },
    ],
    speaking: [
      {
        id: "b2-test-s1",
        title: "Exposé",
        prompt: "Préparez et présentez un exposé de 3 minutes : « L'importance de la lecture chez les jeunes ». Structurez : introduction, deux parties, conclusion.",
        hint: "Mon exposé portera sur… / D'une part… / En conclusion…",
      },
      {
        id: "b2-test-s2",
        title: "Débat",
        prompt: "Défendez votre position dès la question : « Faut-il rendre les transports en commun gratuits ? ». Répondez à au moins une objection.",
        hint: "À mon sens… / Cependant, on pourrait objecter que… / Je maintiens que…",
      },
    ],
    pronunciation: [
      { id: "b2-test-p1", type: "pronunciation", prompt: "Prononcez ce mot :", word: "le gouvernement", ipa: "/lə ɡu.vɛʁ.nə.mɑ̃/", skill: "pronunciation" },
      { id: "b2-test-p2", type: "pronunciation", prompt: "Prononcez ce mot :", word: "souhait", ipa: "/swɛ/", skill: "pronunciation" },
      { id: "b2-test-p3", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Il se peut qu'il pleuve demain", ipa: "/il sə pø kil plœv dəmɛ̃/", skill: "pronunciation" },
      { id: "b2-test-p4", type: "pronunciation", prompt: "Prononcez ce mot :", word: "détruire", ipa: "/de.tʁɥiʁ/", skill: "pronunciation" },
      { id: "b2-test-p5", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Bien qu'il soit fatigué, il travaille", ipa: "/bjɛ̃ kil swa fatige il tʁavaj/", skill: "pronunciation" },
    ],
  },
};