import type { LevelContent } from "@/lib/types";

export const c1: LevelContent = {
  level: "C1",

  grammar: [
    {
      id: "c1-subjonctif-avance",
      title: "Le Subjonctif Avancé",
      explanation:
        "Beyond simple emotion/necessity: subjunctive after conjunctions (avant que, à condition que, pour que, bien que, de peur que), after superlative+que (le meilleur qui soit), and in certain hypotheses (au cas où + conditionnel, not subjunctive). Also: after 'le fait que' the subjunctive is common. Connaître le mode du subjonctif passé is required for C1.",
      examples: [
        { fr: "Nous sortirons avant qu'il ne fasse nuit.", en: "We'll go out before it gets dark." },
        { fr: "C'est le meilleur roman que je connaisse.", en: "It's the best novel I know." },
        { fr: "Je l'accompagne à condition qu'il soit prudent.", en: "I'll go with him provided he's careful." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Advanced Subjunctive",
      exercises: [
        {
          id: "c1-subj-1",
          type: "multiple_choice",
          prompt: "Complete: Il sortira ___ le temps soit mauvais.",
          options: ["bien que", "parce que", "étant donné que", "car"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "c1-subj-2",
          type: "multiple_choice",
          prompt: "Which sentence requires the subjunctive?",
          options: ["Il est certain qu'il viendra.", "Avant qu'il parte, préviens-moi.", "Je crois qu'il est parti.", "Il me semble qu'il a raison."],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c1-subj-3",
          type: "fill_in_blank",
          prompt: "Complete: Je le ferai à condition qu'il ___ d'accord. (être)",
          answer: "soit",
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-antecedent-syntaxe",
      title: "Syntaxe: l'antéposition",
      explanation:
        "Putting an element of the sentence before the main clause to emphasize it or to create a literary effect. Qu'elle soit belle, oui ! / En matière de cuisine, il excelle. Such structures (bien que the subjunctive be used) give a C1 level of accuracy.",
      examples: [
        { fr: "Quant à ses intentions, on les ignore.", en: "As for his intentions, they're unknown." },
        { fr: "Préférer la campagne, c'est ce qu'elle fait.", en: "Preferring the countryside — that's what she does." },
        { fr: "Ce qui l'inquiète, c'est le coût du projet.", en: "What worries him is the cost of the project." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Cleft sentences",
      exercises: [
        {
          id: "c1-ante-1",
          type: "multiple_choice",
          prompt: "Complete: ___ l'inquiète, c'est le coût.",
          options: ["Ce qui", "Ce que", "Ce dont", "Ce pourquoi"],
          answer: 1,
          skill: "grammar",
          explain: "'what worries him' = cost is object → ce que.",
        },
        {
          id: "c1-ante-2",
          type: "multiple_choice",
          prompt: "Complete: C'est elle ___ a proposé cette solution.",
          options: ["qui", "que", "où", "dont"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-inversion",
      title: "L'Inversion Complexe",
      explanation:
        "Formal inversion in questions and after certain adverbials: Pourquoi est-il parti ? / Que pense-t-elle ? / À peine avait-il fini qu'il se couchait. Inversion is preferred in formal written French and after adverbs bien que short: Aussi bien que. Remember the 't' euphonic in inversion: A-t-il compris ?",
      examples: [
        { fr: "Pourquoi n'avez-vous pas réservé ?", en: "Why didn't you book?" },
        { fr: "À peine était-il rentré que le téléphone sonna.", en: "He had hardly come home when the phone rang." },
        { fr: "Où pouvez-vous être demain ?", en: "Where can you be tomorrow?" },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Inversion",
      exercises: [
        {
          id: "c1-inv-1",
          type: "multiple_choice",
          prompt: "Rewrite correctly: « Pourquoi il est parti ? » → Pourquoi ___ ?",
          options: ["est-il parti", "il est parti", "part-il est", "a-t-il parti"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "c1-inv-2",
          type: "multiple_choice",
          prompt: "Complete with inversion: À peine ___ qu'il pleuvait.",
          options: ["nous étions sortis", "sortions-nous", "est-on sorti", "étions-nous sortis"],
          answer: 3,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-participe-passe",
      title: "Accord du Participe Passé",
      explanation:
        "The most grammatical-bug prone rule: past participle agrees with preceding direct object (la pomme que j'ai mangée, les livres que j'ai lus), but NOT with an indirect object (la fille à qui j'ai parlé). With en it does not agree. With pronominal verbs, agree with the reflexive pronoun if it's the direct object: elle s'est levée vs elle s'est lavé les mains (la pomme que elle...). Attention to être verbs: agree with subject.",
      examples: [
        { fr: "Les chansons qu'elle a chantées sont connues.", en: "The songs she sang are famous." },
        { fr: "Elle s'est lavé les mains. (les mains = direct object)", en: "She washed her hands." },
        { fr: "Elles se sont levées tôt.", en: "They got up early." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Past participle agreement",
      exercises: [
        {
          id: "c1-accord-1",
          type: "multiple_choice",
          prompt: "Complete: Les fleurs qu'elle a ___ (acheter).",
          options: ["acheté", "achetée", "achetées", "acheter"],
          answer: 2,
          skill: "grammar",
        },
        {
          id: "c1-accord-2",
          type: "multiple_choice",
          prompt: "Complete: Elle s'est ___ (laver) les mains.",
          options: ["lavée", "lavé", "lavés", "lavées"],
          answer: 1,
          skill: "grammar",
          explain: "direct object = les mains → no agreement.",
        },
      ],
    },
    {
      id: "c1-literary-tenses",
      title: "Temps Littéraires: Passé Simple",
      explanation:
        "Understanding (not producing) the passé simple is key at C1: il parla, elle partit, nous mangeâmes. Recognizable in novels and histories. It replaces the passé composé in narration. Note the -âmes, -îmes, -ûmes endings and the value of memorizing frequency stems (être → fut, avoir → eut, venir → vint, faire → fit, dire → dit).",
      examples: [
        { fr: "Il ouvrit la porte et resta figé.", en: "He opened the door and stood frozen." },
        { fr: "Elle écrivit une lettre à son père.", en: "She wrote a letter to her father." },
        { fr: "Ils partirent au petit matin.", en: "They left at dawn." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Passé simple",
      exercises: [
        {
          id: "c1-lit-1",
          type: "multiple_choice",
          prompt: "Which form is the passé simple of 'être' (il)?",
          options: ["fut", "était", "serait", "a été"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "c1-lit-2",
          type: "multiple_choice",
          prompt: "In novels, the narration of past events is usually in:",
          options: ["le présent", "le passé simple", "le futur antérieur", "le conditionnel"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-gerondif-et-participe",
      title: "Le Participe Présent et le Gérondif",
      explanation:
        "Participe présent (chantant, aimant) functions as an adjective or verbal: Elle est charmante (adjective) / Frappez-moi, s'il vous plaît... Note the difference: en + participe présent = gérondif, expressing simultaneous action or manner. As a verbal adjective may be invariable (Elle, charmant les enfants). Watch agreement: 'des rue charmantes' agrees, but 'des fleurs endormant'... never as a gérondif doesn't agree.",
      examples: [
        { fr: "En traversant la rue, il a été renversé.", en: "While crossing the street, he was run over." },
        { fr: "Ayant fini ses devoirs, elle est sortie.", en: "Having finished her homework, she went out." },
        { fr: "Les élèves attentifs, le professeur continue.", en: "With the students attentive, the teacher continues." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, Participe présent",
      exercises: [
        {
          id: "c1-gerpart-1",
          type: "multiple_choice",
          prompt: "Complete: ___ (avoir) faim, il a acheté une baguette.",
          options: ["En ayant", "Ayant", "Avant", "Avent"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c1-gerpart-2",
          type: "multiple_choice",
          prompt: "Which is a verbal (gérondif) usage?",
          options: ["Il chante en travaillant.", "C'est une chanteuse.", "La chante ralentit.", "Il pleut souvent ici."],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-conditionnel-reportage",
      title: "Le Conditionnel dans les Médias",
      explanation:
        "The journalist's conditional: Les deux parties auraient trouvé un accord (reported, unconfirmed). Unverified info is presented with avoir au conditionnel to warn the reader that it isn't confirmed. Perfect for C1-level reading of the news.",
      examples: [
        { fr: "L'usine serait vendue à un groupe chinois.", en: "The factory is said to be sold to a Chinese group." },
        { fr: "Le ministre aurait démissionné ce matin.", en: "The minister is said to have resigned this morning." },
        { fr: "Des témoins auraient aperçu une fumée.", en: "Witnesses supposedly saw smoke." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Journalistic conditional",
      exercises: [
        {
          id: "c1-cond-media-1",
          type: "multiple_choice",
          prompt: "What nuance does the conditional add in: « Le PDG aurait quitté l'entreprise » ?",
          options: ["It's certain", "It's unconfirmed", "It's a wish", "It's a question"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c1-cond-media-2",
          type: "fill_in_blank",
          prompt: "Report conditionally: On dit que l'acteur est malade. → L'acteur ___ malade. (être)",
          answer: "serait",
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-pronoms-toniques",
      title: "Pronoms Compléments Avancés",
      explanation:
        "Beyond direct/indirect: y (there/to it), en (of it/from/some), and the combination word order. Combine pronouns: le+lui, le+y, la+leur, les+y, en must come last (il m'en donne). Double object: je le lui ai donné. At C1 you must handle these automatically.",
      examples: [
        { fr: "Je pense à mon avenir. — J'y pense.", en: "I'm thinking about my future. — I'm thinking about it." },
        { fr: "Tu veux du café ? — Oui, j'en veux.", en: "Do you want some coffee? — Yes, I do (want some)." },
        { fr: "Tu le lui as dit ? — Oui, je le lui ai dit.", en: "Did you tell him it? — Yes, I told him it." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Pronouns",
      exercises: [
        {
          id: "c1-pro-1",
          type: "multiple_choice",
          prompt: "Replace 'à ce restaurant': Nous allons à ce restaurant → Nous __ allons.",
          options: ["y", "en", "le", "lui"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "c1-pro-2",
          type: "multiple_choice",
          prompt: "Replace: Je parle au professeur → Je ___ parle.",
          options: ["le", "lui", "y", "en"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c1-pro-3",
          type: "fill_in_blank",
          prompt: "Order the pronouns: Je ___ ___ donne. (le, lui) — type two words",
          answer: "le lui",
          answerVariants: ["le lui"],
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-varietes-registres",
      title: "Registres de Langue",
      explanation:
        "Distinguish soutenu (literary: se retirer, demeurer), courant (standard: partir, habiter), familier (colloquial: se barrer, crasher, bouffer) and argot (slang). Choosing the right register is a C1 social skill: never use familier in a job interview, don't use soutenu on social media.",
      examples: [
        { fr: "Je me retire (soutenu) / Je pars (courant) / Je me tire (familier).", en: "I'm leaving." },
        { fr: "Il demeure à Lyon (soutenu) / Il habite à Lyon (courant).", en: "He lives in Lyon." },
        { fr: "C'est un film excellent (courant) / C'est un bon film (familier).", en: "It's an excellent film." },
      ],
      bookChapters: "Complete French All-in-One — Vocabulary, Registers",
      exercises: [
        {
          id: "c1-registre-1",
          type: "multiple_choice",
          prompt: "Which word is 'soutenu' (formal) for 'to die'?",
          options: ["mourir", "trépasser", "casser", "finir"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c1-registre-2",
          type: "multiple_choice",
          prompt: "In a job interview, which register should you use?",
          options: ["Familier", "Courant", "Argotique", "Poétique"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c1-idioms-avances",
      title: "Idiomes et Expressions Figées",
      explanation:
        "C1 learners must taste metaphorical French: tomber sur (to come across), ce n'est pas la mer à boire (it's not rocket science), aérer (to give breathing room). Effective language includes lots of verb + preposition and cultural idioms. Understand them in context and use them sparingly but correctly.",
      examples: [
        { fr: "Je suis tombé sur un article passionnant.", en: "I came across a fascinating article." },
        { fr: "C'est la cerise sur le gâteau !", en: "It's the cherry on the cake!" },
        { fr: "Poser une colle à quelqu'un", en: "To ask someone a tricky question." },
      ],
      bookChapters: "Complete French All-in-One — Vocabulary, Idioms",
      exercises: [
        {
          id: "c1-idiom-1",
          type: "multiple_choice",
          prompt: "« Poser une colle » signifie :",
          options: ["Coller un papier", "Poser une question difficile", "Recoller un objet", "Donner un rendez-vous"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c1-idiom-2",
          type: "multiple_choice",
          prompt: "« Ce n'est pas la mer à boire » signifie :",
          options: ["C'est très difficile", "Ce n'est pas si difficile", "C'est impossible", "C'est interdit"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
  ],

  vocabulary: [
    {
      theme: "Legal & Formal",
      items: [
        { fr: "l'ordonnance", en: "the decree/short order", example: "Le juge a rendu une ordonnance.", exampleEn: "The judge issued a court order." },
        { fr: "la jurisprudence", en: "case law", example: "La jurisprudence évolue.", exampleEn: "Case law evolves." },
        { fr: "le procès", en: "the trial", example: "Le procès a duré trois mois.", exampleEn: "The trial lasted three months." },
        { fr: "l'avocat", en: "the lawyer", example: "L'avocat plaidera demain.", exampleEn: "The lawyer will plead tomorrow." },
        { fr: "le témoin", en: "the witness", example: "Le témoin a été interrogé.", exampleEn: "The witness was questioned." },
        { fr: "la preuve", en: "the evidence", example: "Les preuves sont solides.", exampleEn: "The evidence is solid." },
        { fr: "l'audience", en: "the court hearing", example: "L'audience est publique.", exampleEn: "The hearing is public." },
        { fr: "condamner", en: "to convict", example: "Il a été condamné à trois ans.", exampleEn: "He was sentenced to three years." },
        { fr: "acquitter", en: "to acquit", example: "Elle a été acquittée.", exampleEn: "She was acquitted." },
        { fr: "le plaignant", en: "the plaintiff", example: "Le plaignant réclame des dommages.", exampleEn: "The plaintiff claims damages." },
      ],
    },
    {
      theme: "Science & Research",
      items: [
        { fr: "la recherche", en: "research", example: "La recherche avance lentement.", exampleEn: "Research advances slowly." },
        { fr: "l'expérience", en: "the experiment", example: "L'expérience a été reproduite.", exampleEn: "The experiment was reproduced." },
        { fr: "les données", en: "the data", example: "Les données sont fiables.", exampleEn: "The data are reliable." },
        { fr: "la théorie", en: "the theory", example: "La théorie reste à prouver.", exampleEn: "The theory still has to be proved." },
        { fr: "la conclusion", en: "the conclusion", example: "La conclusion est prudente.", exampleEn: "The conclusion is cautious." },
        { fr: "l'hypothèse", en: "the hypothesis", example: "L'hypothèse a été vérifiée.", exampleEn: "The hypothesis was verified." },
        { fr: "le chercheur", en: "the researcher", example: "Le chercheur publie dans une revue.", exampleEn: "The researcher publishes in a journal." },
        { fr: "la découverte", en: "the discovery", example: "La découverte est majeure.", exampleEn: "The discovery is major." },
        { fr: "l'article scientifique", en: "the scientific article", example: "L'article est écrit en anglais.", exampleEn: "The article is written in English." },
        { fr: "le laboratoire", en: "the laboratory", example: "Le laboratoire est équipé de robots.", exampleEn: "The laboratory is equipped with robots." },
      ],
    },
    {
      theme: "Philosophy & Reasoning",
      items: [
        { fr: "le raisonnement", en: "reasoning", example: "Le raisonnement est logique.", exampleEn: "The reasoning is logical." },
        { fr: "l'argument", en: "the argument", example: "L'argument convainc le public.", exampleEn: "The argument convinces the public." },
        { fr: "la réfutation", en: "refutation", example: "La réfutation est documentée.", exampleEn: "The refutation is documented." },
        { fr: "la prémisse", en: "the premise", example: "La prémisse de départ est fausse.", exampleEn: "The starting premise is false." },
        { fr: "le jugement", en: "the judgment", example: "Le jugement est hâtif.", exampleEn: "The judgment is rash." },
        { fr: "la nuance", en: "the nuance", example: "Il faut ajouter une nuance.", exampleEn: "A nuance must be added." },
        { fr: "soutenir", en: "to maintain/argue", example: "Je soutiens le contraire.", exampleEn: "I maintain the opposite." },
        { fr: "la thèse", en: "the thesis", example: "La thèse est défendable.", exampleEn: "The thesis is defensible." },
        { fr: "l'objection", en: "the objection", example: "L'objection porte sur le coût.", exampleEn: "The objection concerns the cost." },
        { fr: "la démonstration", en: "the demonstration", example: "La démonstration est limpide.", exampleEn: "The demonstration is crystal-clear." },
      ],
    },
    {
      theme: "Art Criticism",
      items: [
        { fr: "l'analyse", en: "the analysis", example: "L'analyse du tableau est fine.", exampleEn: "The analysis of the painting is fine." },
        { fr: "le point de vue", en: "the point of view", example: "Le point de vue du critique est original.", exampleEn: "The critic's point of view is original." },
        { fr: "l'interprétation", en: "the interpretation", example: "Plusieurs interprétations sont possibles.", exampleEn: "Several interpretations are possible." },
        { fr: "l'œuvre", en: "the work", example: "Une œuvre majeure du XXe siècle.", exampleEn: "A major 20th century work." },
        { fr: "la nature morte", en: "the still life", example: "La nature morte est un genre ancien.", exampleEn: "Still life is an old genre." },
        { fr: "la palette", en: "the palette", example: "La palette est sombre.", exampleEn: "The palette is dark." },
        { fr: "le courant", en: "the movement", example: "Le cubisme est un courant majeur.", exampleEn: "Cubism is a major movement." },
        { fr: "la composition", en: "the composition", example: "La composition est équilibrée.", exampleEn: "The composition is balanced." },
        { fr: "la technique", en: "the technique", example: "La technique de la fresque est exigeante.", exampleEn: "Fresco technique is demanding." },
        { fr: "dénoncer", en: "to denounce/criticize", example: "L'œuvre dénonce la guerre.", exampleEn: "The work denounces war." },
      ],
    },
    {
      theme: "Social Media & Debate",
      items: [
        { fr: "la polémique", en: "the controversy", example: "La polémique enflamme les réseaux.", exampleEn: "The controversy is blowing up online." },
        { fr: "déclencher", en: "to trigger", example: "Sa déclaration a déclenché un débat.", exampleEn: "His statement triggered a debate." },
        { fr: "la réputation", en: "the reputation", example: "La réputation du journal est en jeu.", exampleEn: "The newspaper's reputation is at stake." },
        { fr: "avoir raison / tort", en: "to be right / wrong", example: "Elle a raison de protester.", exampleEn: "She's right to protest." },
        { fr: "argumenter", en: "to argue/build an argument", example: "Il argumente avec précision.", exampleEn: "He argues precisely." },
        { fr: "le hashtag", en: "the hashtag", example: "Le hashtag est devenu viral.", exampleEn: "The hashtag went viral." },
        { fr: "le démenti", en: "the denial/denial statement", example: "Le démenti est arrivé trop tard.", exampleEn: "The denial came too late." },
        { fr: "conspuer", en: "to boo", example: "L'orateur a été conspué.", exampleEn: "The speaker was booed." },
        { fr: "exprimer des réserves", en: "to express reservations", example: "J'exprime des réserves sur ce plan.", exampleEn: "I express reservations about this plan." },
        { fr: "étayer", en: "to back up (arguments)", example: "Il étaye ses propos.", exampleEn: "He backs up his claims." },
      ],
    },
    {
      theme: "Financial Markets & Africa/Belgium/Quebec French",
      items: [
        { fr: "la bourse / le CAC", en: "the stock exchange / the French index", example: "Le CAC a clôturé en hausse.", exampleEn: "The CAC closed higher." },
        { fr: "le dividende", en: "the dividend", example: "Le dividende est versé chaque année.", exampleEn: "The dividend is paid each year." },
        { fr: "les obligations", en: "bonds", example: "Les obligations rapportent moins.", exampleEn: "Bonds yield less." },
        { fr: "la fuite des capitaux", en: "capital flight", example: "La fuite des capitaux s'accélère.", exampleEn: "Capital flight is accelerating." },
        { fr: "la déréglementation", en: "deregulation", example: "La déréglementation a changé le secteur.", exampleEn: "Deregulation changed the sector." },
        { fr: "le franc CFA", en: "the CFA franc", example: "Le franc CFA est utilisé en Afrique de l'Ouest.", exampleEn: "The CFA franc is used in West Africa." },
        { fr: "la francophonie", en: "la Francophonie", example: "La francophonie unit de nombreux pays.", exampleEn: "La Francophonie unites many countries." },
        { fr: "la cohabitation", en: "power-sharing/cohabitation", example: "La cohabitation est fréquente en France.", exampleEn: "Cohabitation is frequent in France." },
        { fr: "l'accord de Schengen", en: "Schengen agreement", example: "L'espace Schengen facilite les déplacements.", exampleEn: "The Schengen area makes travel easier." },
        { fr: "la banque centrale", en: "the central bank", example: "La banque centrale doit rester indépendante.", exampleEn: "The central bank must remain independent." },
      ],
    },
    {
      theme: "Environment & Climate Negotiations",
      items: [
        { fr: "le compromis", en: "the compromise", example: "Les négociations cherchent un compromis.", exampleEn: "The negotiations seek a compromise." },
        { fr: "la transition écologique", en: "ecological transition", example: "La transition exige des financements.", exampleEn: "The transition requires funding." },
        { fr: "les émissions", en: "emissions", example: "Les émissions de CO2 doivent baisser.", exampleEn: "CO2 emissions must drop." },
        { fr: "la cop21", en: "COP21", example: "L'accord de Paris a été adopté à la COP21.", exampleEn: "The Paris agreement was adopted at COP21." },
        { fr: "le rapport", en: "the report", example: "Le rapport prévoit une hausse de 1,5°C.", exampleEn: "The report predicts a 1.5°C rise." },
        { fr: "engager", en: "to commit (to)", example: "Les pays se sont engagés à réduire leurs émissions.", exampleEn: "Countries committed to reduce emissions." },
        { fr: "la contrainte", en: "the constraint", example: "La contrainte budgétaire limite l'action.", exampleEn: "The budget constraint limits action." },
        { fr: "le rendez-vous de Glasgow", en: "the Glasgow summit", example: "Le rendez-vous de Glasgow était crucial.", exampleEn: "The Glasgow summit was crucial." },
        { fr: "la subvention", en: "the subsidy", example: "Les subventions aux énergies fossiles restent élevées.", exampleEn: "Fossil-fuel subsidies remain high." },
        { fr: "l'écoresponsabilité", en: "environmental responsibility", example: "L'écoresponsabilité guide nos achats.", exampleEn: "Environmental responsibility guides our purchases." },
      ],
    },
    {
      theme: "Formal Writing Phrases",
      items: [
        { fr: "il convient de", en: "it is appropriate to", example: "Il convient de rappeler les faits.", exampleEn: "It is appropriate to recall the facts." },
        { fr: "il serait souhaitable de", en: "it would be desirable to", example: "Il serait souhaitable de consulter les experts.", exampleEn: "It would be desirable to consult the experts." },
        { fr: "en l'occurrence", en: "in this case", example: "En l'occurrence, le choix est simple.", exampleEn: "In this case, the choice is simple." },
        { fr: "sous réserve de", en: "subject to", example: "Sous réserve de l'accord du conseil.", exampleEn: "Subject to the council's agreement." },
        { fr: "à titre exceptionnel", en: "exceptionally", example: "À titre exceptionnel, nous prolongeons l'offre.", exampleEn: "As an exception, we're extending the offer." },
        { fr: "dans la mesure où", en: "insofar as", example: "Nous vous suivons dans la mesure où c'est utile.", exampleEn: "We'll follow you insofar as it's useful." },
        { fr: "ne serait-ce que", en: "if only / merely", example: "Ne serait-ce qu'une minute.", exampleEn: "If only for a minute." },
        { fr: "pour autant", en: "however", example: "Pour autant, je ne suis pas convaincu.", exampleEn: "However, I'm not convinced." },
        { fr: "la suite donnée", en: "the follow-up", example: "Quelle suite donne-on à cette demande ?", exampleEn: "What follow-up is given to this request?" },
        { fr: "donner suite à", en: "to act on", example: "Nous donnerons suite à votre réclamation.", exampleEn: "We will act on your complaint." },
      ],
    },
  ],

  phrases: [
    { fr: "Il n'empêche que", en: "all the same / still", example: "Il n'empêche que c'est une belle initiative.", exampleEn: "All the same, it's a nice initiative." },
    { fr: "pour ainsi dire", en: "so to speak", example: "C'est, pour ainsi dire, terminé.", exampleEn: "It's, so to speak, over." },
    { fr: "en définitive", en: "ultimately", example: "En définitive, tout s'est bien passé.", exampleEn: "Ultimately, all went well." },
    { fr: "à vrai dire", en: "to tell the truth", example: "À vrai dire, je n'y crois pas.", exampleEn: "To tell the truth, I don't believe it." },
    { fr: "de surcroît", en: "furthermore", example: "De surcroît, il est très compétent.", exampleEn: "Furthermore, he's very competent." },
    { fr: "quoi qu'il en soit", en: "be that as it may", example: "Quoi qu'il en soit, nous devons avancer.", exampleEn: "Be that as it may, we must move forward." },
    { fr: "à la lumière de", en: "in light of", example: "À la lumière de ces faits…", exampleEn: "In light of these facts…" },
    { fr: "faire état de", en: "to report/mention", example: "Le rapport fait état de progrès.", exampleEn: "The report mentions progress." },
    { fr: "sans commune mesure", en: "disproportionate", example: "Le R is sans commune mesure avec le problème.", exampleEn: "The response is disproportionate to the problem." },
    { fr: "d'ores et déjà", en: "from now on/immediately", example: "Nous vous confirmons d'ores et déjà notre participation.", exampleEn: "We confirm our participation from now on." },
    { fr: "en aucun cas", en: "in no case", example: "En aucun cas, il ne faut céder.", exampleEn: "In no case should we give in." },
    { fr: "à l'aune de", en: "by the yardstick of", example: "À l'aune des résultats, l'expérience réussit.", exampleEn: "By the measure of the results, the experiment succeeds." },
  ],

  pronunciation: {
    phonemes: [
      { symbol: "détente", name: "Syllable timing (isochronie)", examples: ["la République", "le gouvernement", "l'économie"], note: "French syllables are nearly equal-timed; stress usually falls on the final syllable of the phrase group." },
      { symbol: "liaison", name: "Liaison (advanced rules)", examples: ["les_hommes", "quand_on", "un_ami"], note: "Compulsory in set phrases and between verb+pronoun; optional after certain words; wrong liaisons are a C1++ differentiator." },
      { symbol: "elision", name: "Elision & 'e' caduc", examples: ["je ne sais pas → ch'pas", "petite → p'tite"], note: "In connected speech the schwa drops freely; recognize the patterns when listening to natives." },
      { symbol: "e/ɛ", name: "The mid vowels e/ɛ in open syllables", examples: ["j'étais (ɛ)", "été (e)", "fait (ɛ)"], note: "In metropolitan French 'ai' is /ɛ/ only in open syllable before orthographic m/n? — accent-fixed dialects vary; listen." },
      { symbol: "s/z", name: "Voiced vs voiceless fricatives", examples: ["poisson / poison", "zone / sono"], note: "Confusions change words — target perfect voicing in the s/z set." },
      { symbol: "intonation", name: "Intonation & phrasing", examples: ["Je ne sais pas (finale descendante)", "Tu viens ? (montante)"], note: "Statement vs question depends on rising intonation in informal French." },
    ],
    minimalPairs: [
      { a: "les", b: "lai" },
      { a: "je", b: "jus" },
      { a: "poisson", b: "poison" },
      { a: "zone", b: "sonne" },
      { a: "un", b: "in" },
      { a: "brun", b: "brin" },
      { a: "dessus", b: "dessous" },
      { a: "temps", b: "tant" },
      { a: "fait", b: "fé" },
      { a: "j'étais", b: "été" },
      { a: "bientôt", b: "binet" },
      { a: "hotesse", b: "hôtel" },
    ],
    rules: [
      "'s' between two vowels = /z/; rule holds even in compound words (maison, désaccord).",
      "'e' muet at the end of a word is dropped in normal speed but may be heard in close cautious speech.",
      "Final mute consonants take their sound value in liaison only.",
      "The schwa 'e' in 'cette', 'le', is realized /œ/, not English 'uh'.",
      "Intonation is the only signal of yes/no questions in informal speech — keep the final rise.",
    ],
  },

  listening: [
    {
      id: "c1-listen-1",
      title: "Interview économique",
      text: "Journaliste : Madame la Ministre, votre projet de réforme des retraites suscite de vives réactions. N'êtes-vous pas inquiète ? — Ministre : Il est vrai que les syndicats expriment un mécontentement légitime. Néanmoins, cette réforme est indispensable : si l'on ne réagit pas maintenant, le système ne sera plus viable en 2040. Nous avons laissé de côté des mesures trop brutales, comme le relèvement automatique de l'âge légal, au profit d'un accord progressif. — Journaliste : Certains critiques parlent d'un recul. Quelle est votre réponse ? — Ministre : Je comprends qu'ils puissent être déçus. Mais l'accord que nous avons bâti préserve les droits les plus fragiles et, d'une certaine manière, sécurise l'avenir de tous. Le débat, je l'assume, doit rester ouvert.",
      questions: [
        {
          id: "c1-listen-1-q1",
          type: "multiple_choice",
          prompt: "Quelle est la réaction des syndicats selon la Ministre ?",
          options: ["Ils soutiennent la réforme", "Ils expriment un mécontentement", "Ils refusent toute discussion", "Ils sont indifférents"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c1-listen-1-q2",
          type: "multiple_choice",
          prompt: "Selon la Ministre, que deviendrait le système sans réforme ?",
          options: ["Il serait plus juste", "Il ne serait plus viable en 2040", "Il resterait stable", "Il serait privatisé"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c1-listen-1-q3",
          type: "multiple_choice",
          prompt: "Quelle mesure ont-ils évitée ?",
          options: ["L'accord progressif", "Le relèvement automatique de l'âge légal", "La préservation des droits", "Le débat public"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c1-listen-1-q4",
          type: "multiple_choice",
          prompt: "Comment la Ministre justifie-t-elle le projet ?",
          options: ["Il préserve les droits les plus fragiles", "Il augmente les retraites", "Il réduit les impôts", "Il supprime les syndicats"],
          answer: 0,
          skill: "listening",
        },
      ],
    },
    {
      id: "c1-listen-2",
      title: "Conférence sur la culture",
      text: "Permettez-moi de vous dire que la culture n'est pas un luxe, mais une nécessité vitale. J'entends souvent dire que la culture coûte cher ; en réalité, c'est l'ignorance qui coûte cher. Chaque euro investi dans un musée, une bibliothèque ou une école de musique se traduit par des gains en santé publique, en cohésion sociale et en compétitivité économique. Des études menées dans plusieurs villes européennes le confirment : les quartiers qui investissent dans la culture voient leur taux de délinquance baisser et leurs commerces prospérer. Il ne s'agit pas, bien sûr, de remplacer les besoins de base par la culture, mais de comprendre qu'ils sont liés. En somme, je vous invite à considérer la culture non comme une dépense, mais comme un investissement rentable pour l'avenir.",
      questions: [
        {
          id: "c1-listen-2-q1",
          type: "multiple_choice",
          prompt: "Quel est le propos principal de l'intervenant ?",
          options: ["La culture coûte trop cher", "La culture est un investissement rentable", "La culture doit être gratuite", "La culture est un luxe"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c1-listen-2-q2",
          type: "multiple_choice",
          prompt: "Selon les études citées, que constate-t-on dans les quartiers qui investissent dans la culture ?",
          options: ["Plus de délinquance", "Moins de délinquance et des commerces prospères", "Une hausse des impôts", "Une baisse du tourisme"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c1-listen-2-q3",
          type: "multiple_choice",
          prompt: "Que dit l'intervenant sur l'ignorance ?",
          options: ["Elle est gratuite", "Elle coûte cher", "Elle est inévitable", "Elle est un mythe"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c1-listen-2-q4",
          type: "multiple_choice",
          prompt: "Quelle nuance apporte-t-il à la fin ?",
          options: ["Il faut supprimer les besoins de base", "Il ne faut pas remplacer les besoins de base par la culture", "Il faut financer uniquement la culture", "Il faut choisir entre les deux"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
  ],

  reading: [
    {
      id: "c1-read-1",
      title: "La valeur du temps",
      text: "La modernité a fait du temps une marchandise : on le « gagne », on le « perd », on le « gaspille ». Cette métaphore marchande n'est pas innocente. Elle transforme l'existence en une course où chaque minute non rentabilisée apparaît comme un échec. Pourtant, les sociétés où la notion de temps semble la plus souple — que l'on songe aux cultures méditerranéennes ou à certaines pratiques africaines — montrent que la lenteur n'est pas synonyme d'oisiveté, mais peut être une forme de sagesse : on y consacre du temps aux relations, à l'attention, à la parole échangée. Retrouver le goût du temps long, ce serait peut-être se réapproprier ce que le progrès technique n'a jamais pu produire : une présence au monde.",
      questions: [
        {
          id: "c1-read-1-q1",
          type: "multiple_choice",
          prompt: "Selon l'auteur, comment la modernité traite-t-elle le temps ?",
          options: ["Comme un cadeau", "Comme une marchandise", "Comme un sujet", "Comme une illusion"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-read-1-q2",
          type: "multiple_choice",
          prompt: "Quel sens peut avoir la lenteur dans certaines cultures ?",
          options: ["L'oisiveté", "Une forme de sagesse", "Le retard", "Le refus du travail"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-read-1-q3",
          type: "multiple_choice",
          prompt: "Qu'est-ce que le progrès technique n'a jamais produit ?",
          options: ["La technologie", "Une présence au monde", "La rapidité", "Des marchandises"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-read-1-q4",
          type: "multiple_choice",
          prompt: "Le registre de ce texte est plutôt :",
          options: ["Familier", "Soutenu", "Administratif", "Publicitaire"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-read-1-q5",
          type: "multiple_choice",
          prompt: "Le mot « rentabilisée » dans le texte signifie :",
          options: ["Profitable", "Rapide", "Gratuite", "Juste"],
          answer: 0,
          skill: "reading",
        },
      ],
    },
    {
      id: "c1-read-2",
      title: "La diplomatie francophone",
      text: "La Francophonie est souvent méconnue dans l'opinion publique, réduite à une simple fête de la langue. Pourtant, elle constitue un espace géopolitique singulier : 88 États et gouvernements y sont représentés, de l'Afrique de l'Ouest au Québec, de la Belgique à l'Océan indien. Cet espace partage des enjeux concrets — enseignement, numérique, paix, économie — et pèse dans la diplomatie multilatérale, notamment au sein de l'ONU et des organisations de coopération. Certes, la Francophonie affronte des contradictions : certaines de ses membres pratiquent des politiques en décalage avec ses valeurs. Il n'empêche que sa force repose sur un trésor intangible : une langue qui, malgré la domination de l'anglais, continue d'être un instrument de création, de dialogue et de contre-pouvoir.",
      questions: [
        {
          id: "c1-read-2-q1",
          type: "multiple_choice",
          prompt: "Comment la Francophonie est-elle souvent perçue ?",
          options: ["Comme un espace géopolitique", "Comme une simple fête de la langue", "Comme une coalition militaire", "Comme une union économique"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-read-2-q2",
          type: "multiple_choice",
          prompt: "Combien d'États et gouvernements la Francophonie représente-t-elle ?",
          options: ["48", "68", "88", "108"],
          answer: 2,
          skill: "reading",
        },
        {
          id: "c1-read-2-q3",
          type: "multiple_choice",
          prompt: "Quelle contradiction est évoquée ?",
          options: ["Des pays qui quittent", "Des politiques en décalage avec ses valeurs", "Une langue en déclin", "Un déficit de financement"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-read-2-q4",
          type: "multiple_choice",
          prompt: "Quel est le rôle de la langue selon l'auteur ?",
          options: ["Un simple moyen de communication", "Un instrument de création et de dialogue", "Un outil commercial", "Un symbole national"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  writingPrompts: [
    {
      id: "c1-write-1",
      title: "Synthèse argumentative",
      task: "Rédigez une synthèse de 250 à 300 mots sur le thème : « Faut-il encadrer les réseaux sociaux ? » Présentez les arguments pour et contre, nuancez, et donnez votre position.",
      minWords: 250,
    },
    {
      id: "c1-write-2",
      title: "Essai critique",
      task: "Écrivez un essai de 250 à 300 mots sur une œuvre culturelle (livre, film, exposition) de votre choix. Analysez le thème, la forme, le message, et justifiez votre jugement.",
      minWords: 250,
    },
  ],

  speakingPrompts: [
    {
      id: "c1-speaking-1",
      title: "Exposé structuré",
      scenario: "Présentez un exposé de 4 minutes : « Le rôle de la culture dans l'identité nationale ». Structurez clairement et utilisez un registre soutenu.",
      hint: "Je souhaite aborder… / En premier lieu… / Il convient de préciser que…",
    },
    {
      id: "c1-speaking-2",
      title: "Débat d'idées",
      scenario: "Défendez votre position avec puissance : « La technologie menace-t-elle notre capacité d'attention ? » Anticipez deux objections et répondez-y.",
      hint: "Il me semble essentiel de souligner… / Vous pourriez objecter que…, mais…",
    },
  ],

  stories: [
    {
      id: "c1-story-1",
      title: "La lettre anonyme",
      level: "C1",
      dialogue: [
        { speaker: "Narrateur", text: "Un matin d'avril, Georges, archiviste à la mairie, reçut une enveloppe sans tampon. À l'intérieur, une lettre anonyme et un plan." },
        { speaker: "Georges", text: "Quelqu'un cherche quelque chose. Mais quoi ?" },
        { speaker: "Claudine", text: "Ce plan ressemble au vieux parc des Capucins. Un trésor ?" },
        { speaker: "Georges", text: "Plutôt un piège. Réfléchis : ce bâtiment a brûlé en 1827. Les registres paroissiaux ont été sauvés par un prêtre nommé Aubry." },
        { speaker: "Claudine", text: "Et si la lettre était une demande de restitution ? Les archives d'une famille exilée ?" },
        { speaker: "Georges", text: "Tiens, au dos du plan, une date : 1923. Une frontière a été déplacée cette année-là." },
        { speaker: "Narrateur", text: "La lettre disait : « Ce que votre ville conserve n'est pas ce qu'elle croit conserver. Sous l'ancienne chapelle repose la mémoire de ma famille. »" },
        { speaker: "Claudine", text: "Alors c'est une affaire de mémoire, pas de trésor. Il faut ouvrir le dossier officiel." },
        { speaker: "Georges", text: "Et si je me trompais, je briserais sa confiance. Il faut être certain." },
      ],
      questions: [
        {
          id: "c1-story-1-q1",
          type: "multiple_choice",
          prompt: "Quelle est la découverte initiale de Georges ?",
          options: ["Un trésor", "Une lettre anonyme et un plan", "Un vieux livre", "Une carte de ville"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-story-1-q2",
          type: "multiple_choice",
          prompt: "À quoi ressemble le plan selon Claudine ?",
          options: ["Au vieux parc des Capucins", "À la gare", "À un château", "À un champ"],
          answer: 0,
          skill: "reading",
        },
        {
          id: "c1-story-1-q3",
          type: "multiple_choice",
          prompt: "Que souhaite apparemment la famille anonyme ?",
          options: ["De l'argent", "Restituer la mémoire de sa famille", "Acheter le bâtiment", "Signaler un vol"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c1-story-1-q4",
          type: "multiple_choice",
          prompt: "Quelle est la crainte finale de Georges ?",
          options: ["La perte de son poste", "Briser la confiance", "Une panne", "Le coût"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  scenarios: [
    {
      id: "c1-scenario-emission",
      title: "Émission de débat",
      setting: "Vous êtes invité(e) dans une émission de radio francophone pour débattre d'un sujet : « Faut-il rendre les réseaux sociaux responsables des contenus diffusés ? »",
      dialogue: [
        { speaker: "Animateur", text: "Bienvenue à tous. Docteur, vous représentez une association de défense des droits numériques." },
        { speaker: "Invité 1", text: "Merci. Il me semble qu'imposer la responsabilité aux plateformes est illusoire sans transparence totale sur leurs algorithmes." },
        { speaker: "Animateur", text: "Et vous, Madame la juriste ?" },
        { speaker: "Invité 2", text: "Une responsabilité juridique est possible, à condition qu'elle soit proportionnée et qu'il existe des autorités de contrôle indépendantes." },
        { speaker: "Invité 1", text: "Le vrai enjeu, c'est l'éducation des publics. La censure étatique est un risque pire que la désinformation." },
        { speaker: "Invité 2", text: "Mais ne pas agir, c'est laisser les algorithmes décider à notre place sans aucune supervision." },
        { speaker: "Animateur", text: "Où se situe le compromis acceptable, selon vous ?" },
        { speaker: "Invité 1", text: "Une régulation fondée sur la transparence, pas sur l'interdiction." },
        { speaker: "Invité 2", text: "Je partage cette idée, à condition que les associations puissent auditer les plateformes." },
      ],
    },
  ],

  culturalNotes: [
    {
      title: "L'art oratoire français",
      body: "French oratory values structure, clarity and antithesis. « Je veux », « il faut », elegant inversions, and the famous double negation-chême (pas, pas) are the tools of debate. Success in a French argument is not being louder, but more precise.",
    },
    {
      title: "Les Essais et l'Académie",
      body: "From Montaigne to the Académie française, France has a tradition of the essay and of refining language. The Académie (founded 1635) still debates grammar and vocabulary — a living link to the past in a digital world.",
    },
    {
      title: "La langue comme pouvoir",
      body: "In the Francophonie, French is often a language of access to education and power, but also a site of resistance to the dominance of English. African writers, Québécois singers and Belgian filmmakers use it to assert distinctive identities.",
    },
  ],

  test: {
    passingScore: 260,
    maxScore: 400,
    listening: [
      {
        id: "c1-test-l1",
        type: "multiple_choice",
        prompt: "Vous entendez : « Le gouvernement n'envisage pas, à ce stade, de légiférer — il s'interroge néanmoins sur la nécessité d'un cadre éthique. » — Que peut-on dire ?",
        audio: "Le gouvernement n'envisage pas, à ce stade, de légiférer — il s'interroge néanmoins sur la nécessité d'un cadre éthique.",
        options: ["Il légifère", "Il réfléchit à un cadre éthique", "Il a refusé", "Il a adopté une loi"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c1-test-l2",
        type: "multiple_choice",
        prompt: "Vous entendez : « Bien que le climat des affaires reste morose, certaines PME parviennent à s'étendre à l'export. » — Quelle est la situation ?",
        audio: "Bien que le climat des affaires reste morose, certaines PME parviennent à s'étendre à l'export.",
        options: ["Toutes les PME exportent", "Certaines PME réussissent à exporter", "Le climat est excellent", "Les PME se replient"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c1-test-l3",
        type: "multiple_choice",
        prompt: "Vous entendez : « Il aurait été préférable de consulter les riverains avant le lancement des travaux. » — Que déplore l'auteur ?",
        audio: "Il aurait été préférable de consulter les riverains avant le lancement des travaux.",
        options: ["Le coût des travaux", "L'absence de consultation", "Le retard des travaux", "Le choix des entreprises"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c1-test-l4",
        type: "multiple_choice",
        prompt: "Vous entendez : « Quoi qu'en disent les sondages, l'opinion réelle ne se réduit jamais à quelques points de pourcentage. » — Que signifie cette phrase ?",
        audio: "Quoi qu'en disent les sondages, l'opinion réelle ne se réduit jamais à quelques points de pourcentage.",
        options: ["Les sondages sont parfaits", "L'opinion est plus complexe que les sondages", "Les sondages sont interdits", "L'opinion change vite"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c1-test-l5",
        type: "multiple_choice",
        prompt: "Vous entendez : « À peine le rapport publié, la direction a réuni les équipes pour en atténuer la portée. » — Qu'a fait la direction ?",
        audio: "À peine le rapport publié, la direction a réuni les équipes pour en atténuer la portée.",
        options: ["Analysé les chiffres", "Minimisé les conclusions", "Annulé le rapport", "Félicité les équipes"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c1-test-l6",
        type: "multiple_choice",
        prompt: "Vous entendez : « Sans doute le succès de la mesure dépend-il du soutien des régions, dont dépend également son financement. » — De quoi dépend le financement ?",
        audio: "Sans doute le succès de la mesure dépend-il du soutien des régions, dont dépend également son financement.",
        options: ["Du gouvernement", "Des régions", "Des citoyens", "Des entreprises"],
        answer: 1,
        skill: "listening",
      },
    ],
    reading: [
      {
        id: "c1-test-r1",
        type: "multiple_choice",
        prompt: "« La réforme, bien qu'annoncée à grand renfort de communication, demeure profondément ambivalente dans ses objectifs réels. » — Le mot « ambivalente » signifie :",
        options: ["Claire", "Contradictoire", "Sans importance", "Efficace"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c1-test-r2",
        type: "multiple_choice",
        prompt: "« Les chercheurs s'accordent : sans une réduction drastique des émissions, les objectifs de l'accord de Paris resteront lettre morte. » — « lettre morte » signifie :",
        options: ["Réalisée", "Inapplicable", "Secrète", "Traduite"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c1-test-r3",
        type: "multiple_choice",
        prompt: "« Loin de se limiter à un simple enjeu technique, la question de l'eau engage la souveraineté des peuples. » — Que signifie cette phrase ?",
        options: ["La question est purement technique", "La question dépasse la technique et touche la souveraineté", "La question est résolue", "La question concerne la marine"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c1-test-r4",
        type: "multiple_choice",
        prompt: "« Face aux critiques, l'acteur n'a eu de cesse de renvoyer les détracteurs à leurs propres contradictions. » — L'acteur :",
        options: ["A ignoré les critiques", "A constamment répondu aux critiques", "A quitté le débat", "A menacé ses détracteurs"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c1-test-r5",
        type: "multiple_choice",
        prompt: "« Loin d'être le fruit du hasard, cette réussite résulte d'un long travail de convictions. » — Quel est le sens ?",
        options: ["La réussite est fortuite", "La réussite est le fruit du travail", "La réussite est impossible", "La réussite est une illusion"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c1-test-r6",
        type: "multiple_choice",
        prompt: "« Quoi qu'il advienne, le festival maintiendra sa programmation, comme il le fait depuis vingt ans. » — Le festival :",
        options: ["Annulera sûrement", "Maintiendra malgré tout", "Mettra en doute", "Changera de lieu"],
        answer: 1,
        skill: "reading",
      },
    ],
    writing: [
      {
        id: "c1-test-w1",
        title: "Rapport argumenté",
        prompt: "Rédigez un rapport de 250 à 300 mots sur : « L'impact de l'intelligence artificielle sur les métiers de demain ». Présentez les bénéfices, les risques et une recommandation.",
        minWords: 250,
      },
      {
        id: "c1-test-w2",
        title: "Essai",
        prompt: "Écrivez un essai (250 à 300 mots) répondant à la question : « Que gagne-t-on à apprendre une langue étrangère ? » Adoptez un registre soutenu.",
        minWords: 250,
      },
    ],
    speaking: [
      {
        id: "c1-test-s1",
        title: "Synthèse orale",
        prompt: "Présentez en 4 minutes les thèses suivantes (contre et pour) : « Les écrans menacent l'école ». Reformulez, opposez, nuancez, concluez.",
        hint: "L'une des thèses soutient que… / En revanche… / En définitive…",
      },
      {
        id: "c1-test-s2",
        title: "Débat animé",
        prompt: "Défendez vigoureusement votre position : « Faut-il instaurer un revenu universel ? » Vous devez convaincre un interlocuteur sceptique.",
        hint: "Je vous répondrais que… / Ce n'est pas tant une question de coût que de… ",
      },
    ],
    pronunciation: [
      { id: "c1-test-p1", type: "pronunciation", prompt: "Prononcez ce mot :", word: "connaissance", ipa: "/kɔ.nɛ.sɑ̃s/", skill: "pronunciation" },
      { id: "c1-test-p2", type: "pronunciation", prompt: "Prononcez ce mot :", word: "l'hésitation", ipa: "/le.zi.ta.sjɔ̃/", skill: "pronunciation" },
      { id: "c1-test-p3", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Quoi qu'il en soit, nous avancerons", ipa: "/kwa kil ɑ̃ swa nu zavɑ̃sʁɔ̃/", skill: "pronunciation" },
      { id: "c1-test-p4", type: "pronunciation", prompt: "Prononcez ce mot :", word: "extraordinaire", ipa: "/ɛkstʁaɔʁdinɛʁ/", skill: "pronunciation" },
      { id: "c1-test-p5", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Je n'en suis point certain", ipa: "/ʒə nɑ̃ sɥi pwɛ̃ sɛʁtɛ̃/", skill: "pronunciation" },
    ],
  },
};