import type { LevelContent } from "@/lib/types";

export const c2: LevelContent = {
  level: "C2",

  grammar: [
    {
      id: "c2-temps-litteraires",
      title: "Temps Littéraires et Modes (approfondis)",
      explanation:
        "Mastery of French means commanding the full system: passé simple (narration), passé antérieur (after à peine, dès que in literary past), subjonctif imparfait/plus-que-parfait (formal written style: qu'il parlât, qu'il eût parlé), and the conditionnel passé 2e forme (eût été). These tenses are no longer spoken but appear in literary contexts, official documents and high-register writing.",
      examples: [
        { fr: "Quand il eut fini, il sortit.", en: "When he had finished, he went out." },
        { fr: "Il aurait été préférable qu'il vînt.", en: "It would have been preferable for him to come." },
        { fr: "À peine fût-il parti que le téléphone sonna.", en: "Hardly had he left when the phone rang." },
      ],
      bookChapters: "Complete French All-in-One — Verb Section, All literary tenses",
      exercises: [
        {
          id: "c2-lit-1",
          type: "multiple_choice",
          prompt: "Passé antérieur of 'finir' (il):",
          options: ["il finit", "il eût fini", "il avait fini", "il finissait"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c2-lit-2",
          type: "multiple_choice",
          prompt: "Subjonctif imparfait of 'être' (qu'il):",
          options: ["qu'il soit", "qu'il fût", "qu'il était", "qu'il est"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c2-accent-tonique",
      title: "L'Accent Tonique et la Phrase",
      explanation:
        "In French, the tonic accent falls on the last syllable of a rhythmic group. Mastery involves placing pauses and emphasis naturally, using stress for contrast (MOI, je préfère...) while keeping the melody of the sentence. This affects comprehension and pronunciation of long, complex sentences.",
      examples: [
        { fr: "Moi, je ne suis pas d'accord.", en: "As for me, I don't agree." },
        { fr: "C'est tout à fait vrai.", en: "That's absolutely true." },
        { fr: "Je vous demande de réfléchir.", en: "I ask you to think about it." },
      ],
      bookChapters: "Complete French All-in-One — Pronunciation",
      exercises: [
        {
          id: "c2-accent-1",
          type: "multiple_choice",
          prompt: "Où se place l'accent tonique dans une phrase française ?",
          options: ["Sur la première syllabe", "Sur la dernière syllabe du groupe rythmique", "Sur la deuxième syllabe", "Sur chaque mot"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c2-accent-2",
          type: "multiple_choice",
          prompt: "Dans la phrase « C'est absolument formidable », l'accent tombe sur :",
          options: ["C'est", "absolument", "formidable", "C'est et formidable"],
          answer: 3,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c2-details-accord",
      title: "Accords Subtils",
      explanation:
        "Subtle agreements that trip up even natives: the participle before 'en' (je leur en ai parlé → no agreement), the 'le' neuter (les lettres que j'ai dû écrire vs le fait qu'il a été), agreement in the statement of $strick origin, the 'certains/certaines' that stay in singular, invariability of 'ci-joint' in some positions (ci-joint la copie vs la copie ci-jointe).",
      examples: [
        { fr: "Des lettres que j'ai dû écrire.", en: "The letters I had to write." },
        { fr: "Je leur en ai parlé longuement.", en: "I spoke to them about it at length." },
        { fr: "Tout est permis, sauf les actes.", en: "Everything is allowed, except the acts." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Subtle agreements",
      exercises: [
        {
          id: "c2-subtle-1",
          type: "multiple_choice",
          prompt: "Complete: Elle leur en a ___ (parler).",
          options: ["parlé", "parlée", "parlés", "parlées"],
          answer: 0,
          skill: "grammar",
          explain: "en before the participle → no agreement.",
        },
        {
          id: "c2-subtle-2",
          type: "multiple_choice",
          prompt: "In standard writing, « ci-joint » is invariable here: « ___ votre facture. »",
          options: ["Ci-jointe", "Ci-joint", "Ci-joints", "Ci-jointes"],
          answer: 1,
          skill: "grammar",
          explain: "placed before the noun, ci-joint is invariable.",
        },
      ],
    },
    {
      id: "c2-punchlines-idiomes",
      title: "Idiomes et Stéréotypes Culturels",
      explanation:
        "At C2 the true challenge is comprehension of idioms, proverbs, allusions and cultural references: tomber dans le panneau, être au bout du rouleau, avoir plusieurs cordes à son arc, les carottes sont cuites. Understand them from context, don't translate literally, and use them with caution (register matters).",
      examples: [
        { fr: "Il est au bout du rouleau.", en: "He's exhausted / at the end of his rope." },
        { fr: "Les carottes sont cuites !", en: "It's all over / no turning back!" },
        { fr: "Elle a plus d'une corde à son arc.", en: "She has more than one string to her bow." },
      ],
      bookChapters: "Complete French All-in-One — Vocabulary, Idioms",
      exercises: [
        {
          id: "c2-idio-1",
          type: "multiple_choice",
          prompt: "« Tomber dans le panneau » signifie :",
          options: ["Se faire piéger", "Tomber dans l'escalier", "Gagner facilement", "Réussir"],
          answer: 0,
          skill: "grammar",
        },
        {
          id: "c2-idio-2",
          type: "multiple_choice",
          prompt: "« Avoir plusieurs cordes à son arc » signifie :",
          options: ["Être musicien", "Avoir plusieurs talents/options", "Perdre son temps", "Être têtu"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c2-modification-nominal",
      title: "Néologie et Mots Composés",
      explanation:
        "French enriches itself with neologisms (courriel→e-mail officiel, numérique, écoconduite), compound words (portefeuille, gratte-ciel, avant-projet) and borrowed anglicisms deflected (le week-end, le football, le challenge). Mastering word-formation and recognizing new coinages marks true fluency.",
      examples: [
        { fr: "Le courriel a remplacé le courrier traditionnel.", en: "Email replaced traditional mail." },
        { fr: "Un gratte-ciel domine la ville.", en: "A skyscraper dominates the city." },
        { fr: "Pratiquons l'écoconduite.", en: "Let's practice eco-driving." },
      ],
      bookChapters: "Complete French All-in-One — Vocabulary, Word formation",
      exercises: [
        {
          id: "c2-neo-1",
          type: "multiple_choice",
          prompt: "Quel est le terme français officiel pour 'e-mail' ?",
          options: ["le mél", "le courriel", "le mail", "le messager"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c2-neo-2",
          type: "multiple_choice",
          prompt: "Quel mot est un anglicisme naturalisé ?",
          options: ["le gratte-ciel", "le week-end", "l'écoconduite", "le courriel"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c2-registres-soutenu",
      title: "Le Registre Soutenu",
      explanation:
        "Full command of the soutenu register: subjonctif tenses, inversion, nominalization, vocabulary like quoique, néanmoins, à l'encontre de, préalablement. Writing official letters, administrative summaries, speeches. Distinguish it from the courant and familier registers.",
      examples: [
        { fr: "Néanmoins, il demeure que cette solution s'avère satisfaisante.", en: "Nevertheless, this solution proves satisfactory." },
        { fr: "Il vous sera loisible de consulter le dossier.", en: "You will be free to consult the file." },
        { fr: "En conséquence, nous vous invitons à…", en: "Consequently, we invite you to…" },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Formal register",
      exercises: [
        {
          id: "c2-sout-1",
          type: "multiple_choice",
          prompt: "Quel mot est le plus 'soutenu' pour dire « cependant » ?",
          options: ["mais", "cependant", "néanmoins", "par contre"],
          answer: 2,
          skill: "grammar",
          explain: "'néanmoins' is the most formal.",
        },
        {
          id: "c2-sout-2",
          type: "multiple_choice",
          prompt: "Formal for « pouvoir »: Il vous ___ loisible de partir.",
          options: ["est", "sera", "fait", "laisse"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c2-concordance-temps",
      title: "Concordance des Temps dans le Récit",
      explanation:
        "Matching time systems across the narrative: present-based vs past-based sequence of tenses. Quand il était jeune, il vivait à Québec (imparfait), il avait déjà visité l'Europe (plus-que-parfait), puis il est parti en Afrique (passé composé). Sustained narration without register breaks is a C2 signature.",
      examples: [
        { fr: "Il regarda par la fenêtre : la ville, qu'il avait tant aimée, semblait étrangère.", en: "He looked out the window: the city, which he had loved so much, seemed foreign." },
        { fr: "Après qu'il eut signé le contrat, il se sentit soulagé.", en: "After he had signed the contract, he felt relieved." },
        { fr: "Si j'avais su, je ne serais pas venu.", en: "If I had known, I wouldn't have come." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Seq. of tenses",
      exercises: [
        {
          id: "c2-conc-1",
          type: "multiple_choice",
          prompt: "Complete: Après qu'elle ___ (avoir) terminé son discours, elle s'assit.",
          options: ["a", "eut", "avait", "eût eu"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c2-conc-2",
          type: "multiple_choice",
          prompt: "In a past narrative, the 'background' is usually in:",
          options: ["le passé composé", "l'imparfait", "le futur", "le présent"],
          answer: 1,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c2-verbes-precieuses",
      title: "Verbes Précieux et Registres",
      explanation:
        "Some verbs carry precise, elevated meanings: s'accouder (to lean on elbows), déambuler (to stroll), réitérer (to repeat), prescrire/indiquer (distinguish!), s'enquérir (to inquire). Also distinguish: mettre fin à, aboutir à, déboucher sur. Precision of meaning is the heart of C2.",
      examples: [
        { fr: "Les visiteurs déambulaient dans le parc.", en: "The visitors strolled through the park." },
        { fr: "Je me suis enquis de sa santé.", en: "I inquired about his health." },
        { fr: "Cette tension aboutira à un conflit.", en: "This tension will lead to a conflict." },
      ],
      bookChapters: "Complete French All-in-One — Vocabulary",
      exercises: [
        {
          id: "c2-prec-1",
          type: "multiple_choice",
          prompt: "« Déambuler » signifie :",
          options: ["Courir", "Se promener tranquillement", "Travailler", "Écrire"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c2-prec-2",
          type: "multiple_choice",
          prompt: "Quel verbe convient : « Cette réunion a ___ un accord » ?",
          options: ["abouti à", "consisté en", "revenu à", "finalisé"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
    {
      id: "c2-structures-rhetoriques",
      title: "Structures Rhétoriques",
      explanation:
        "C2 oral and written argument uses rhetorical devices: l'anaphore (répétition en début de phrase), l'antithèse, la question rhétorique, la concession suivie d'une restriction (certes… mais), la gradation. These give your expression persuasive depth.",
      examples: [
        { fr: "Certes, les temps sont durs. Mais ils ne l'ont jamais été autrement.", en: "True, the times are hard. But they've never been otherwise." },
        { fr: "Qui n'a jamais rêvé d'une vie meilleure ?", en: "Who has never dreamed of a better life?" },
        { fr: "Nous le devons à nos enfants : à leur avenir, à leur sécurité, à leur liberté.", en: "We owe it to our children: to their future, their safety, their freedom." },
      ],
      bookChapters: "Complete French All-in-One — Grammar Review, Rhetoric",
      exercises: [
        {
          id: "c2-rhet-1",
          type: "multiple_choice",
          prompt: "La répétition du même mot en début de phrases successives s'appelle :",
          options: ["L'ellipse", "L'anaphore", "La litote", "L'hyperbole"],
          answer: 1,
          skill: "grammar",
        },
        {
          id: "c2-rhet-2",
          type: "multiple_choice",
          prompt: "« Certes… mais… » est un outil de :",
          options: ["La concession", "La cause", "L'hypothèse", "La coordination"],
          answer: 0,
          skill: "grammar",
        },
      ],
    },
  ],

  vocabulary: [
    {
      theme: "Semantique & Précision",
      items: [
        { fr: "s'avérer", en: "to prove to be, to turn out", example: "La tâche s'avère complexe.", exampleEn: "The task proves complex." },
        { fr: "déceler", en: "to detect/discern", example: "On décèle une méfiance croissante.", exampleEn: "A growing distrust can be detected." },
        { fr: "réfuter", en: "to refute", example: "Il a réfuté tous les arguments.", exampleEn: "He refuted all the arguments." },
        { fr: "soupeser", en: "to weigh up", example: "Il faut soupeser toutes les options.", exampleEn: "We must weigh up all options." },
        { fr: "paré à", en: "prepared/ready for", example: "Nous sommes parés à toute éventualité.", exampleEn: "We are prepared for any eventuality." },
        { fr: "concourir à", en: "to contribute to", example: "Ces efforts concourent au même but.", exampleEn: "These efforts contribute to the same goal." },
        { fr: "émaner de", en: "to emanate from", example: "Ce rapport émane d'un groupe d'experts.", exampleEn: "This report emanates from an expert group." },
        { fr: "la conjecture", en: "the conjecture", example: "Cette théorie repose sur des conjectures.", exampleEn: "This theory rests on conjectures." },
        { fr: "l'anicroche", en: "the trivial glitch", example: "Un petit anicroche, rien de grave.", exampleEn: "A small glitch, nothing serious." },
        { fr: "la cohésion", en: "the cohesion", example: "La cohésion sociale est menacée.", exampleEn: "Social cohesion is threatened." },
      ],
    },
    {
      theme: "Administrative French",
      items: [
        { fr: "informer par écrit", en: "to inform in writing", example: "Il vous appartient d'informer l'administration par écrit.", exampleEn: "You must inform the administration in writing." },
        { fr: "la pièce justificative", en: "the supporting document", example: "Joignez les pièces justificatives.", exampleEn: "Attach the supporting documents." },
        { fr: "notifier", en: "to notify", example: "La décision sera notifiée sous huit jours.", exampleEn: "The decision will be notified within eight days." },
        { fr: "être réputé", en: "to be deemed", example: "Le silence est réputé acceptation.", exampleEn: "Silence is deemed acceptance." },
        { fr: "la délibération", en: "the deliberation", example: "La délibération est publique.", exampleEn: "The deliberation is public." },
        { fr: "la saisine", en: "the referral/submission", example: "La saisine du tribunal est obligatoire.", exampleEn: "The referral to the court is mandatory." },
        { fr: "exhumer", en: "to unearth/bring to light", example: "On a exhumé des archives oubliées.", exampleEn: "Forgotten archives were unearthed." },
        { fr: "la clause", en: "the clause", example: "La clause de confidentialité est stricte.", exampleEn: "The confidentiality clause is strict." },
        { fr: "le dispositif", en: "the scheme/mechanism", example: "Le dispositif d'aide est simplifié.", exampleEn: "The aid scheme is simplified." },
        { fr: "donner suite", en: "to follow up/act on", example: "Nous donnerons suite à votre requête.", exampleEn: "We will act on your request." },
      ],
    },
    {
      theme: "Culture & Arts",
      items: [
        { fr: "le metteur en scène", en: "the director", example: "Le metteur en scène a signé une adaptation fidèle.", exampleEn: "The director signed a faithful adaptation." },
        { fr: "la scénographie", en: "the scenography", example: "La scénographie est épurée.", exampleEn: "The scenography is minimalist." },
        { fr: "l'œuvre d'art", en: "the work of art", example: "L'œuvre d'art dialogue avec l'espace.", exampleEn: "The artwork dialogues with the space." },
        { fr: "la critique", en: "the review/criticism", example: "La critique a salué le spectacle.", exampleEn: "The critics praised the show." },
        { fr: "le patrimoine", en: "the heritage", example: "Le patrimoine est un atout touristique.", exampleEn: "Heritage is a tourist asset." },
        { fr: "l'inauguration", en: "the inauguration", example: "L'inauguration attire de nombreux visiteurs.", exampleEn: "The inauguration attracts many visitors." },
        { fr: "la rétrospective", en: "the retrospective", example: "Une rétrospective est consacrée au peintre.", exampleEn: "A retrospective is devoted to the painter." },
        { fr: "se produire", en: "to perform", example: "Le chanteur se produit à Paris.", exampleEn: "The singer performs in Paris." },
        { fr: "le vernissage", en: "the private viewing", example: "Le vernissage a lieu en soirée.", exampleEn: "The private viewing takes place in the evening." },
        { fr: "l'exposition itinérante", en: "the touring exhibition", example: "L'exposition itinérante fait le tour du pays.", exampleEn: "The touring exhibition travels the country." },
      ],
    },
    {
      theme: "Relations Internationales",
      items: [
        { fr: "la souveraineté", en: "sovereignty", example: "La souveraineté alimentaire est un enjeu.", exampleEn: "Food sovereignty is an issue." },
        { fr: "la médiation", en: "the mediation", example: "La médiation a évité le pire.", exampleEn: "The mediation avoided the worst." },
        { fr: "l'ingérence", en: "interference", example: "L'ingérence étrangère est dénoncée.", exampleEn: "Foreign interference is denounced." },
        { fr: "la ratification", en: "the ratification", example: "La ratification du traité est en cours.", exampleEn: "Ratification of the treaty is under way." },
        { fr: "la résolution", en: "the resolution", example: "La résolution a été adoptée à l'unanimité.", exampleEn: "The resolution was adopted unanimously." },
        { fr: "se retirer de", en: "to withdraw from", example: "Le pays s'est retiré de l'alliance.", exampleEn: "The country withdrew from the alliance." },
        { fr: "la tutelle", en: "the trusteeship/guardianship", example: "Le territoire est sous tutelle internationale.", exampleEn: "The territory is under international trusteeship." },
        { fr: "le sommet", en: "the summit", example: "Le sommet a réuni les chefs d'État.", exampleEn: "The summit brought together the heads of state." },
        { fr: "la coopération", en: "cooperation", example: "La coopération scientifique se renforce.", exampleEn: "Scientific cooperation is strengthening." },
        { fr: "le blocus", en: "the blockade", example: "Le blocus économique a été levé.", exampleEn: "The economic blockade was lifted." },
      ],
    },
    {
      theme: "Speech & Writing Devices",
      items: [
        { fr: "l'emphase", en: "the emphasis", example: "L'emphase de son intonation marquait la phrase.", exampleEn: "The emphasis of his intonation stressed the sentence." },
        { fr: "la litote", en: "the litotes", example: "« Ce n'est pas mal » est une litote.", exampleEn: "'Not bad' is a litotes." },
        { fr: "l'hyperbole", en: "the hyperbole", example: "L'hyperbole sert à exagérer.", exampleEn: "Hyperbole serves to exaggerate." },
        { fr: "la métaphore", en: "the metaphor", example: "La métaphore éclaire le propos.", exampleEn: "The metaphor clarifies the point." },
        { fr: "l'antithèse", en: "the antithesis", example: "L'antithèse oppose deux idées.", exampleEn: "Antithesis opposes two ideas." },
        { fr: "l'ellipse", en: "the ellipse/omission", example: "L'ellipse rend le style vivant.", exampleEn: "Ellipsis makes the style lively." },
        { fr: "la périphrase", en: "the periphrasis", example: "La périphrase évite la répétition.", exampleEn: "Periphrasis avoids repetition." },
        { fr: "l'euphémisme", en: "the euphemism", example: "« Une issue fatale » est un euphémisme.", exampleEn: "'A fatal outcome' is a euphemism." },
        { fr: "l'ironie", en: "the irony", example: "L'ironie suppose un décodage.", exampleEn: "Irony requires decoding." },
        { fr: "le registre", en: "the register", example: "Le registre soutenu exige le subjonctif.", exampleEn: "The formal register requires the subjunctive." },
      ],
    },
    {
      theme: "Espaces francophones",
      items: [
        { fr: "le Québec", en: "Quebec", example: "Le Québec a sa propre culture.", exampleEn: "Quebec has its own culture." },
        { fr: "la Wallonie", en: "Wallonia", example: "La Wallonie est la région francophone de Belgique.", exampleEn: "Wallonia is the French-speaking region of Belgium." },
        { fr: "la Suisse romande", en: "French-speaking Switzerland", example: "Genève appartient à la Suisse romande.", exampleEn: "Geneva belongs to French-speaking Switzerland." },
        { fr: "les Québécismes", en: "Quebec expressions", example: "« Une tuque » est un québécisme.", exampleEn: "'Tuque' is a Quebec expression." },
        { fr: "les belgicismes", en: "Belgian expressions", example: "« Septante » est un belgicisme/helvétisme.", exampleEn: "'Septante' is a Belgian/Swiss expression." },
        { fr: "l'accent", en: "the accent", example: "L'accent québécois est plus nasal.", exampleEn: "The Quebec accent is more nasal." },
        { fr: "la francophonie africaine", en: "African Francophonie", example: "Le français est une langue de travail en Afrique.", exampleEn: "French is a working language in Africa." },
        { fr: "le Maghreb", en: "the Maghreb", example: "Le français est langue d'enseignement au Maghreb.", exampleEn: "French is a language of instruction in the Maghreb." },
        { fr: "les Antilles", en: "the French West Indies", example: "La Guadeloupe et la Martinique sont des Antilles.", exampleEn: "Guadeloupe and Martinique are French West Indies." },
        { fr: "le créole", en: "the creole", example: "Le créole coexiste avec le français.", exampleEn: "Creole coexists with French." },
      ],
    },
    {
      theme: "Register & Nuance",
      items: [
        { fr: "anciennement / précédemment", en: "formerly / previously", example: "Précédemment, les règles étaient plus souples.", exampleEn: "Previously, the rules were more flexible." },
        { fr: "a fortiori", en: "even more so", example: "A fortiori, si les prix augmentent…", exampleEn: "Even more so if prices rise…" },
        { fr: "ne serait-ce que pour", en: "if only to", example: "Venez, ne serait-ce que pour une heure.", exampleEn: "Come, if only for an hour." },
        { fr: "à bon escient", en: "wisely / judiciously", example: "Il use de l'argent à bon escient.", exampleEn: "He spends money wisely." },
        { fr: "en vertu de", en: "by virtue of", example: "En vertu de la loi…", exampleEn: "By virtue of the law…" },
        { fr: "dans la mesure du possible", en: "as far as possible", example: "Répondez dans la mesure du possible.", exampleEn: "Reply as far as possible." },
        { fr: "tenir à", en: "to care about / be attached to", example: "Je tiens à ces valeurs.", exampleEn: "I care about these values." },
        { fr: "relever de", en: "to fall under / concern", example: "Cet aspect relève du droit public.", exampleEn: "This aspect falls under public law." },
        { fr: "à propos de", en: "with regard to", example: "À propos de votre demande…", exampleEn: "With regard to your request…" },
        { fr: "en quelque sorte", en: "in a way", example: "Il s'agit, en quelque sorte, d'un retour aux sources.", exampleEn: "It's, in a way, a return to the sources." },
      ],
    },
  ],

  phrases: [
    { fr: "Il ne fait pas de doute que", en: "There is no doubt that", example: "Il ne fait pas de doute que l'avenir est incertain.", exampleEn: "There is no doubt that the future is uncertain." },
    { fr: "sans que cela nuise à", en: "without harming", example: "Il faut être exigeant sans que cela nuise à la motivation.", exampleEn: "Be demanding without harming motivation." },
    { fr: "pour peu que", en: "if only / provided that", example: "Pour peu qu'on écoute, on comprend.", exampleEn: "If one only listens, one understands." },
    { fr: "à plus forte raison", en: "even more reason / a fortiori", example: "S'il est en retard, à plus forte raison les autres.", exampleEn: "If he's late, all the more reason the others are." },
    { fr: "s'en remettre à", en: "to defer to / rely on", example: "Je m'en remets à votre jugement.", exampleEn: "I defer to your judgment." },
    { fr: "être le théâtre de", en: "to be the scene of", example: "La ville fut le théâtre de violents affrontements.", exampleEn: "The city was the scene of violent clashes." },
    { fr: "défrayer la chronique", en: "to make the headlines", example: "Cette affaire défraie la chronique.", exampleEn: "This case is all over the news." },
    { fr: "mettre sur le même pied", en: "to put on the same footing", example: "Ne mettons pas tout sur le même pied.", exampleEn: "Let's not put everything on the same footing." },
    { fr: "se faire entendre", en: "to make oneself heard", example: "Les opposants se sont fait entendre.", exampleEn: "The opponents made themselves heard." },
    { fr: "livre de chevet", en: "one's favourite/bedside book", example: "Ce roman est l'un de ses livres de chevet.", exampleEn: "This novel is one of his favourite reads." },
    { fr: "à quelques nuances près", en: "with minor reservations", example: "Le texte convient, à quelques nuances près.", exampleEn: "The text is fine, with minor reservations." },
    { fr: "de manière générale", en: "generally speaking", example: "De manière générale, les résultats sont bons.", exampleEn: "Generally speaking, the results are good." },
  ],

  pronunciation: {
    phonemes: [
      { symbol: "isochronie", name: "Temps syllabique", examples: ["le rendez-vous", "la responsabilité"], note: "Syllables are quasi-isochronique (equal duration); a native rhythm." },
      { symbol: "liaison/élision", name: "Liaisons et élisions natives", examples: ["les différents_histoirs", "un_autour"], note: "At C2, master optional liaisons and enchaînements; dropped schwas are understood as natural." },
      { symbol: "schwa", name: "Le e-muet", examples: ["petite", "accepter", "de Guillaume"], note: "Native speech reduces the schwa; recognize 'je' → 'j' in fast speech." },
      { symbol: "r", name: "Le 'r' uvulaire", examples: ["Paris", "rendez-vous"], note: "In connected speech, the rhythmic group final—not the word—carries stress." },
      { symbol: "vowel length", name: "Long vowels + r", examples: ["fête, être (lost long)", "carte, pince (variant)", "peur"], note: "Long vowels appear before /ʁ/, /v/, /z/, /ʒ/, /l/ in some dialects — quality beats length." },
      { symbol: "accent d'insistance", name: "Expression emphasis", examples: ["C'est absurde !", "Moi, je resterai."], note: "Stress extracted for contrast; keep your vowels clear when emphasizing." },
    ],
    minimalPairs: [
      { a: "il fut", b: "il fut ré" },
      { a: "je", b: "jus" },
      { a: "ils", b: "il" },
      { a: "fait", b: "fé" },
      { a: "mais", b: "mes" },
      { a: "nous", b: "nous" },
      { a: "cétait", b: "c'est était" },
      { a: "dessus", b: "dessous" },
      { a: "sont", b: "suint" },
      { a: "temps", b: "tant" },
      { a: "brun", b: "brin" },
      { a: "peur", b: "pour" },
    ],
    rules: [
      "French rhythm: group-final stress, no word stress — use the group, not the word, as the unit.",
      "Liaison is a three-level system; using an optional liaison in the right place signals fluency.",
      "The 'r' is articulated once in continuous speech — avoid trilling and avoid dropping it (except in mute -e).",
      "In exclamation and insistence, the emphasized word stays clear; the vowels do not reduce.",
      "Master the schwa: in 'petit', 'de', 'me' the native speech glides ('ptit', 'd', 'm').",
    ],
  },

  listening: [
    {
      id: "c2-listen-1",
      title: "Discours politique",
      text: "Mesdames et Messieurs, on nous répète que la réforme est inévitable. Il serait peut-être temps de s'interroger sur cette prétendue fatalité. Quand je vois que des décisions structurelles se prennent sans débat public, sans étude d'impact réellement indépendante, je m'inquiète, non pas de la réforme elle-même, mais de la méthode. Car une réforme qui n'emporte pas l'adhésion des citoyens, si brillante soit-elle sur le papier, est une réforme qui se heurtera à la réalité. Nous ne demandons pas l'immobilisme ; nous exigeons une véritable concertation. Et j'ajouterai ceci : la confiance, cela se construit, pas cela ne se décrète. Soyons lucides, soyons exigeants, et faisons de ce texte un objet de pensée collective plutôt qu'un bulldozer.",
      questions: [
        {
          id: "c2-listen-1-q1",
          type: "multiple_choice",
          prompt: "Que dénonce principalement l'orateur ?",
          options: ["La réforme elle-même", "La méthode choisie", "Les citoyens", "L'immobilisme"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c2-listen-1-q2",
          type: "multiple_choice",
          prompt: "Que souhaite l'orateur ?",
          options: ["Le rejet total de la réforme", "Une véritable concertation", "Une réforme plus radicale", "Le silence"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c2-listen-1-q3",
          type: "multiple_choice",
          prompt: "Quelle phrase résume le mieux sa position ?",
          options: ["Soyons lucides, soyons exigeants", "La réforme est inévitable", "Les citoyens ont tort", "Le papier est brillant"],
          answer: 0,
          skill: "listening",
        },
      ],
    },
    {
      id: "c2-listen-2",
      title: "Émission littéraire",
      text: "Bonjour à toutes et à tous. En cette fin d'année, je voudrais vous parler d'un premier roman qui m'a bouleversé : « L'ombre des algues », de Fatou Dione. Ce texte est bien plus qu'une histoire de famille ; c'est une méditation sur la mémoire, sur ce que l'on transmet malgré soi, sur ces silences qui façonnent une lignée. Ce qui m'a frappé, c'est la langue : une langue précise, presque chirurgicale, qui n'exclut jamais la tendresse. L'auteure, d'origine sénégalaise, installée en Belgique, écrit depuis les marges — et c'est justement cette position de vigie qui donne au roman sa force d'interpellation. Je sais que certains lecteurs trouveront la narration exigeante ; mais je les invite à ne pas s'arrêter aux apparences. La récompense est ici à la hauteur de l'effort.",
      questions: [
        {
          id: "c2-listen-2-q1",
          type: "multiple_choice",
          prompt: "Quel est le sujet principal apparent du roman ?",
          options: ["Les algues", "Une histoire de famille", "La Belgique", "Un crime"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c2-listen-2-q2",
          type: "multiple_choice",
          prompt: "Comment l'oratrice qualifie-t-elle la langue du roman ?",
          options: ["Simple", "Précise et chirurgicale", "Compliquée et froide", "Rare"],
          answer: 1,
          skill: "listening",
        },
        {
          id: "c2-listen-2-q3",
          type: "multiple_choice",
          prompt: "Quel est le pays d'origine de l'auteure ?",
          options: ["Le Sénégal", "La Belgique", "La France", "Le Canada"],
          answer: 0,
          skill: "listening",
        },
        {
          id: "c2-listen-2-q4",
          type: "multiple_choice",
          prompt: "Que répond l'oratrice aux lecteurs rebutés ?",
          options: ["D'abandonner", "Ne pas s'arrêter aux apparences", "De lire plus vite", "De lire le résumé"],
          answer: 1,
          skill: "listening",
        },
      ],
    },
  ],

  reading: [
    {
      id: "c2-read-1",
      title: "Le silence comme langage",
      text: "On oppose volontiers la parole au silence, comme si l'une n'était que lumière et l'autre pur néant. Or la réalité est autre : le silence est une parole, et même la plus éloquente des paroles. Dans nos sociétés bavardes, on confond exhibition et expression ; on croit que se dire, c'est tout dire, sans mesurer que la parole ne prend sa pleine valeur que parce qu'elle est parfois suspendue, différée, ménagée. L'écrivain qui laisse un blanc après une phrase fatidique ne fait pas un aveu d'impuissance ; il témoigne, au contraire, d'une souveraine exigence. De même, dans le dialogue, le silence de l'un n'est pas la défaite de l'autre : c'est un temps de respiration où l'échange se consume et se relance. Apprendre une langue, c'est aussi apprendre à se taire dans cette langue — à choisir ce qui ne sera pas dit.",
      questions: [
        {
          id: "c2-read-1-q1",
          type: "multiple_choice",
          prompt: "L'auteur considère le silence comme :",
          options: ["Un néant", "Une forme de parole", "Un obstacle", "Une faiblesse"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-read-1-q2",
          type: "multiple_choice",
          prompt: "Quel est le reproche fait aux sociétés bavardes ?",
          options: ["De parler trop peu", "De confondre exhibition et expression", "De se taire", "D'écrire des livres"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-read-1-q3",
          type: "multiple_choice",
          prompt: "Selon le texte, le blanc laissé par l'écrivain est :",
          options: ["Un aveu d'impuissance", "Un signe de rigueur", "Une erreur", "Une mode"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-read-1-q4",
          type: "multiple_choice",
          prompt: "La thèse finale du texte est que :",
          options: ["Il faut toujours parler", "Apprendre une langue implique d'apprendre à se taire", "Le silence est interdit", "Il faut lire moins"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
    {
      id: "c2-read-2",
      title: "Nation, mémoire, transmission",
      text: "Ce que l'on nomme communément « la mémoire nationale » n'existe pas plus que la mémoire d'un individu : elle est une construction, tissée de récits, de silences, d'oubli volontaire. Les historiens le savent, qui traitent les archives autant que les absences. Mais cette construction n'est pas un simple enjeu de spécialistes : elle nourrit le sentiment d'appartenance, justifie des institutions, oriente des politiques. Le danger surgit lorsque ce récit se fige en dogme ou, à l'inverse, se dissout dans l'indifférence. Entre ces deux écueils, la tâche de la transmission est délicate : il s'agit à la fois de ne pas sacraliser le passé et de ne pas le congédier d'un revers de main. C'est là, précisément, que l'école, les musées et les institutions culturelles jouent un rôle irremplaçable : faire circuler le passé sans en faire un fétiche.",
      questions: [
        {
          id: "c2-read-2-q1",
          type: "multiple_choice",
          prompt: "Selon l'auteur, la mémoire nationale est :",
          options: ["Une donnée fixe", "Une construction", "Un trésor naturel", "Une invention récente"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-read-2-q2",
          type: "multiple_choice",
          prompt: "Quels sont les deux dangers évoqués ?",
          options: ["Le dogme et l'indifférence", "L'école et les musées", "Le passé et l'avenir", "La peur et la colère"],
          answer: 0,
          skill: "reading",
        },
        {
          id: "c2-read-2-q3",
          type: "multiple_choice",
          prompt: "Quel rôle l'auteur attribue-t-il aux institutions culturelles ?",
          options: ["Sacraliser le passé", "Faire circuler le passé sans en faire un fétiche", "Interdire l'histoire", "Vendre des souvenirs"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-read-2-q4",
          type: "multiple_choice",
          prompt: "Le mot « fétiche » dans ce contexte signifie :",
          options: ["Un objet décoratif", "Un objet de culte excessif", "Un livre ancien", "Un monument"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  writingPrompts: [
    {
      id: "c2-write-1",
      title: "Dissertation",
      task: "Rédigez une dissertation de 350 à 400 mots : « Le langage est-il un instrument ou une prison ? » Structurez (thèse, antithèse, synthèse) et citez au moins deux exemples culturels.",
      minWords: 350,
    },
    {
      id: "c2-write-2",
      title: "Prise de position",
      task: "Rédigez un éditorial de 300 à 350 mots pour un journal francophone : « La place du français dans la mondialisation ». Ton incisif et registre soutenu.",
      minWords: 300,
    },
  ],

  speakingPrompts: [
    {
      id: "c2-speaking-1",
      title: "Exposé magistral",
      scenario: "Présentez pendant 5 minutes : « La transmission de la mémoire ». Guidé par une structure : constat, analyse, enjeux, propositions. Utilisez le registre soutenu et des figures de style.",
      hint: "Il ne s'agit pas tant de… que de… / Encore faut-il… / En guise de conclusion…",
    },
    {
      id: "c2-speaking-2",
      title: "Débat hostile",
      scenario: "Un interlocuteur conteste vos idées avec agressivité. Répondez avec calme, nuances et précision, sans perdre la politesse, en retournant ses arguments.",
      hint: "Je comprends votre agacement, mais… / Permettez-moi de préciser… / Vous faites un amalgame entre…",
    },
  ],

  stories: [
    {
      id: "c2-story-1",
      title: "La bibliothèque sans nom",
      level: "C2",
      dialogue: [
        { speaker: "Narrateur", text: "Il y a des lieux qui ne figurent sur aucune carte. La bibliothèque sans nom était de ceux-là : une salle voûtée, au fond d'une impasse, que seuls quelques initiés connaissaient." },
        { speaker: "Hélène", text: "Vous êtes sûre que c'est ici ? Il n'y a ni enseigne, ni domicile." },
        { speaker: "Le bibliothécaire", text: "C'est précisément pour cela que nous existons, Madame. Les livres les plus précieux sont ceux qu'on ne trouve pas." },
        { speaker: "Hélène", text: "Un manuscrit de Marguerite Yourcenar, dites-vous ?" },
        { speaker: "Le bibliothécaire", text: "Marguerite, oui. Mais celui-ci, elle ne l'a jamais publié. Il contient une confession qu'elle jugeait trop intime." },
        { speaker: "Hélène", text: "Et vous me la montreriez ?" },
        { speaker: "Le bibliothécaire", text: "Je vous montre le chemin. Le choix vous appartient. Car lire, c'est parfois enfreindre un vœu — celui que l'auteure s'était fait à elle-même." },
      ],
      questions: [
        {
          id: "c2-story-1-q1",
          type: "multiple_choice",
          prompt: "Pourquoi la bibliothèque est-elle inconnue sur les cartes ?",
          options: ["Elle est récente", "Elle est privée de nom et discrète", "Elle est fermée", "Elle est virtuelle"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-story-1-q2",
          type: "multiple_choice",
          prompt: "Quel manuscrit Hélène recherche-t-elle ?",
          options: ["Un roman de Proust", "Un manuscrit de Marguerite Yourcenar", "Une lettre de Voltaire", "Un poème de Rimbaud"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-story-1-q3",
          type: "multiple_choice",
          prompt: "Pourquoi le texte n'a-t-il jamais été publié ?",
          options: ["Il était perdu", "Il contenait une confession intime", "Il était illisible", "L'auteure était inconnue"],
          answer: 1,
          skill: "reading",
        },
        {
          id: "c2-story-1-q4",
          type: "multiple_choice",
          prompt: "Quel dilemme le bibliothécaire soulève-t-il ?",
          options: ["Acheter ou voler", "Lire ou respecter le vœu de l'auteure", "Publier ou détruire", "Vendre ou garder"],
          answer: 1,
          skill: "reading",
        },
      ],
    },
  ],

  scenarios: [
    {
      id: "c2-scenario-ouverte",
      title: "Négociation diplomatique",
      setting: "Vous êtes le nouveau chef de la délégation francophone dans une négociation multilatérale sur les océans.",
      dialogue: [
        { speaker: "Présidente", text: "Mesdames et Messieurs, nous sommes réunis pour fixer les objectifs de protection marine à 2030." },
        { speaker: "Délégué A", text: "Notre pays estime qu'un objectif de 30% de zones protégées est irréaliste au vu des enjeux économiques." },
        { speaker: "Vous", text: "Je voudrais d'abord saluer la franchise de notre collègue. Permettons-nous de rappeler, toutefois, que ces 30% sont un strict minimum scientifique, et non un plafond." },
        { speaker: "Délégué B", text: "Et où trouverons-nous les financements ?" },
        { speaker: "Vous", text: "C'est là que la solidarité francophone peut innover : créer un fonds commun, alimenté par les pays qui en ont les moyens, adossé à des mécanismes existants." },
        { speaker: "Délégué A", text: "Nous restons très réservés." },
        { speaker: "Vous", text: "Notre proposition, précisément, vous offre une voie de sortie : un seuil apparemment contraignant, mais une mise en œuvre étalée et souple, avec des étapes vérifiables." },
      ],
    },
  ],

  culturalNotes: [
    {
      title: "L'Académie française et la langue",
      body: "Created in 1635, the Académie française still debates, dictionaries and language politics. Writers like Marguerite Yourcenar (first woman elected in 1980) embody this institution. Even if its recommendations are soft, it remains a cultural monument of the French-speaking world.",
    },
    {
      title: "La tradition de la dissertation",
      body: "The dissertation is the pinnacle of French school training: thesis, antithesis, synthesis, with examples, in a well-argued chain. This form shapes both academic and political discourse — understanding it is key to French argumentative culture.",
    },
    {
      title: "Les voies de la coopération francophone",
      body: "Beyond Europe, the Organisation internationale de la Francophonie (OIF) works on education, peace and digital as common goods. Its summits and agencies represent a diplomatic force often invisible to the public, valued especially by African, Canadian and European members.",
    },
  ],

  test: {
    passingScore: 270,
    maxScore: 430,
    listening: [
      {
        id: "c2-test-l1",
        type: "multiple_choice",
        prompt: "Vous entendez : « Loin de traduire une faiblesse, cette pudeur procède d'une exigence morale qui traverse toute l'œuvre. » — La pudeur est ici :",
        audio: "Loin de traduire une faiblesse, cette pudeur procède d'une exigence morale qui traverse toute l'œuvre.",
        options: ["Une faiblesse", "Une exigence morale", "Une ruse", "Un hasard"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c2-test-l2",
        type: "multiple_choice",
        prompt: "Vous entendez : « À supposer que le texte soit authentique, il n'en reste pas moins que sa portée juridique est contestable. » — Que dit-on ?",
        audio: "À supposer que le texte soit authentique, il n'en reste pas moins que sa portée juridique est contestable.",
        options: ["Le texte est faux", "Même vrai, sa portée juridique est contestable", "Il est inapplicable", "Il est déjà appliqué"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c2-test-l3",
        type: "multiple_choice",
        prompt: "Vous entendez : « Il s'en est fallu de peu que la médiation n'échoue, tant les positions semblaient irréconciliables. » — Que s'est-il passé ?",
        audio: "Il s'en est fallu de peu que la médiation n'échoue, tant les positions semblaient irréconciliables.",
        options: ["La médiation a échoué", "La médiation a échappé à l'échec de justesse", "La médiation est reportée", "La médiation était impossible"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c2-test-l4",
        type: "multiple_choice",
        prompt: "Vous entendez : « Sans doute est-ce là le paradoxe le plus fécond de notre temps : plus la technique s'affine, plus la question du sens s'impose. » — Quel paradoxe soulève-t-on ?",
        audio: "Sans doute est-ce là le paradoxe le plus fécond de notre temps : plus la technique s'affine, plus la question du sens s'impose.",
        options: ["La technique supprime le sens", "La technique rend la question du sens plus urgente", "Le sens détruit la technique", "Le sens est une invention récente"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c2-test-l5",
        type: "multiple_choice",
        prompt: "Vous entendez : « Quoi qu'il vous en semble, force est de constater que les chiffres corroborent notre analyse. » — L'orateur :",
        audio: "Quoi qu'il vous en semble, force est de constater que les chiffres corroborent notre analyse.",
        options: ["Demande votre avis", "Affirme que les chiffres confirment son analyse", "Réfute les chiffres", "Pense que vous avez raison"],
        answer: 1,
        skill: "listening",
      },
      {
        id: "c2-test-l6",
        type: "multiple_choice",
        prompt: "Vous entendez : « Autant dire que sans une réévaluation de la politique salariale, l'exode des compétences va s'amplifier. » — Que signifie cette phrase ?",
        audio: "Autant dire que sans une réévaluation de la politique salariale, l'exode des compétences va s'amplifier.",
        options: ["Il faut augmenter les salaires pour éviter l'exode", "L'exode est sans lien avec les salaires", "L'exode va ralentir", "Les salaires vont baisser"],
        answer: 0,
        skill: "listening",
      },
    ],
    reading: [
      {
        id: "c2-test-r1",
        type: "multiple_choice",
        prompt: "« Sa démonstration, pour brillante qu'elle fût, ne dissipait pas les soupçons qui pesaient sur la méthode. » — L'auteur :",
        options: ["Valide totalement", "Loue la forme mais doute de la méthode", "Rejette tout", "Ne s'exprime pas"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c2-test-r2",
        type: "multiple_choice",
        prompt: "« Il n'y a pas loin du Capitole à la Roche Tarpéienne » signifie :",
        options: ["Le succès peut se changer en échec", "La distance est courte", "Les monuments sont proches", "Il faut voyager"],
        answer: 0,
        skill: "reading",
      },
      {
        id: "c2-test-r3",
        type: "multiple_choice",
        prompt: "« La proposition, en dépit de sa séduction formelle, souffre d'un vice de conception. » — Le mot « séduction » ici signifie :",
        options: ["Une tromperie", "Un attrait", "Un manque", "Un avantage"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c2-test-r4",
        type: "multiple_choice",
        prompt: "« Il n'est de richesse que d'hommes » — le sens de cette phrase est :",
        options: ["L'argent est la vraie richesse", "Les hommes sont la vraie richesse", "La richesse se définit", "Rien ne vaut l'or"],
        answer: 1,
        skill: "reading",
      },
      {
        id: "c2-test-r5",
        type: "multiple_choice",
        prompt: "« L'entreprise connut un interrègne de six mois avant la désignation du nouveau directeur général. » — « interrègne » signifie :",
        options: ["Une période sans direction", "Un règne dispensé", "Une faillite", "Une fusion"],
        answer: 0,
        skill: "reading",
      },
      {
        id: "c2-test-r6",
        type: "multiple_choice",
        prompt: "« Fût-ce au prix de notre confort, il nous faut consentir à cet effort collectif. » — Le sens est :",
        options: ["Acceptons le confort", "Acceptons l'effort même au prix du confort", "Refusons l'effort", "Exigeons plus de confort"],
        answer: 1,
        skill: "reading",
      },
    ],
    writing: [
      {
        id: "c2-test-w1",
        title: "Dissertation",
        prompt: "Rédigez une dissertation de 350 à 400 mots : « La langue est-elle le reflet d'une culture ou son instrument ? » Structurez rigoureusement et illustrez.",
        minWords: 350,
      },
      {
        id: "c2-test-w2",
        title: "Éditorial",
        prompt: "Écrivez un éditorial (300 à 350 mots) : « La vigilance démocratique à l'ère numérique ». Registre soutenu, ton engagé.",
        minWords: 300,
      },
    ],
    speaking: [
      {
        id: "c2-test-s1",
        title: "Exposé",
        prompt: "Présentez en 5 minutes : « Le rôle de la mémoire dans la construction d'un avenir ». Structure claire, registre soutenu, figures de style.",
        hint: "L'un des enjeux consiste en… / Nous ne saurions… / En définitive…",
      },
      {
        id: "c2-test-s2",
        title: "Débat contradictoire",
        prompt: "Affrontez la thèse opposée : « Les réseaux sociaux sont un bienfait démocratique ». Réfutez avec méthode et calme.",
        hint: "Ce serait oublier que… / Il y a là un raccourci / Le problème ne se situe pas là…",
      },
    ],
    pronunciation: [
      { id: "c2-test-p1", type: "pronunciation", prompt: "Prononcez ce mot :", word: "l'irréconciliable", ipa: "/liʁe.kɔ̃.si.ljabl/", skill: "pronunciation" },
      { id: "c2-test-p2", type: "pronunciation", prompt: "Prononcez ce mot :", word: "souveraineté", ipa: "/su.vʁɛn.te/", skill: "pronunciation" },
      { id: "c2-test-p3", type: "pronunciation", prompt: "Prononcez ce mot :", word: "extraordinairement", ipa: "/ɛkstʁaɔʁdinɛʁmɑ̃/", skill: "pronunciation" },
      { id: "c2-test-p4", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Il s'en est fallu de peu", ipa: "/il sɑ̃ nɛ faly də pø/", skill: "pronunciation" },
      { id: "c2-test-p5", type: "pronunciation", prompt: "Prononcez cette phrase :", word: "Quelle que soit la difficulté, il faut avancer", ipa: "/kɛl kə swa la difikylte il fo avɑ̃se/", skill: "pronunciation" },
    ],
  },
};